//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/ANSUploaderDelegate-Protocol.h>

@class ANSCrashMetadata, ANSEventFilter, ANSMetadata, ANSSettings, ANSTimer, ANSUploader, FABCertificatePinner, NSMutableDictionary, NSOperationQueue, NSString, NSURL;

@interface ANSAnswersController : NSObject <ANSUploaderDelegate>
{
    NSOperationQueue *_eventQueue;
    NSString *_rootEventDirectory;
    NSString *_crashMetadataPath;
    ANSMetadata *_metadata;
    ANSCrashMetadata *_crashMetadata;
    ANSUploader *_uploader;
    NSURL *_currentLogURL;
    FABCertificatePinner *_certPinner;
    ANSEventFilter *_eventFilter;
    ANSSettings *_settings;
    ANSTimer *_flushTimer;
    NSMutableDictionary *_retryTimerMap;
}

+ (id)rootDirectory;
@property(readonly, nonatomic) NSMutableDictionary *retryTimerMap; // @synthesize retryTimerMap=_retryTimerMap;
@property(readonly, nonatomic) ANSTimer *flushTimer; // @synthesize flushTimer=_flushTimer;
@property(readonly, nonatomic) ANSSettings *settings; // @synthesize settings=_settings;
@property(readonly, nonatomic) ANSEventFilter *eventFilter; // @synthesize eventFilter=_eventFilter;
@property(readonly, nonatomic) FABCertificatePinner *certPinner; // @synthesize certPinner=_certPinner;
@property(readonly, nonatomic) NSURL *currentLogURL; // @synthesize currentLogURL=_currentLogURL;
@property(readonly, nonatomic) ANSUploader *uploader; // @synthesize uploader=_uploader;
@property(readonly, nonatomic) ANSCrashMetadata *crashMetadata; // @synthesize crashMetadata=_crashMetadata;
@property(readonly, nonatomic) ANSMetadata *metadata; // @synthesize metadata=_metadata;
@property(readonly, nonatomic) NSString *crashMetadataPath; // @synthesize crashMetadataPath=_crashMetadataPath;
@property(readonly, nonatomic) NSString *rootEventDirectory; // @synthesize rootEventDirectory=_rootEventDirectory;
@property(readonly, nonatomic) NSOperationQueue *eventQueue; // @synthesize eventQueue=_eventQueue;
- (void).cxx_destruct;
- (id)timerForUniqueName:(id)arg1 initialRetryValue:(double)arg2;
- (void)uploader:(id)arg1 completedRequest:(id)arg2 withResponse:(id)arg3 uniqueName:(id)arg4 error:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)uploader:(id)arg1 session:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)uploader:(id)arg1 didFinishUploadWithUniqueName:(id)arg2 error:(id)arg3;
- (id)uploader:(id)arg1 filePathForUniqueName:(id)arg2;
- (id)multipartMimeURLWithBoundary:(id)arg1;
- (id)boundaryFromURL:(id)arg1;
- (void)uploadMultipartFiles:(id)arg1;
- (void)uploadAllMultipartFiles;
- (void)cleanupAndProcessExistingFiles;
- (id)uploadOperationForFileAtURL:(id)arg1 withBoundary:(id)arg2;
- (id)operationsForCompressedLog:(id)arg1;
- (id)operationsForUncompressedLog:(id)arg1;
- (void)rotateAndSubmitCurrentLog;
- (BOOL)shouldSubmitLogAtURL:(id)arg1;
- (void)enqueueEvent:(id)arg1;
- (id)beginActivityOperationWithActivityName:(id)arg1 options:(unsigned long long)arg2;
- (void)logCrashEvent:(id)arg1;
- (BOOL)shouldLogEvent;
- (void)logEvent:(id)arg1;
- (void)rotateCrashMetadataWithCurrentMetadata:(id)arg1;
- (void)removeAllLogs;
- (void)flushTimerFired;
- (void)initializeSettingsIfNeededWithFabricSettings:(id)arg1;
- (void)fabricSettingsDidBecomeAvailable:(id)arg1;
- (id)generateNewLogPath;
- (void)applicationLifecycleEvent:(id)arg1;
- (void)registerForApplicationLifecycleEvents;
- (id)uploaderWithQueue:(id)arg1 delegate:(id)arg2;
- (id)sharedFabricSDK;
- (id)crashMetadataPathForRootDirectory:(id)arg1;
- (id)eventDirectoryForRootDirectory:(id)arg1;
- (id)initWithBetaToken:(id)arg1 rootDirectory:(id)arg2;
- (id)initWithBetaToken:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

