//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBackgroundActivityScheduler, NSString;

@interface ANSTimer : NSObject
{
    BOOL _repeats;
    NSString *_timerIdentifier;
    double _timeInterval;
    struct dispatch_queue_s *_queue;
    CDUnknownBlockType _timerBlock;
    struct dispatch_source_s *_timerSource;
    NSBackgroundActivityScheduler *_backgroundActivityScheduler;
}

@property(retain, nonatomic) NSBackgroundActivityScheduler *backgroundActivityScheduler; // @synthesize backgroundActivityScheduler=_backgroundActivityScheduler;
@property(nonatomic) struct dispatch_source_s *timerSource; // @synthesize timerSource=_timerSource;
@property(nonatomic) BOOL repeats; // @synthesize repeats=_repeats;
@property(copy, nonatomic) CDUnknownBlockType timerBlock; // @synthesize timerBlock=_timerBlock;
@property(nonatomic) struct dispatch_queue_s *queue; // @synthesize queue=_queue;
@property(nonatomic) double timeInterval; // @synthesize timeInterval=_timeInterval;
@property(readonly, nonatomic) NSString *timerIdentifier; // @synthesize timerIdentifier=_timerIdentifier;
- (void).cxx_destruct;
- (void)scheduleBackgroundActivityWithName:(id)arg1;
- (void)scheduleDispatchTimer;
- (void)scheduleTimer;
- (void)dealloc;
- (id)initWithTimeInterval:(double)arg1 onQueue:(struct dispatch_queue_s *)arg2 timerIdentifier:(id)arg3 repeats:(BOOL)arg4 block:(CDUnknownBlockType)arg5;
- (id)initWithTimeInterval:(double)arg1 timerIdentifier:(id)arg2 repeats:(BOOL)arg3 block:(CDUnknownBlockType)arg4;

@end

