//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct BaikeInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    int _field5;
    unsigned int _field6[1];
};

struct BriefingBalanceSheet_A {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    int _field6;
    unsigned int _field7[1];
};

struct BriefingBalanceSheet_HK_Fin {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    int _field7;
    unsigned int _field8[1];
};

struct BriefingBalanceSheet_HK_NoFin {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    int _field9;
    unsigned int _field10[1];
};

struct BriefingBalanceSheet_US {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    int _field10;
    unsigned int _field11[1];
};

struct BriefingBalanceSheet_US_BnkIns {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    int _field8;
    unsigned int _field9[1];
};

struct BriefingBuybackInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    int _field5;
    unsigned int _field6[1];
};

struct BriefingCashFlow_A {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    int _field6;
    unsigned int _field7[1];
};

struct BriefingCashFlow_HK {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    int _field7;
    unsigned int _field8[1];
};

struct BriefingCashFlow_US {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    int _field7;
    unsigned int _field8[1];
};

struct BriefingCompanyInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field10;
    int _field11;
    unsigned int _field12[1];
};

struct BriefingDividendInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    int _field5;
    unsigned int _field6[1];
};

struct BriefingIncomeInfo_A {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    int _field9;
    unsigned int _field10[1];
};

struct BriefingIncomeInfo_HK_Fin {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    int _field9;
    unsigned int _field10[1];
};

struct BriefingIncomeInfo_HK_NoFin {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    int _field10;
    unsigned int _field11[1];
};

struct BriefingIncomeInfo_US {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    int _field10;
    unsigned int _field11[1];
};

struct BriefingIncomeInfo_US_BnkIns {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    int _field9;
    unsigned int _field10[1];
};

struct BriefingKeyIndexInfo_A {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    int _field10;
    unsigned int _field11[1];
};

struct BriefingSharesInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    int _field7;
    unsigned int _field8[1];
};

struct BriefingSplitInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    int _field6;
    unsigned int _field7[1];
};

struct BulletinItem {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    int _field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    unsigned int _field5;
    unsigned int _field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    int _field8;
    unsigned int _field9[1];
};

struct CAS_Reference_Price {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    int _field8;
    unsigned int _field9[1];
};

struct CGSize {
    double width;
    double height;
};

struct CLSMachOFile {
    int fd;
    unsigned long long mappedSize;
    void *mappedFile;
};

struct CLSMachOSlice {
    void *startAddress;
    int cputype;
    int cpusubtype;
};

struct ChannelName {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    int _field3;
    int _field4;
    unsigned int _field5[1];
};

struct EquitiesData {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    long long _field3;
    long long _field4;
    unsigned long long _field5;
    int _field6;
    int _field7;
    int _field8;
    int _field9;
    unsigned long long _field10;
    int _field11;
    int _field12;
    unsigned long long _field13;
    unsigned long long _field14;
    int _field15;
    int _field16;
    int _field17;
    int _field18;
    int _field19;
    int _field20;
    unsigned int _field21[1];
};

struct FLHTTPSender {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    struct OMCriticalSection _field4;
    id _field5;
};

struct FLTCPProtoSender {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    id _field4;
    struct OMCriticalSection _field5;
};

struct GetMsgHistoryFullRsp {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    unsigned int _field3;
    struct RepeatedPtrField<msgcenter::MsgItem> _field4;
    unsigned long long _field5;
    _Bool _field6;
    int _field7;
    unsigned int _field8[1];
};

struct IndexData {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    int _field6;
    unsigned int _field7[1];
};

struct MarginTrading {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    _Bool _field3;
    _Bool _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    int _field8;
    unsigned int _field9[1];
};

struct MatterItem {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    unsigned int _field6;
    int _field7;
    unsigned int _field8[1];
};

struct MsgHead;

struct MsgItem {
    CDUnknownFunctionPointerType *_field1;
    struct MsgHead *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    int _field4;
    unsigned int _field5[1];
};

struct NNCFeedElementComm {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    int _field3;
    int _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    struct NNCFeedViewPermission *_field7;
    unsigned int _field8;
    _Bool _field9;
    _Bool _field10;
    _Bool _field11;
    _Bool _field12;
    _Bool _field13;
    int _field14;
    unsigned int _field15[1];
};

struct NNCFeedElementComment {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    struct NNCFeedElementUserInfo *_field3;
    unsigned long long _field4;
    unsigned int _field5;
    int _field6;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> _field7;
    unsigned long long _field8;
    struct NNCFeedElementUserInfo *_field9;
    unsigned int _field10;
    unsigned int _field11;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> _field12;
    struct NNCFeedElementLike *_field13;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementPictureInfo> _field14;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementPictureInfo> _field15;
    unsigned long long _field16;
    _Bool _field17;
    _Bool _field18;
    int _field19;
    int _field20;
    unsigned int _field21[1];
};

struct NNCFeedElementContent {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> _field2;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementPictureInfo> _field3;
    int _field4;
    unsigned int _field5[1];
};

struct NNCFeedElementLike {
    CDUnknownFunctionPointerType *_field1;
    _Bool _field2;
    unsigned int _field3;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementUserInfo> _field4;
    int _field5;
    unsigned int _field6[1];
};

struct NNCFeedElementOriginal {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> _field2;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementPictureInfo> _field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    int _field6;
    unsigned int _field7[1];
};

struct NNCFeedElementPicture {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    unsigned int _field3;
    unsigned int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    int _field8;
    unsigned int _field9[1];
};

struct NNCFeedElementPictureInfo {
    CDUnknownFunctionPointerType *_field1;
    struct NNCFeedElementPicture *_field2;
    struct NNCFeedElementPicture *_field3;
    struct NNCFeedElementPicture *_field4;
    struct NNCFeedElementPicture *_field5;
    struct NNCFeedElementPicture *_field6;
    int _field7;
    unsigned int _field8[1];
};

struct NNCFeedElementRichText {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    int _field3;
    unsigned int _field4;
    unsigned long long _field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    struct NNCFeedElementPictureInfo *_field10;
    unsigned int _field11;
    int _field12;
    unsigned int _field13[1];
};

struct NNCFeedElementSummary {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> _field2;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementPictureInfo> _field3;
    _Bool _field4;
    int _field5;
    unsigned int _field6[1];
};

struct NNCFeedElementUserInfo {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    unsigned int _field5;
    int _field6;
    unsigned int _field7[1];
};

struct NNCFeedModel {
    CDUnknownFunctionPointerType *_field1;
    struct NNCFeedElementComm *_field2;
    struct NNCFeedElementUserInfo *_field3;
    struct NNCFeedElementSummary *_field4;
    struct NNCFeedElementContent *_field5;
    struct NNCFeedElementOriginal *_field6;
    struct NNCFeedElementLike *_field7;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementComment> _field8;
    unsigned long long _field9;
    _Bool _field10;
    int _field11;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field12;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field13;
    struct RepeatedField<unsigned int> _field14;
    unsigned long long _field15;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementComment> _field16;
    unsigned int _field17;
    int _field18;
    unsigned int _field19[1];
};

struct NNCFeedViewPermission;

struct NNCFeedsListRsp {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    int _field3;
    _Bool _field4;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedModel> _field5;
    unsigned long long _field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    unsigned long long _field8;
    unsigned long long _field9;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field10;
    int _field11;
    unsigned int _field12[1];
};

struct NNCNewMsgContent {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> _field2;
    int _field3;
    int _field4;
    unsigned int _field5[1];
};

struct NNCNewMsgModel {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    struct NNCFeedElementUserInfo *_field3;
    struct NNCNewMsgContent *_field4;
    unsigned long long _field5;
    unsigned long long _field6;
    struct NNCFeedElementSummary *_field7;
    unsigned long long _field8;
    struct NNCFeedElementUserInfo *_field9;
    int _field10;
    int _field11;
    unsigned int _field12[1];
};

struct Ndt_Trd_AccItem {
    unsigned long long _field1;
    unsigned long long _field2;
    char _field3[32];
    char _field4[32];
    int _field5;
    int _field6;
    _Bool _field7;
    int _field8;
    int _field9;
    char _field10[16];
    char _field11[32];
    unsigned long long _field12;
    unsigned long long _field13;
    unsigned long long _field14;
    char _field15[32];
    char _field16[32];
};

struct News_Rsp_NewsInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field10;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field11;
    int _field12;
    unsigned int _field13[1];
};

struct OMCriticalSection {
    CDUnknownFunctionPointerType *_field1;
    void *_field2;
};

struct OMLParam {
    _Bool _field1;
    long long _field2;
    long long _field3;
    long long _field4;
    long long _field5;
    long long _field6;
    unsigned int _field7;
    unsigned int _field8;
    char *_field9;
    int _field10;
    char *_field11;
    int _field12;
};

struct OneLevelOrderBookDetail;

struct OneStockSimple {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned int _field9;
    unsigned int _field10;
    int _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    unsigned int _field16;
    unsigned int _field17;
    unsigned int _field18;
    unsigned int _field19;
    unsigned int _field20;
    unsigned long long _field21;
    unsigned int _field22;
    int _field23;
    unsigned long long _field24;
    unsigned long long _field25;
    unsigned long long _field26;
    unsigned int _field27;
    unsigned int _field28;
    unsigned int _field29;
    int _field30;
    unsigned int _field31;
    unsigned int _field32;
    int _field33;
    unsigned int _field34;
    struct EquitiesData *_field35;
    struct WarrantsData *_field36;
    struct IndexData *_field37;
    int _field38;
    unsigned int _field39;
    struct PlateData *_field40;
    struct TrustData *_field41;
    unsigned int _field42;
    unsigned int _field43;
    struct VCM_Trigger *_field44;
    struct CAS_Reference_Price *_field45;
    struct MarginTrading *_field46;
    unsigned int _field47;
    int _field48;
    unsigned int _field49[2];
};

struct OrderBookDetail {
    CDUnknownFunctionPointerType *_field1;
    struct OneLevelOrderBookDetail *_field2;
    struct OneLevelOrderBookDetail *_field3;
    int _field4;
    unsigned int _field5[1];
};

struct OwnerPlateInfo {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    long long _field3;
    int _field4;
    unsigned int _field5[1];
};

struct PickingStrategyInfo {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    unsigned int _field7;
    unsigned int _field8;
    struct PickingStrategyQuote *_field9;
    int _field10;
    unsigned int _field11[1];
};

struct PickingStrategyQuote {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    int _field3;
    unsigned int _field4[1];
};

struct PickingStrategyStocks_Rsp {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmdStockPick::StockCondition_Item> _field2;
    int _field3;
    _Bool _field4;
    unsigned int _field5;
    unsigned int _field6;
    int _field7;
    unsigned int _field8[1];
};

struct PlateData {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
    unsigned long long _field5;
    long long _field6;
    long long _field7;
    int _field8;
    int _field9;
    unsigned int _field10;
    unsigned int _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned long long _field14;
    int _field15;
    unsigned int _field16[1];
};

struct PlateSummary {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    int _field6;
    unsigned int _field7[1];
};

struct Plate_Elem_Data {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    int _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned int _field9;
    unsigned int _field10;
    int _field11;
    unsigned int _field12;
    unsigned long long _field13;
    unsigned long long _field14;
    unsigned int _field15;
    unsigned int _field16;
    unsigned long long _field17;
    unsigned int _field18;
    int _field19;
    unsigned int _field20;
    unsigned int _field21;
    unsigned int _field22;
    _Bool _field23;
    _Bool _field24;
    unsigned int _field25;
    unsigned int _field26;
    unsigned int _field27;
    unsigned int _field28;
    int _field29;
    unsigned int _field30;
    long long _field31;
    long long _field32;
    unsigned long long _field33;
    int _field34;
    unsigned int _field35;
    long long _field36;
    int _field37;
    unsigned int _field38;
    int _field39;
    unsigned int _field40;
    long long _field41;
    unsigned long long _field42;
    unsigned long long _field43;
    unsigned int _field44;
    int _field45;
    unsigned int _field46[2];
};

struct PriceItem {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    int _field3;
    int _field4;
    unsigned long long _field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
    unsigned int _field10;
    unsigned int _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    int _field16;
    int _field17;
    unsigned long long _field18;
    unsigned int _field19;
    int _field20;
    unsigned int _field21[1];
};

struct RepeatedField<int> {
    int *_field1;
    int _field2;
    int _field3;
};

struct RepeatedField<unsigned int> {
    unsigned int *_field1;
    int _field2;
    int _field3;
};

struct RepeatedPtrField<FTCmd6821::OneStockSimple> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementComment> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementPictureInfo> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementRichText> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedElementUserInfo> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<FTCmdNNCFeeds::NNCFeedModel> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<FTCmdStockPick::StockCondition_Item> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RepeatedPtrField<msgcenter::MsgItem> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct SectionGet_Rsp_SectionInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    _Bool _field5;
    int _field6;
    int _field7;
    unsigned int _field8[1];
};

struct StockCondition_Item {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned long long _field7;
    unsigned long long _field8;
    unsigned long long _field9;
    unsigned long long _field10;
    unsigned int _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    int _field16;
    unsigned long long _field17;
    unsigned int _field18;
    unsigned int _field19;
    int _field20;
    _Bool _field21;
    _Bool _field22;
    unsigned int _field23;
    unsigned int _field24;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field25;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field26;
    int _field27;
    unsigned int _field28[1];
};

struct StockCondition_Req {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned int _field9;
    int _field10;
    int _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned long long _field15;
    unsigned int _field16;
    unsigned int _field17;
    unsigned long long _field18;
    unsigned int _field19;
    int _field20;
    int _field21;
    int _field22;
    int _field23;
    int _field24;
    int _field25;
    int _field26;
    unsigned long long _field27;
    unsigned long long _field28;
    unsigned long long _field29;
    unsigned long long _field30;
    _Bool _field31;
    _Bool _field32;
    unsigned int _field33;
    unsigned int _field34;
    unsigned int _field35;
    unsigned int _field36;
    int _field37;
    unsigned int _field38[2];
};

struct StockCondition_Rsp {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmdStockPick::StockCondition_Item> _field2;
    int _field3;
    unsigned int _field4;
    unsigned int _field5;
    int _field6;
    unsigned int _field7[1];
};

struct StockDetailData_Res {
    CDUnknownFunctionPointerType *_field1;
    struct RepeatedPtrField<FTCmd6821::OneStockSimple> _field2;
    int _field3;
    int _field4;
    unsigned int _field5[1];
};

struct StockWiki {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    _Bool _field6;
    _Bool _field7;
    _Bool _field8;
    unsigned int _field9;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field10;
    unsigned int _field11;
    int _field12;
    unsigned int _field13[1];
};

struct SubsItem {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    int _field7;
    unsigned int _field8[1];
};

struct TrustData {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    int _field3;
    unsigned int _field4[1];
};

struct UsrStrateItem {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field2;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field3;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field4;
    unsigned long long _field5;
    unsigned long long _field6;
    int _field7;
    unsigned int _field8[1];
};

struct VCM_Trigger {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    int _field8;
    unsigned int _field9[1];
};

struct WarrantItem {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned int _field4;
    int _field5;
    unsigned long long _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned long long _field9;
    unsigned int _field10;
    unsigned int _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned long long _field14;
    unsigned long long _field15;
    unsigned long long _field16;
    unsigned long long _field17;
    unsigned int _field18;
    unsigned int _field19;
    unsigned int _field20;
    unsigned int _field21;
    unsigned int _field22;
    unsigned int _field23;
    int _field24;
    int _field25;
    unsigned int _field26;
    unsigned int _field27;
    long long _field28;
    unsigned long long _field29;
    long long _field30;
    long long _field31;
    long long _field32;
    unsigned int _field33;
    int _field34;
    unsigned int _field35[1];
};

struct WarrantList_Req {
    CDUnknownFunctionPointerType *_field1;
    unsigned long long _field2;
    int _field3;
    unsigned int _field4;
    struct RepeatedField<int> _field5;
    unsigned int _field6;
    int _field7;
    unsigned long long _field8;
    int _field9;
    unsigned int _field10;
    unsigned long long _field11;
    unsigned int _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    unsigned int _field16;
    int _field17;
    int _field18;
    int _field19;
    int _field20;
    unsigned int _field21;
    unsigned int _field22;
    unsigned int _field23;
    unsigned int _field24;
    unsigned int _field25;
    unsigned int _field26;
    int _field27;
    long long _field28;
    long long _field29;
    int _field30;
    int _field31;
    int _field32;
    int _field33;
    int _field34;
    int _field35;
    struct RepeatedField<int> _field36;
    int _field37;
    int _field38;
    unsigned int _field39[2];
};

struct WarrantsData {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    unsigned int _field9;
    unsigned int _field10;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field11;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field12;
    unsigned long long _field13;
    unsigned long long _field14;
    unsigned int _field15;
    unsigned int _field16;
    unsigned int _field17;
    unsigned int _field18;
    int _field19;
    int _field20;
    unsigned int _field21[1];
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct _TBXMLAttribute {
    char *_field1;
    char *_field2;
    struct _TBXMLAttribute *_field3;
};

struct _TBXMLAttributeBuffer {
    struct _TBXMLAttribute *_field1;
    struct _TBXMLAttributeBuffer *_field2;
    struct _TBXMLAttributeBuffer *_field3;
};

struct _TBXMLElement {
    char *_field1;
    char *_field2;
    struct _TBXMLAttribute *_field3;
    struct _TBXMLElement *_field4;
    struct _TBXMLElement *_field5;
    struct _TBXMLElement *_field6;
    struct _TBXMLElement *_field7;
    struct _TBXMLElement *_field8;
};

struct _TBXMLElementBuffer {
    struct _TBXMLElement *_field1;
    struct _TBXMLElementBuffer *_field2;
    struct _TBXMLElementBuffer *_field3;
};

struct __CFString;

struct __va_list_tag {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
    void *_field4;
};

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>;

struct clt_crypt_codec_clt_side {
    CDUnknownFunctionPointerType *_field1;
    char *_field2;
    unsigned int _field3;
    struct clt_pack_head _field4;
    struct util_byteios_net _field5;
    char *_field6;
    unsigned int _field7;
    struct clt_pack_head _field8;
    struct util_byteios_net _field9;
};

struct clt_pack_flag {
    unsigned int :1;
    unsigned int :7;
};

struct clt_pack_head {
    unsigned char _field1[2];
    unsigned char _field2;
    unsigned char _field3;
    unsigned short _field4;
    unsigned char _field5;
    unsigned int _field6;
    struct clt_pack_flag _field7;
    unsigned int _field8;
    unsigned short _field9;
    unsigned int _field10;
    unsigned char _field11;
    unsigned char _field12;
    unsigned char _field13[8];
};

struct ft_packer {
    CDUnknownFunctionPointerType *_field1;
    char *_field2;
    unsigned int _field3;
    struct clt_pack_head _field4;
    struct util_byteios_net _field5;
    char *_field6;
    unsigned int _field7;
    struct clt_pack_head _field8;
    struct util_byteios_net _field9;
};

struct news {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    int _field3;
    unsigned long long _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    int _field6;
    unsigned int _field7[1];
};

struct uregex;

struct util_byteios_net {
    _Bool _field1;
    char *_field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned int major;
    unsigned int minor;
    unsigned int bugfix;
} CDStruct_e24ffa00;

typedef struct {
    char *_field1;
    char *_field2;
    unsigned int _field3;
    unsigned int _field4;
} CDStruct_4355734a;

typedef struct {
    char *_field1;
    void *_field2;
    _Bool _field3;
    void *_field4;
    char *_field5;
    char *_field6;
    char *_field7;
    char *_field8;
    char *_field9;
    unsigned int _field10;
    _Bool _field11;
    _Bool _field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    unsigned int _field16;
} CDStruct_1e2a2a70;

typedef struct {
    long long _field1;
    int _field2;
} CDStruct_87dc826d;

typedef struct {
    char _field1[33];
    _Bool _field2;
    CDStruct_e24ffa00 _field3;
    CDStruct_e24ffa00 _field4;
    struct {
        void *_field1;
        unsigned long long _field2;
        void *_field3;
        void *_field4;
        void *_field5;
    } _field5;
    struct CLSMachOSlice _field6;
    long long _field7;
} CDStruct_fad71a87;

