//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CryptoUtil : NSObject
{
}

+ (struct OpaqueSecKeyRef *)getPublicKeyFromBase64String:(id)arg1 withTag:(id)arg2;
+ (struct OpaqueSecKeyRef *)RSAPublicKeyRefFromBase64String:(id)arg1 withTag:(id)arg2;
+ (id)stripPublicKeyHeader:(id)arg1;
+ (id)rsaDecryptWithData:(id)arg1 key:(struct OpaqueSecKeyRef *)arg2;
+ (id)decryptString:(id)arg1 RSAPrivateKey:(struct OpaqueSecKeyRef *)arg2 padding:(unsigned int)arg3;
+ (id)encryptString:(id)arg1 RSAPublicKey:(struct OpaqueSecKeyRef *)arg2 padding:(unsigned int)arg3;
+ (struct OpaqueSecKeyRef *)loadRSAPublicKeyRefWithAppTag:(id)arg1;
+ (BOOL)deleteRSAPublicKeyWithAppTag:(id)arg1;
+ (BOOL)updateRSAPublicKey:(id)arg1 appTag:(id)arg2;
+ (BOOL)saveRSAPublicKey:(id)arg1 appTag:(id)arg2 overwrite:(BOOL)arg3;
+ (id)generateRSAPublicKeyWithModulus:(id)arg1 exponent:(id)arg2;
+ (BOOL)generateRSAKeyWithKeySizeInBits:(int)arg1 publicKeyTag:(id)arg2 privateKeyTag:(id)arg3;
+ (id)fetchStatus:(int)arg1;

@end

