//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>
#import <FTEngine/NSCopying-Protocol.h>

@class NSData, NSDictionary, NSString;

@interface FLAccount : NSObject <NSCoding, NSCopying>
{
    BOOL _didReadFromKeychain;
    BOOL _rememberPassword;
    BOOL _autoLogin;
    BOOL _thirdPartyLogin;
    BOOL _isNewLogin;
    BOOL _isGuest;
    NSString *_login;
    NSString *_areaCode;
    NSString *_password;
    unsigned long long _userID;
    NSString *_nickName;
    NSString *_tgtgt;
    NSData *_tgtgtRandomKey;
    NSData *_clientSig;
    NSData *_clientKey;
    NSString *_deviceSig;
    NSString *_webSig;
    NSString *_uploadSig;
    NSString *_themeName;
    NSDictionary *_countryInfo;
}

+ (unsigned long long)getAccountUserIDWithOpenId:(id)arg1 tokenType:(id)arg2;
+ (void)saveAccountUserID:(unsigned long long)arg1 forOpenID:(id)arg2 tokenType:(id)arg3;
+ (id)getDeviceSigWithUserID:(unsigned long long)arg1;
+ (void)saveDeviceSigWithUserId:(unsigned long long)arg1 deviceSig:(id)arg2;
+ (id)guestAccount;
+ (id)accountWithDictionary:(id)arg1 randKey:(id)arg2;
@property(retain, nonatomic) NSDictionary *countryInfo; // @synthesize countryInfo=_countryInfo;
@property BOOL isGuest; // @synthesize isGuest=_isGuest;
@property(copy, nonatomic) NSString *themeName; // @synthesize themeName=_themeName;
@property(nonatomic) BOOL isNewLogin; // @synthesize isNewLogin=_isNewLogin;
@property(copy, nonatomic) NSString *uploadSig; // @synthesize uploadSig=_uploadSig;
@property(copy, nonatomic) NSString *webSig; // @synthesize webSig=_webSig;
@property(copy, nonatomic) NSString *deviceSig; // @synthesize deviceSig=_deviceSig;
@property(retain) NSData *clientKey; // @synthesize clientKey=_clientKey;
@property(retain) NSData *clientSig; // @synthesize clientSig=_clientSig;
@property(retain, nonatomic) NSData *tgtgtRandomKey; // @synthesize tgtgtRandomKey=_tgtgtRandomKey;
@property(copy, nonatomic) NSString *tgtgt; // @synthesize tgtgt=_tgtgt;
@property(nonatomic, getter=isThirdPartyLogin) BOOL thirdPartyLogin; // @synthesize thirdPartyLogin=_thirdPartyLogin;
@property(nonatomic, getter=isAutoLogin) BOOL autoLogin; // @synthesize autoLogin=_autoLogin;
@property(nonatomic, getter=isRememberPassword) BOOL rememberPassword; // @synthesize rememberPassword=_rememberPassword;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) unsigned long long userID; // @synthesize userID=_userID;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *areaCode; // @synthesize areaCode=_areaCode;
@property(copy, nonatomic) NSString *login; // @synthesize login=_login;
- (void).cxx_destruct;
- (id)debugDescription;
- (BOOL)couldAutoLogin;
- (BOOL)needUpdateLoginSig;
- (void)deleteFromKeychain;
- (void)saveToKeychain;
- (void)readFromKeychain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (BOOL)fillAccountWithDictionary:(id)arg1 randKey:(id)arg2;

@end

