//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FLAccountStatistic : NSObject
{
    NSString *_currency;
    double _openBlance;
    double _openStockValue;
    unsigned long long _tradesCount;
    double _turnover;
    double _profit;
    double _profitRate;
}

@property(nonatomic) double profitRate; // @synthesize profitRate=_profitRate;
@property(nonatomic) double profit; // @synthesize profit=_profit;
@property(nonatomic) double turnover; // @synthesize turnover=_turnover;
@property(nonatomic) unsigned long long tradesCount; // @synthesize tradesCount=_tradesCount;
@property(nonatomic) double openStockValue; // @synthesize openStockValue=_openStockValue;
@property(nonatomic) double openBlance; // @synthesize openBlance=_openBlance;
@property(copy, nonatomic) NSString *currency; // @synthesize currency=_currency;
- (void).cxx_destruct;

@end

