//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLAccountProtectionManager : NSObject
{
}

+ (id)shareInstance;
- (void)mainThreadPostNotification:(id)arg1 object:(id)arg2 resultInfo:(id)arg3;
- (void)deleteDevice:(id)arg1 userId:(unsigned long long)arg2 callBack:(CDUnknownBlockType)arg3;
- (void)updateDevice:(id)arg1 userId:(unsigned long long)arg2 deviceAlias:(id)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)fetchDeviceList:(unsigned long long)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)confirmSetAccountProtect:(id)arg1 userId:(unsigned long long)arg2 callBack:(CDUnknownBlockType)arg3;
- (void)setAccountProtect:(BOOL)arg1 deviceId:(id)arg2 userId:(unsigned long long)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)accountIsProtected:(unsigned long long)arg1 callBack:(CDUnknownBlockType)arg2;

@end

