//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FLAccountCash : NSObject
{
    BOOL _cleared;
    NSString *_currency;
    double _cash;
    double _puchasingPower;
    double _freezeCash;
    double _loanMax;
    double _recoverCash;
    double _withdrawCash;
    double _positionValue;
}

@property(nonatomic) BOOL cleared; // @synthesize cleared=_cleared;
@property(nonatomic) double positionValue; // @synthesize positionValue=_positionValue;
@property(nonatomic) double withdrawCash; // @synthesize withdrawCash=_withdrawCash;
@property(nonatomic) double recoverCash; // @synthesize recoverCash=_recoverCash;
@property(nonatomic) double loanMax; // @synthesize loanMax=_loanMax;
@property(nonatomic) double freezeCash; // @synthesize freezeCash=_freezeCash;
@property(nonatomic) double puchasingPower; // @synthesize puchasingPower=_puchasingPower;
@property(nonatomic) double cash; // @synthesize cash=_cash;
@property(copy, nonatomic) NSString *currency; // @synthesize currency=_currency;
- (void).cxx_destruct;

@end

