//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLAccountProtectionNetServer : NSObject
{
}

+ (id)shareInstance;
- (void)deleteDevice:(unsigned long long)arg1 deviceId:(id)arg2 callBack:(CDUnknownBlockType)arg3;
- (void)updateDeviceLockInfo:(unsigned long long)arg1 deviceId:(id)arg2 andDeviceInfo:(id)arg3 callBack:(CDUnknownBlockType)arg4;
- (void)fetchDevicesInfo:(unsigned long long)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)setDeviceLock:(unsigned long long)arg1 deviceLockInfo:(id)arg2 deviceId:(id)arg3 confirm:(int)arg4 callBack:(CDUnknownBlockType)arg5;
- (void)deviceIsLocked:(unsigned long long)arg1 callBack:(CDUnknownBlockType)arg2;

@end

