//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLOrder.h>

#import <FTEngine/FLATradeModel-Protocol.h>

@class FLAShareholderInfo, NSString;

@interface FLAOrder : FLOrder <FLATradeModel>
{
    BOOL _cancelFlag;
    BOOL _disableTradeFlag;
    int _tradeMarketType;
    int _status;
    int _type;
    int _orderGroupNumber;
    unsigned long long _orderIDHash;
    NSString *_otherSideText;
    NSString *_shareholderId;
}

@property(nonatomic) BOOL disableTradeFlag; // @synthesize disableTradeFlag=_disableTradeFlag;
@property(nonatomic) int orderGroupNumber; // @synthesize orderGroupNumber=_orderGroupNumber;
@property(nonatomic) BOOL cancelFlag; // @synthesize cancelFlag=_cancelFlag;
@property(copy, nonatomic) NSString *shareholderId; // @synthesize shareholderId=_shareholderId;
@property(copy, nonatomic) NSString *otherSideText; // @synthesize otherSideText=_otherSideText;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) int tradeMarketType; // @synthesize tradeMarketType=_tradeMarketType;
@property(nonatomic) unsigned long long orderIDHash; // @synthesize orderIDHash=_orderIDHash;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) FLAShareholderInfo *shareholderInfo;
- (BOOL)isPending;
- (BOOL)isSuccess;
- (BOOL)isFailed;
- (BOOL)priceAdjustable;
- (BOOL)removable;
- (BOOL)cancelable;
- (BOOL)editable;
- (long long)compareStatus:(id)arg1;
- (id)directionString;
- (id)statusText;
- (id)updateStatus;
- (id)typeText;
- (id)displayErrorMessage;
- (void)decodeWithOrder:(void *)arg1;
- (void)decodeWithDictionary:(id)arg1;
- (void)setCode:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

