//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLATradeModel-Protocol.h>

@class NSString;

@interface FLAShareholderInfo : NSObject <FLATradeModel>
{
    int _tradeMarketType;
    NSString *_shareholderId;
    NSString *_shareholderName;
}

@property(nonatomic) int tradeMarketType; // @synthesize tradeMarketType=_tradeMarketType;
@property(copy, nonatomic) NSString *shareholderName; // @synthesize shareholderName=_shareholderName;
@property(copy, nonatomic) NSString *shareholderId; // @synthesize shareholderId=_shareholderId;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)decodeWithShareholderInfo:(void *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

