//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/NSObject-Protocol.h>

@class GCDAsyncSocket, NSData, NSString;

@protocol FLAsyncSocketProxyProtocol <NSObject>

@optional
@property(readonly, nonatomic) unsigned short destinationPort;
@property(retain, nonatomic) NSString *destinationHost;
@property(retain, nonatomic) GCDAsyncSocket *proxySocket;
- (void)proxySocketDidReadLength:(unsigned long long)arg1 tag:(long long)arg2;
- (void)proxySocketDidReadData:(NSData *)arg1 withTag:(long long)arg2;
- (void)proxySocketDidConnect;
@end

