//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLAsyncSocketProxyClient.h>

#import <FTEngine/FLAsyncSocketProxyProtocol-Protocol.h>

@class GCDAsyncSocket, NSString;

@interface FLAsyncSocketProxyHTTPClient : FLAsyncSocketProxyClient <FLAsyncSocketProxyProtocol>
{
}

- (void)onDidReadDataWithNoTagAction:(id)arg1;
- (id)valueForHTTPFieldName:(id)arg1 fieldArray:(id)arg2;
- (void)onDidReadDataWithAuthorizeTagAction:(id)arg1 withTag:(long long)arg2;
- (void)proxySocketDidReadData:(id)arg1 withTag:(long long)arg2;
- (void)proxySocketDidReadLength:(unsigned long long)arg1 tag:(long long)arg2;
- (void)proxySocketDidConnect;
- (id)setProxyValue:(id)arg1 forHeader:(id)arg2;
- (void)openProxy;
- (void)writeData:(id)arg1 withTimeout:(double)arg2 tag:(long long)arg3;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2 socketQueue:(id)arg3 clientType:(unsigned long long)arg4;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(retain, nonatomic) NSString *destinationHost;
@property(readonly, nonatomic) unsigned short destinationPort;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) GCDAsyncSocket *proxySocket;
@property(readonly) Class superclass;

@end

