//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLSubAccount.h>

@class FLAShareholderInfo, NSArray, NSDate, NSString;

@interface FLASubAccount : FLSubAccount
{
    int _platformID;
    FLAShareholderInfo *_defaultShareholderSZ;
    FLAShareholderInfo *_defaultShareholderSH;
    NSArray *_shareholders;
    NSString *_platformIDString;
    NSDate *_lastRefreshDate;
    unsigned long long _fundID;
}

@property(nonatomic) unsigned long long fundID; // @synthesize fundID=_fundID;
@property(nonatomic) NSDate *lastRefreshDate; // @synthesize lastRefreshDate=_lastRefreshDate;
@property(copy, nonatomic) NSString *platformIDString; // @synthesize platformIDString=_platformIDString;
@property(nonatomic) int platformID; // @synthesize platformID=_platformID;
@property(retain, nonatomic) NSArray *shareholders; // @synthesize shareholders=_shareholders;
@property(retain, nonatomic) FLAShareholderInfo *defaultShareholderSH; // @synthesize defaultShareholderSH=_defaultShareholderSH;
@property(retain, nonatomic) FLAShareholderInfo *defaultShareholderSZ; // @synthesize defaultShareholderSZ=_defaultShareholderSZ;
- (void).cxx_destruct;
- (void)resetAccount;
- (id)createOrderWithStock:(id)arg1 code:(id)arg2 stockManager:(id)arg3;

@end

