//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLStock, FLSubAccount, NSString;

@interface FLBaseModel : NSObject <NSCopying>
{
    NSString *_code;
    NSString *_symbol;
    NSString *_name;
    FLStock *_stock;
    unsigned long long _marketType;
    FLSubAccount *_subAccount;
    long long _price;
    long long _quantity;
}

@property(nonatomic) long long quantity; // @synthesize quantity=_quantity;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(nonatomic) __weak FLSubAccount *subAccount; // @synthesize subAccount=_subAccount;
@property(nonatomic) unsigned long long marketType; // @synthesize marketType=_marketType;
@property(retain, nonatomic) FLStock *stock; // @synthesize stock=_stock;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *symbol; // @synthesize symbol=_symbol;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) NSString *turnoverString;
@property(readonly, nonatomic) NSString *priceString;
- (void)decodeWithDictionary:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

