//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/FLStockFilterQuoteInfo-Protocol.h>
#import <FTEngine/FLStockFilterRequest-Protocol.h>
#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLBaseStockFilterRequest : FTCodingModel <NSCopying, FLStockFilterRequest, FLStockFilterQuoteInfo>
{
    BOOL _sortAscend;
    BOOL _isAutoRequest;
    int _language;
    int _sortType;
    int _dataFrom;
    int _maxDataCount;
}

+ (id)request;
@property(nonatomic) BOOL isAutoRequest; // @synthesize isAutoRequest=_isAutoRequest;
@property(nonatomic) int maxDataCount; // @synthesize maxDataCount=_maxDataCount;
@property(nonatomic) int dataFrom; // @synthesize dataFrom=_dataFrom;
@property(nonatomic) int sortType; // @synthesize sortType=_sortType;
@property(nonatomic) BOOL sortAscend; // @synthesize sortAscend=_sortAscend;
@property(nonatomic) int language; // @synthesize language=_language;
@property(readonly, nonatomic) unsigned int filterMarketType;
@property(readonly, nonatomic) BOOL supportBMP;
- (id)desc;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

