//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface FLCExtensionManager : NSObject
{
    NSArray *_extensionPoints;
    NSDictionary *_extensionsDic;
}

+ (id)shareInstance;
- (void).cxx_destruct;
- (id)versionForExtensionPointName:(id)arg1;
- (id)extensionInstancesForPointName:(id)arg1;
- (id)extensionsForPointName:(id)arg1;
- (id)init;

@end

