//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface FLCloudClientItem : NSObject
{
    unsigned short _key;
    unsigned long long _itemID;
    unsigned long long _updateTime;
    NSData *_data;
}

@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) unsigned long long updateTime; // @synthesize updateTime=_updateTime;
@property(nonatomic) unsigned long long itemID; // @synthesize itemID=_itemID;
@property(nonatomic) unsigned short key; // @synthesize key=_key;
- (void).cxx_destruct;

@end

