//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLCNFinanceIncomeModel : FTCodingModel
{
    NSString *_infoSource;
    NSString *_operatingRevenue;
    NSString *_operatingRevenueGR;
    NSString *_operatingProfit;
    NSString *_OperatingProfitGR;
    NSString *_netProfit;
    NSString *_netProfitGR;
}

@property(copy, nonatomic) NSString *netProfitGR; // @synthesize netProfitGR=_netProfitGR;
@property(copy, nonatomic) NSString *netProfit; // @synthesize netProfit=_netProfit;
@property(copy, nonatomic) NSString *OperatingProfitGR; // @synthesize OperatingProfitGR=_OperatingProfitGR;
@property(copy, nonatomic) NSString *operatingProfit; // @synthesize operatingProfit=_operatingProfit;
@property(copy, nonatomic) NSString *operatingRevenueGR; // @synthesize operatingRevenueGR=_operatingRevenueGR;
@property(copy, nonatomic) NSString *operatingRevenue; // @synthesize operatingRevenue=_operatingRevenue;
@property(copy, nonatomic) NSString *infoSource; // @synthesize infoSource=_infoSource;
- (void).cxx_destruct;

@end

