//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLCNFinanceBalanceModel : FTCodingModel
{
    NSString *_infoSource;
    NSString *_totalAssets;
    NSString *_totalLiability;
    NSString *_totalShareholderEuiqty;
}

@property(copy, nonatomic) NSString *totalShareholderEuiqty; // @synthesize totalShareholderEuiqty=_totalShareholderEuiqty;
@property(copy, nonatomic) NSString *totalLiability; // @synthesize totalLiability=_totalLiability;
@property(copy, nonatomic) NSString *totalAssets; // @synthesize totalAssets=_totalAssets;
@property(copy, nonatomic) NSString *infoSource; // @synthesize infoSource=_infoSource;
- (void).cxx_destruct;

@end

