//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLTCPCommand-Protocol.h>

@class NSString;

@interface FLCommand : NSObject <FLTCPCommand>
{
    BOOL _requireSecurityToken;
    unsigned char _marketType;
    unsigned char _dataType;
    unsigned short _command;
    unsigned int _serialNumber;
    unsigned int _timeOutInterval;
    unsigned int _timeOutTime;
    double _sendTime;
    CDUnknownBlockType _responseBlock;
}

@property(copy, nonatomic) CDUnknownBlockType responseBlock; // @synthesize responseBlock=_responseBlock;
@property(nonatomic) double sendTime; // @synthesize sendTime=_sendTime;
@property(nonatomic) unsigned char dataType; // @synthesize dataType=_dataType;
@property(nonatomic) unsigned char marketType; // @synthesize marketType=_marketType;
@property(nonatomic) unsigned int timeOutTime; // @synthesize timeOutTime=_timeOutTime;
@property(nonatomic) unsigned int timeOutInterval; // @synthesize timeOutInterval=_timeOutInterval;
@property(nonatomic) BOOL requireSecurityToken; // @synthesize requireSecurityToken=_requireSecurityToken;
@property(nonatomic) unsigned int serialNumber; // @synthesize serialNumber=_serialNumber;
@property(nonatomic) unsigned short command; // @synthesize command=_command;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

