//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLCompanyBuyBackModel : FTCodingModel
{
    NSString *_date;
    NSString *_totalAmount;
    NSString *_percent;
}

@property(copy, nonatomic) NSString *percent; // @synthesize percent=_percent;
@property(copy, nonatomic) NSString *totalAmount; // @synthesize totalAmount=_totalAmount;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
- (void).cxx_destruct;

@end

