//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLCompanySplitModel : FTCodingModel
{
    NSString *_date;
    NSString *_tempCode;
    NSString *_programDesc;
    NSString *_reformType;
}

@property(copy, nonatomic) NSString *reformType; // @synthesize reformType=_reformType;
@property(copy, nonatomic) NSString *programDesc; // @synthesize programDesc=_programDesc;
@property(copy, nonatomic) NSString *tempCode; // @synthesize tempCode=_tempCode;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
- (void).cxx_destruct;

@end

