//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLCompanySharesModel : FTCodingModel
{
    NSString *_sharesCount;
    NSString *_outstandingShares;
    NSString *_notHKShares;
    NSString *_holders;
    NSString *_avgHoldShares;
}

@property(copy, nonatomic) NSString *avgHoldShares; // @synthesize avgHoldShares=_avgHoldShares;
@property(copy, nonatomic) NSString *holders; // @synthesize holders=_holders;
@property(copy, nonatomic) NSString *notHKShares; // @synthesize notHKShares=_notHKShares;
@property(copy, nonatomic) NSString *outstandingShares; // @synthesize outstandingShares=_outstandingShares;
@property(copy, nonatomic) NSString *sharesCount; // @synthesize sharesCount=_sharesCount;
- (void).cxx_destruct;

@end

