//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLCompanyDividendModel : FTCodingModel
{
    NSString *_statement;
    NSString *_exDate;
    NSString *_payDate;
}

@property(copy, nonatomic) NSString *payDate; // @synthesize payDate=_payDate;
@property(copy, nonatomic) NSString *exDate; // @synthesize exDate=_exDate;
@property(copy, nonatomic) NSString *statement; // @synthesize statement=_statement;
- (void).cxx_destruct;

@end

