//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLShortConnectionTask.h>

@class NSMutableData, NSString;

@interface FLConfigFileDownloadTask : FLShortConnectionTask
{
    unsigned int _fileBeginPosition;
    unsigned int _filePieceLength;
    NSMutableData *_fileData;
    NSString *_newFileStamp;
    unsigned short _fileID;
}

@property(nonatomic) unsigned short fileID; // @synthesize fileID=_fileID;
- (void).cxx_destruct;
- (void)decodePacket:(struct util_byteios_net *)arg1;
- (void)decodePacker:(struct ft_packer *)arg1;
- (void)startSending;
- (id)init;

@end

