//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLDBHelper : NSObject
{
}

+ (void)removeOldDBFilesLowerThanVersion:(int)arg1 currentDBFileFullPath:(id)arg2 sourceDBName:(id)arg3;
+ (void)initDBFile:(id)arg1 currentVersion:(int)arg2 sourceDBName:(id)arg3;

@end

