//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/NSObject-Protocol.h>

@class NSObject;
@protocol OS_dispatch_queue;

@protocol FLDBDelegate <NSObject>
- (void)asyncDoDBOperation:(void (^)(FMDatabase *))arg1 callBackBlock:(void (^)(void))arg2 callBackQueue:(NSObject<OS_dispatch_queue> *)arg3 useTransaction:(BOOL)arg4 useDeferred:(BOOL)arg5;
- (void)syncDoDBOperation:(void (^)(FMDatabase *))arg1 useTransaction:(BOOL)arg2 useDeferred:(BOOL)arg3;
@end

