//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, NSString;
@protocol OS_dispatch_queue;

@interface FLDBObject : NSObject
{
    NSObject<OS_dispatch_queue> *_taskQueue;
    NSString *_dbPath;
    FMDatabaseQueue *_dbQueue;
}

@property(retain, nonatomic) FMDatabaseQueue *dbQueue; // @synthesize dbQueue=_dbQueue;
- (void).cxx_destruct;
- (void)syncExecuteInDB:(CDUnknownBlockType)arg1 useTransaction:(BOOL)arg2 useDeferred:(BOOL)arg3;
- (void)asyncExecuteInDB:(CDUnknownBlockType)arg1 callBackBlock:(CDUnknownBlockType)arg2 callBackQueue:(id)arg3 useTransaction:(BOOL)arg4 useDeferred:(BOOL)arg5;
- (void)initDatabase;
- (void)closeDatabase;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

