//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLDBDelegate-Protocol.h>

@class FLDBObject, NSString;

@interface FLDBBaseMgr : NSObject <FLDBDelegate>
{
    FLDBObject *_dbObject;
    int _currentDBVersion;
    NSString *_sourceDBName;
    NSString *_dbName;
}

@property(nonatomic) int currentDBVersion; // @synthesize currentDBVersion=_currentDBVersion;
@property(retain, nonatomic) NSString *dbName; // @synthesize dbName=_dbName;
@property(retain, nonatomic) NSString *sourceDBName; // @synthesize sourceDBName=_sourceDBName;
- (void).cxx_destruct;
- (void)asyncDoDBOperation:(CDUnknownBlockType)arg1 callBackBlock:(CDUnknownBlockType)arg2 callBackQueue:(id)arg3 useTransaction:(BOOL)arg4 useDeferred:(BOOL)arg5;
- (void)syncDoDBOperation:(CDUnknownBlockType)arg1 useTransaction:(BOOL)arg2 useDeferred:(BOOL)arg3;
- (void)destroyDB;
- (void)initDB;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

