//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CocoaLumberjack/DDLogFileManagerDefault.h>

@class NSMutableData;

@interface FLDDLogFileManager : DDLogFileManagerDefault
{
    NSMutableData *_uploadLogData;
}

- (void).cxx_destruct;
- (id)extraContentData;
- (void)didRollAndArchiveLogFile:(id)arg1;
- (void)didArchiveLogFile:(id)arg1;
- (void)removeExtractLogTempFile;
- (id)getExtractLogTempCompressedLogFile;
- (id)getExtractLogTempLogFile;
- (void)generateCompressedFileWithData:(id)arg1;
- (id)getDateFromString:(id)arg1;
- (void)serverPushForSettingLogLevel:(int)arg1 classes:(id)arg2;
- (void)doUploadLogFile;
- (BOOL)extractLogWith:(double)arg1 endTime:(double)arg2 fromLog:(id)arg3;
- (void)uploadLogByBeginTimeStamp:(double)arg1 endTimeStamp:(double)arg2 keyWord:(id)arg3 clientVersion:(id)arg4;
- (void)uploadLogWithDescription:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;

@end

