//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@interface FLDeviceLockModel : FTCodingModel <NSCopying>
{
    int _deviceLocked;
    unsigned long long _userId;
}

@property(nonatomic) int deviceLocked; // @synthesize deviceLocked=_deviceLocked;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

