//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLDeviceInfoModel : FTCodingModel <NSCopying>
{
    unsigned long long _userId;
    NSString *_deviceId;
    NSString *_deviceType;
    NSString *_deviceAlias;
}

@property(retain, nonatomic) NSString *deviceAlias; // @synthesize deviceAlias=_deviceAlias;
@property(retain, nonatomic) NSString *deviceType; // @synthesize deviceType=_deviceType;
@property(retain, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

