//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@interface FLEmailAndSMSSubscribeManager : FLBaseManager
{
}

- (id)subscribeChannelModelWithPbModel:(struct ChannelName *)arg1;
- (id)subscribeItemWithPbModel:(struct SubsItem *)arg1;
- (BOOL)updateUserSubscribeInfoWithUserId:(unsigned long long)arg1 subsItems:(id)arg2 apiKey:(id)arg3 response:(CDUnknownBlockType)arg4;
- (BOOL)fetchUserSubscribeInfoWithUserId:(unsigned long long)arg1 subsItems:(id)arg2 apiKey:(id)arg3 response:(CDUnknownBlockType)arg4;

@end

