//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSTimer;

@interface FLF3CNNWrapper : NSObject
{
    BOOL _pingAnEnv;
    NSMutableDictionary *_handlerInfoDictionary;
    NSMutableDictionary *_notificationInfoDictionary;
    NSTimer *_refreshTimer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSTimer *refreshTimer; // @synthesize refreshTimer=_refreshTimer;
@property(retain, nonatomic) NSMutableDictionary *notificationInfoDictionary; // @synthesize notificationInfoDictionary=_notificationInfoDictionary;
@property(retain, nonatomic) NSMutableDictionary *handlerInfoDictionary; // @synthesize handlerInfoDictionary=_handlerInfoDictionary;
@property(nonatomic) BOOL pingAnEnv; // @synthesize pingAnEnv=_pingAnEnv;
- (void).cxx_destruct;
- (void)convertSubAccount:(id)arg1 toF3CAccountItem:(struct Ndt_Trd_AccItem *)arg2;
- (id)getDiskSerialNumber;
- (id)getIPAddress;
- (void)setupAppInfo;
- (void)notifyWithNotificationInfo:(id)arg1;
- (void)performResultBlockForRequestKey:(unsigned long long)arg1 notificationInfo:(id)arg2;
- (void)addRequestHandleWithRequestKey:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)setTradeAccountList:(id)arg1 forUserId:(unsigned long long)arg2;
- (void)setHttpSender:(struct FLHTTPSender *)arg1 senderId:(long long)arg2;
- (void)setTcpSender:(struct FLTCPProtoSender *)arg1 senderId:(long long)arg2;
- (void)unInit;
- (void)updateServerTimeStamp;
- (void)clear;
- (void)setup;
- (void)dealloc;
- (id)init;

@end

