//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface FLFaceUtil : NSObject
{
    NSDictionary *_faceMap;
    NSDictionary *_staticFaceMap;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSDictionary *staticFaceMap; // @synthesize staticFaceMap=_staticFaceMap;
@property(retain, nonatomic) NSDictionary *faceMap; // @synthesize faceMap=_faceMap;
- (void).cxx_destruct;
- (void)languageChanged:(id)arg1;

@end

