//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLFilterField : FTCodingModel <NSCopying>
{
    unsigned long long _fieldType;
    NSString *_stringValue;
}

@property(copy, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
@property(readonly, nonatomic) unsigned long long fieldType; // @synthesize fieldType=_fieldType;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL valid;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;
- (id)initWithFieldType:(unsigned long long)arg1 stringValue:(id)arg2;
@property(readonly, nonatomic) unsigned long long uint64Value;
@property(readonly, nonatomic) long long int64Value;
@property(readonly, nonatomic) unsigned int uint32Value;
@property(readonly, nonatomic) int int32Value;
@property(readonly, nonatomic) unsigned short uint16Value;
@property(readonly, nonatomic) short int16Value;
@property(readonly, nonatomic) unsigned char uint8Value;
@property(readonly, nonatomic) BOOL int8Value;
@property(readonly, nonatomic) double doubleValue;
@property(readonly, nonatomic) float floatValue;

@end

