//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLFilterField, NSString;

@interface FLFilterPairField : FTCodingModel <NSCopying>
{
    unsigned char _scaleFactor;
    unsigned long long _fieldType;
    FLFilterField *_min;
    FLFilterField *_max;
    double _realFactor;
}

+ (id)pairFieldWithDictionary:(id)arg1;
+ (id)pairFieldWithFieldType:(unsigned long long)arg1 scale:(unsigned char)arg2 minStringValue:(id)arg3 maxStringValue:(id)arg4;
@property(nonatomic) double realFactor; // @synthesize realFactor=_realFactor;
@property(readonly, nonatomic) FLFilterField *max; // @synthesize max=_max;
@property(readonly, nonatomic) FLFilterField *min; // @synthesize min=_min;
@property(nonatomic) unsigned char scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(readonly, nonatomic) unsigned long long fieldType; // @synthesize fieldType=_fieldType;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL valid;
@property(readonly, nonatomic) BOOL maxValid;
@property(readonly, nonatomic) BOOL minValid;
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;
- (id)initWithFieldType:(unsigned long long)arg1 scale:(unsigned char)arg2;
- (id)initWithFieldType:(unsigned long long)arg1 scale:(unsigned char)arg2 minStringValue:(id)arg3 maxStringValue:(id)arg4;
@property(copy, nonatomic) NSString *maxStringValue;
@property(copy, nonatomic) NSString *minStringValue;
@property(nonatomic) unsigned long long uint64MaxValue;
@property(nonatomic) long long int64MaxValue;
@property(nonatomic) unsigned int uint32MaxValue;
@property(nonatomic) int int32MaxValue;
@property(nonatomic) unsigned long long uint64MinValue;
@property(nonatomic) long long int64MinValue;
@property(nonatomic) unsigned int uint32MinValue;
@property(nonatomic) int int32MinValue;

@end

