//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLStockObject.h>

#import <FTEngine/FLBMPModelProtocol-Protocol.h>

@class FLStock, NSString;

@interface FLFilterModel : FLStockObject <FLBMPModelProtocol>
{
    FLStock *_stock;
}

@property(retain, nonatomic) FLStock *stock; // @synthesize stock=_stock;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long ID;
@property(readonly, nonatomic) unsigned char marketID;
@property(readonly, nonatomic) unsigned long long stockMarketType;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *code;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

