//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLForecastRangeItem : NSObject
{
    unsigned int _priceFrom;
    unsigned int _priceTo;
    unsigned int _prob;
}

@property(nonatomic) unsigned int prob; // @synthesize prob=_prob;
@property(nonatomic) unsigned int priceTo; // @synthesize priceTo=_priceTo;
@property(nonatomic) unsigned int priceFrom; // @synthesize priceFrom=_priceFrom;
- (id)initWithPriceFrom:(unsigned int)arg1 priceTo:(unsigned int)arg2 prob:(unsigned int)arg3;
- (id)debugDescription;

@end

