//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FLBaseHandler, NSError;

@protocol FLHandlerStatusDelegate
- (void)handler:(FLBaseHandler *)arg1 didChangedConnectionStatus:(int)arg2 error:(NSError *)arg3;
@end

