//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FLHandicapData : NSObject
{
    NSArray *_buyArray;
    NSArray *_askArray;
}

@property(retain, nonatomic) NSArray *askArray; // @synthesize askArray=_askArray;
@property(retain, nonatomic) NSArray *buyArray; // @synthesize buyArray=_buyArray;
- (void).cxx_destruct;

@end

