//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLHKCNLinkageLimitData : NSObject
{
    unsigned int _sh_sh_hk_total_limit;
    unsigned int _sh_sh_hk_day_limit;
    unsigned int _sh_sh_hk_total_remaining;
    unsigned int _sh_sh_hk_day_remaining;
    unsigned int _sh_sh_hk_update_time;
    unsigned int _hk_sh_hk_total_limit;
    unsigned int _hk_sh_hk_day_limit;
    unsigned int _hk_sh_hk_total_remaining;
    unsigned int _hk_sh_hk_day_remaining;
    unsigned int _hk_sh_hk_update_time;
    unsigned int _sz_sz_hk_total_limit;
    unsigned int _sz_sz_hk_day_limit;
    unsigned int _sz_sz_hk_total_remaining;
    unsigned int _sz_sz_hk_day_remaining;
    unsigned int _sz_sz_hk_update_time;
    unsigned int _hk_sz_hk_total_limit;
    unsigned int _hk_sz_hk_day_limit;
    unsigned int _hk_sz_hk_total_remaining;
    unsigned int _hk_sz_hk_day_remaining;
    unsigned int _hk_sz_hk_update_time;
}

@property(nonatomic) unsigned int hk_sz_hk_update_time; // @synthesize hk_sz_hk_update_time=_hk_sz_hk_update_time;
@property(nonatomic) unsigned int hk_sz_hk_day_remaining; // @synthesize hk_sz_hk_day_remaining=_hk_sz_hk_day_remaining;
@property(nonatomic) unsigned int hk_sz_hk_total_remaining; // @synthesize hk_sz_hk_total_remaining=_hk_sz_hk_total_remaining;
@property(nonatomic) unsigned int hk_sz_hk_day_limit; // @synthesize hk_sz_hk_day_limit=_hk_sz_hk_day_limit;
@property(nonatomic) unsigned int hk_sz_hk_total_limit; // @synthesize hk_sz_hk_total_limit=_hk_sz_hk_total_limit;
@property(nonatomic) unsigned int sz_sz_hk_update_time; // @synthesize sz_sz_hk_update_time=_sz_sz_hk_update_time;
@property(nonatomic) unsigned int sz_sz_hk_day_remaining; // @synthesize sz_sz_hk_day_remaining=_sz_sz_hk_day_remaining;
@property(nonatomic) unsigned int sz_sz_hk_total_remaining; // @synthesize sz_sz_hk_total_remaining=_sz_sz_hk_total_remaining;
@property(nonatomic) unsigned int sz_sz_hk_day_limit; // @synthesize sz_sz_hk_day_limit=_sz_sz_hk_day_limit;
@property(nonatomic) unsigned int sz_sz_hk_total_limit; // @synthesize sz_sz_hk_total_limit=_sz_sz_hk_total_limit;
@property(nonatomic) unsigned int hk_sh_hk_update_time; // @synthesize hk_sh_hk_update_time=_hk_sh_hk_update_time;
@property(nonatomic) unsigned int hk_sh_hk_day_remaining; // @synthesize hk_sh_hk_day_remaining=_hk_sh_hk_day_remaining;
@property(nonatomic) unsigned int hk_sh_hk_total_remaining; // @synthesize hk_sh_hk_total_remaining=_hk_sh_hk_total_remaining;
@property(nonatomic) unsigned int hk_sh_hk_day_limit; // @synthesize hk_sh_hk_day_limit=_hk_sh_hk_day_limit;
@property(nonatomic) unsigned int hk_sh_hk_total_limit; // @synthesize hk_sh_hk_total_limit=_hk_sh_hk_total_limit;
@property(nonatomic) unsigned int sh_sh_hk_update_time; // @synthesize sh_sh_hk_update_time=_sh_sh_hk_update_time;
@property(nonatomic) unsigned int sh_sh_hk_day_remaining; // @synthesize sh_sh_hk_day_remaining=_sh_sh_hk_day_remaining;
@property(nonatomic) unsigned int sh_sh_hk_total_remaining; // @synthesize sh_sh_hk_total_remaining=_sh_sh_hk_total_remaining;
@property(nonatomic) unsigned int sh_sh_hk_day_limit; // @synthesize sh_sh_hk_day_limit=_sh_sh_hk_day_limit;
@property(nonatomic) unsigned int sh_sh_hk_total_limit; // @synthesize sh_sh_hk_total_limit=_sh_sh_hk_total_limit;

@end

