//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLHKFinanceIncomeModel.h>

@class NSString;

@interface FLHKFinanceIncomeModel_Fin : FLHKFinanceIncomeModel
{
    NSString *_operatingRevenue;
    NSString *_operatingExpense;
    NSString *_earningBeforeTax;
    NSString *_profitToShareholders;
    NSString *_EPSBasic;
}

@property(copy, nonatomic) NSString *EPSBasic; // @synthesize EPSBasic=_EPSBasic;
@property(copy, nonatomic) NSString *profitToShareholders; // @synthesize profitToShareholders=_profitToShareholders;
@property(copy, nonatomic) NSString *earningBeforeTax; // @synthesize earningBeforeTax=_earningBeforeTax;
@property(copy, nonatomic) NSString *operatingExpense; // @synthesize operatingExpense=_operatingExpense;
@property(copy, nonatomic) NSString *operatingRevenue; // @synthesize operatingRevenue=_operatingRevenue;
- (void).cxx_destruct;

@end

