//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLHKFinanceIncomeModel.h>

@class NSString;

@interface FLHKFinanceIncomeModel_NoFin : FLHKFinanceIncomeModel
{
    NSString *_operatingIncome;
    NSString *_grossIncome;
    NSString *_operateProfit;
    NSString *_earningBeforeTax;
    NSString *_profitToShareholders;
    NSString *_EPSBasic;
}

@property(copy, nonatomic) NSString *EPSBasic; // @synthesize EPSBasic=_EPSBasic;
@property(copy, nonatomic) NSString *profitToShareholders; // @synthesize profitToShareholders=_profitToShareholders;
@property(copy, nonatomic) NSString *earningBeforeTax; // @synthesize earningBeforeTax=_earningBeforeTax;
@property(copy, nonatomic) NSString *operateProfit; // @synthesize operateProfit=_operateProfit;
@property(copy, nonatomic) NSString *grossIncome; // @synthesize grossIncome=_grossIncome;
@property(copy, nonatomic) NSString *operatingIncome; // @synthesize operatingIncome=_operatingIncome;
- (void).cxx_destruct;

@end

