//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLUserQuoteData.h>

@class NSDate, NSString;

@interface FLHKUserQuoteData : FLUserQuoteData
{
    BOOL _hasClickPricePermission;
    unsigned int _futureFlag;
    unsigned int _refreshPriceLastClickTime;
    unsigned int _refreshPriceTotalClickCount;
    int _refreshPriceLeftClickCount;
    long long _permission;
    NSString *_cardNumber;
    NSDate *_cardStartDate;
    NSDate *_cardEndDate;
}

@property(nonatomic) int refreshPriceLeftClickCount; // @synthesize refreshPriceLeftClickCount=_refreshPriceLeftClickCount;
@property(nonatomic) unsigned int refreshPriceTotalClickCount; // @synthesize refreshPriceTotalClickCount=_refreshPriceTotalClickCount;
@property(nonatomic) unsigned int refreshPriceLastClickTime; // @synthesize refreshPriceLastClickTime=_refreshPriceLastClickTime;
@property(retain, nonatomic) NSDate *cardEndDate; // @synthesize cardEndDate=_cardEndDate;
@property(retain, nonatomic) NSDate *cardStartDate; // @synthesize cardStartDate=_cardStartDate;
@property(retain, nonatomic) NSString *cardNumber; // @synthesize cardNumber=_cardNumber;
@property(nonatomic) unsigned int futureFlag; // @synthesize futureFlag=_futureFlag;
@property(nonatomic) BOOL hasClickPricePermission; // @synthesize hasClickPricePermission=_hasClickPricePermission;
- (void).cxx_destruct;
- (id)description;
- (int)userQuoteDisplayState;
@property(nonatomic) long long permission; // @synthesize permission=_permission;
- (id)initWithMarketType:(unsigned long long)arg1;

@end

