//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLHKFinanceBalanceModel.h>

@class NSString;

@interface FLHKFinanceBalanceModel_NoFin : FLHKFinanceBalanceModel
{
    NSString *_totalCurrentAssets;
    NSString *_totalCurrentLiability;
    NSString *_totalAssets;
    NSString *_totalLiability;
    NSString *_totalInterests;
}

@property(copy, nonatomic) NSString *totalInterests; // @synthesize totalInterests=_totalInterests;
@property(copy, nonatomic) NSString *totalLiability; // @synthesize totalLiability=_totalLiability;
@property(copy, nonatomic) NSString *totalAssets; // @synthesize totalAssets=_totalAssets;
@property(copy, nonatomic) NSString *totalCurrentLiability; // @synthesize totalCurrentLiability=_totalCurrentLiability;
@property(copy, nonatomic) NSString *totalCurrentAssets; // @synthesize totalCurrentAssets=_totalCurrentAssets;
- (void).cxx_destruct;

@end

