//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLHKFinanceCashFlowModel : FTCodingModel
{
    NSString *_infoSource;
    NSString *_netCashFromOperating;
    NSString *_netCashFlowFromInvActivities;
    NSString *_netCashFromFinance;
    NSString *_currentUnit;
}

@property(copy, nonatomic) NSString *currentUnit; // @synthesize currentUnit=_currentUnit;
@property(copy, nonatomic) NSString *netCashFromFinance; // @synthesize netCashFromFinance=_netCashFromFinance;
@property(copy, nonatomic) NSString *netCashFlowFromInvActivities; // @synthesize netCashFlowFromInvActivities=_netCashFlowFromInvActivities;
@property(copy, nonatomic) NSString *netCashFromOperating; // @synthesize netCashFromOperating=_netCashFromOperating;
@property(copy, nonatomic) NSString *infoSource; // @synthesize infoSource=_infoSource;
- (void).cxx_destruct;

@end

