//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLHSubAccount.h>

@interface FLHSimulationSubAccount : FLHSubAccount
{
    double _cashFactor;
    double _positionFactor;
    long long _todayBuy;
    long long _todaySell;
    long long _todayWithdraw;
}

@property(nonatomic) long long todayWithdraw; // @synthesize todayWithdraw=_todayWithdraw;
@property(nonatomic) long long todaySell; // @synthesize todaySell=_todaySell;
@property(nonatomic) long long todayBuy; // @synthesize todayBuy=_todayBuy;
@property(nonatomic) double positionFactor; // @synthesize positionFactor=_positionFactor;
@property(nonatomic) double cashFactor; // @synthesize cashFactor=_cashFactor;
- (void)recaculateValue;
- (void)dealloc;
- (void)onProfitChange:(id)arg1;
- (id)init;

@end

