//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLSubAccount.h>

@interface FLHSubAccount : FLSubAccount
{
    BOOL _loanAllowed;
    int _marginRatioStatus;
    long long _marginValue;
    long long _loanUsed;
    double _marginRatio;
    double _marginWarnRatio;
    double _marginCoverRatio;
    long long _marginCallAmount;
}

@property(nonatomic) int marginRatioStatus; // @synthesize marginRatioStatus=_marginRatioStatus;
@property(nonatomic) long long marginCallAmount; // @synthesize marginCallAmount=_marginCallAmount;
@property(nonatomic) double marginCoverRatio; // @synthesize marginCoverRatio=_marginCoverRatio;
@property(nonatomic) double marginWarnRatio; // @synthesize marginWarnRatio=_marginWarnRatio;
@property(nonatomic) double marginRatio; // @synthesize marginRatio=_marginRatio;
@property(nonatomic) BOOL loanAllowed; // @synthesize loanAllowed=_loanAllowed;
@property(nonatomic) long long loanUsed; // @synthesize loanUsed=_loanUsed;
@property(nonatomic) long long marginValue; // @synthesize marginValue=_marginValue;

@end

