//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AFNetworking/AFHTTPRequestOperationManager.h>

@class FLWebAPIClient;

@interface FLInformationNetRequest : AFHTTPRequestOperationManager
{
    FLWebAPIClient *_webClient;
}

@property(retain, nonatomic) FLWebAPIClient *webClient; // @synthesize webClient=_webClient;
- (void).cxx_destruct;
- (void)netReqInformationBarItemListWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)initWithBaseURL:(id)arg1;

@end

