//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>

@class NSArray, NSMutableDictionary, NSString;

@interface FLInfoSectionUnits : NSObject <NSCoding>
{
    NSMutableDictionary *_modelDic;
    unsigned long long _category;
}

@property(readonly, nonatomic) unsigned long long category; // @synthesize category=_category;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (void)cleanUnits;
@property(readonly, nonatomic) NSArray *allModels;
@property(readonly, nonatomic) unsigned long long counts;
- (id)sectionModelForKey:(id)arg1;
@property(readonly, nonatomic) NSString *categoryText;
@property(readonly, nonatomic) NSString *categoryName;
- (void)addSectionModel:(id)arg1;
- (id)initWithSectionCategory:(unsigned long long)arg1;

@end

