//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLInformationNetRequest, NSArray;

@interface FLInformationService : NSObject
{
    FLInformationNetRequest *_informationNetRequest;
    NSArray *_resultArray;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) FLInformationNetRequest *informationNetRequest; // @synthesize informationNetRequest=_informationNetRequest;
- (void).cxx_destruct;
- (void)saveInformationBarItemListWithItemList:(id)arg1;
- (void)getInformationBarItemListWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;

@end

