//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>

@class NSMutableDictionary, NSString;

@interface FLInfoSectionModel : NSObject <NSCoding>
{
    BOOL _selected;
    NSString *_sectionId;
    unsigned long long _category;
    unsigned long long _defaultLanguage;
    NSMutableDictionary *_languageDic;
}

+ (id)modelWithSectionId:(id)arg1 sectionName:(id)arg2 sectionDesc:(id)arg3 category:(unsigned long long)arg4;
+ (id)nameForCategory:(unsigned long long)arg1;
+ (id)textForCategory:(unsigned long long)arg1;
@property(retain) NSMutableDictionary *languageDic; // @synthesize languageDic=_languageDic;
@property(nonatomic) unsigned long long defaultLanguage; // @synthesize defaultLanguage=_defaultLanguage;
@property(readonly, nonatomic) unsigned long long category; // @synthesize category=_category;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
@property(readonly, nonatomic) NSString *sectionId; // @synthesize sectionId=_sectionId;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
@property(readonly, nonatomic) NSString *sectionDesc;
@property(readonly, nonatomic) NSString *sectionName;
- (void)updateSectionName:(id)arg1 sectionDesc:(id)arg2 forLanguage:(unsigned long long)arg3;
- (id)sectionDescWithLanguage:(unsigned long long)arg1;
- (id)sectionNameWithLanguage:(unsigned long long)arg1;
- (id)init;
- (id)initWithSectionId:(id)arg1 sectionName:(id)arg2 sectionDesc:(id)arg3 category:(unsigned long long)arg4;

@end

