//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>
#import <FTEngine/NSCopying-Protocol.h>

@class NSArray, NSString;

@interface FLIssuer : NSObject <NSCoding, NSCopying>
{
    int _ID;
    NSString *_enFullName;
    NSString *_scFullName;
    NSString *_tcFullName;
    NSString *_fullName;
    NSString *_enShortName;
    NSString *_scShortName;
    NSString *_tcShortName;
    NSString *_shortName;
    NSArray *_brokers;
}

+ (id)matchedIssuersWithName:(id)arg1;
+ (id)matchedIssuersWithPattern:(id)arg1;
@property(retain, nonatomic) NSArray *brokers; // @synthesize brokers=_brokers;
@property(retain, nonatomic) NSString *shortName; // @synthesize shortName=_shortName;
@property(retain, nonatomic) NSString *tcShortName; // @synthesize tcShortName=_tcShortName;
@property(retain, nonatomic) NSString *scShortName; // @synthesize scShortName=_scShortName;
@property(retain, nonatomic) NSString *enShortName; // @synthesize enShortName=_enShortName;
@property(retain, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(retain, nonatomic) NSString *tcFullName; // @synthesize tcFullName=_tcFullName;
@property(retain, nonatomic) NSString *scFullName; // @synthesize scFullName=_scFullName;
@property(retain, nonatomic) NSString *enFullName; // @synthesize enFullName=_enFullName;
@property(nonatomic) int ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

