//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface FLIssuersManager : NSObject
{
    NSDictionary *_idIssuers;
    NSArray *_issuers;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)saveIssuersToLocal:(id)arg1;
- (id)localCachePath;
- (void)setAndSaveIssuers:(id)arg1;
- (void)initDataFromLocalPath:(id)arg1;
- (void)initIdIssuersWithIssuers:(id)arg1;
@property(readonly, nonatomic) NSDictionary *idIssuers;
@property(retain, nonatomic) NSArray *issuers;

@end

