//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLLiveRequestModel : NSObject
{
    unsigned int _maxCount;
    unsigned long long _userId;
    unsigned long long _beginTime;
    unsigned long long _endTime;
}

+ (id)requestWithUserId:(unsigned long long)arg1 passedDays:(unsigned long long)arg2 maxCount:(unsigned int)arg3;
+ (id)requestWithUserId:(unsigned long long)arg1 passedHours:(unsigned long long)arg2 maxCount:(unsigned int)arg3;
+ (id)requestWithUserId:(unsigned long long)arg1 passedMinutes:(unsigned long long)arg2 maxCount:(unsigned int)arg3;
+ (id)requestWithUserId:(unsigned long long)arg1 passedSeconds:(unsigned long long)arg2 maxCount:(unsigned int)arg3;
+ (id)requestWithUserId:(unsigned long long)arg1 from:(unsigned long long)arg2 to:(unsigned long long)arg3 maxCount:(unsigned int)arg4;
@property(nonatomic) unsigned int maxCount; // @synthesize maxCount=_maxCount;
@property(nonatomic) unsigned long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) unsigned long long beginTime; // @synthesize beginTime=_beginTime;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (id)init;
- (id)initWithUserId:(unsigned long long)arg1 from:(unsigned long long)arg2 to:(unsigned long long)arg3 maxCount:(unsigned int)arg4;

@end

