//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLStockObject.h>

@class FLLinkageStockItem;

@interface FLLinkageItem : FLStockObject
{
    float _premium;
    FLLinkageStockItem *_stockMain;
    FLLinkageStockItem *_stockLink;
}

@property(nonatomic) float premium; // @synthesize premium=_premium;
@property(retain, nonatomic) FLLinkageStockItem *stockLink; // @synthesize stockLink=_stockLink;
@property(retain, nonatomic) FLLinkageStockItem *stockMain; // @synthesize stockMain=_stockMain;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)ID;

@end

