//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FLLoginConnectionStrategy : NSObject
{
    long long _retryBackupIndex;
    NSArray *_backupIPAddresses;
}

@property(retain, nonatomic) NSArray *backupIPAddresses; // @synthesize backupIPAddresses=_backupIPAddresses;
@property(nonatomic) long long retryBackupIndex; // @synthesize retryBackupIndex=_retryBackupIndex;
- (void).cxx_destruct;
- (void)fetchAndSaveBackupIpAddresses;
- (id)nextTryURLForClient:(id)arg1;
- (void)dealloc;
- (id)init;

@end

