//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseAPIClient.h>

@class FLLoginConnectionStrategy, NSString;

@interface FLLoginClient : FLBaseAPIClient
{
    NSString *_nextTryURL;
    FLLoginConnectionStrategy *_strategy;
}

@property(retain, nonatomic) FLLoginConnectionStrategy *strategy; // @synthesize strategy=_strategy;
- (void).cxx_destruct;
- (id)receiveErrorResponseMessage:(id)arg1;
- (void)registBySMSWithPassword:(id)arg1 phoneNumber:(id)arg2 areaCode:(id)arg3 salt:(id)arg4 regSig:(id)arg5 codeSig:(id)arg6 resultBlock:(CDUnknownBlockType)arg7;
- (void)verifySMSCode:(id)arg1 phoneNumber:(id)arg2 areaCode:(id)arg3 codeSig:(id)arg4 resultBlock:(CDUnknownBlockType)arg5;
- (void)sendSMSCodeWithPhoneNumber:(id)arg1 areaCode:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)thirdFastRegisterNewUserInfo:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)authenticateOpenId:(id)arg1 accessToken:(id)arg2 wechatUnionID:(id)arg3 twitterTokenSecret:(id)arg4 tokenType:(id)arg5 resultBlock:(CDUnknownBlockType)arg6;
- (void)verifyDeviceSMSCode:(id)arg1 deviceVerifySig:(id)arg2 deviceCodeSig:(id)arg3 userId:(unsigned long long)arg4 resultBlock:(CDUnknownBlockType)arg5;
- (void)fetchDeviceSMSCodeWithUserId:(unsigned long long)arg1 deviceVerifySig:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)fetchAuthoritySaltWithAccount:(id)arg1 areaCode:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)fetchVerifyCodeWithUid:(unsigned long long)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)authenticatePasswordWithUid:(unsigned long long)arg1 tgtgt:(id)arg2 verifyCodeKey:(id)arg3 verifyCode:(id)arg4 deviceSig:(id)arg5 resultBlock:(CDUnknownBlockType)arg6;
- (void)authenticateAccount:(id)arg1 areaCode:(id)arg2 password:(id)arg3 resultBlock:(CDUnknownBlockType)arg4;
- (void)authenticateAccount:(id)arg1 password:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (id)defaultParameters;
- (id)initWithBaseURL:(id)arg1;

@end

