//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLMaxTransaction : NSObject
{
    unsigned long long _maxSellQuantity;
    unsigned long long _maxSellShortQuantity;
    long long _cashMaxBuyingPower;
    unsigned long long _cashMaxBuyQuantity;
    unsigned long long _marginMaxBuyQuantity;
    long long _marginMaxBuyingPower;
    unsigned long long _marginMaxBuyBackQuantity;
}

@property(nonatomic) unsigned long long marginMaxBuyBackQuantity; // @synthesize marginMaxBuyBackQuantity=_marginMaxBuyBackQuantity;
@property(nonatomic) long long marginMaxBuyingPower; // @synthesize marginMaxBuyingPower=_marginMaxBuyingPower;
@property(nonatomic) unsigned long long marginMaxBuyQuantity; // @synthesize marginMaxBuyQuantity=_marginMaxBuyQuantity;
@property(nonatomic) unsigned long long cashMaxBuyQuantity; // @synthesize cashMaxBuyQuantity=_cashMaxBuyQuantity;
@property(nonatomic) long long cashMaxBuyingPower; // @synthesize cashMaxBuyingPower=_cashMaxBuyingPower;
@property(nonatomic) unsigned long long maxSellShortQuantity; // @synthesize maxSellShortQuantity=_maxSellShortQuantity;
@property(nonatomic) unsigned long long maxSellQuantity; // @synthesize maxSellQuantity=_maxSellQuantity;
@property(readonly, nonatomic) unsigned long long maxBuyQuantityOfCashAndMargin;
- (id)description;
- (id)init;

@end

