//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface FLMajorIssuesManager : NSObject
{
    NSObject<OS_dispatch_queue> *_callbackQueue;
}

+ (id)defaultManager;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
- (void).cxx_destruct;
- (BOOL)fetchMajorIssuesWithStockID:(unsigned long long)arg1 marketID:(unsigned int)arg2 forUser:(unsigned long long)arg3 response:(CDUnknownBlockType)arg4;
- (BOOL)fetchMajorIssuesWithStockID:(unsigned long long)arg1 marketID:(unsigned int)arg2 response:(CDUnknownBlockType)arg3;
- (BOOL)fetchMajorIssuesWithStock:(id)arg1 response:(CDUnknownBlockType)arg2;

@end

