//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FLMajorIssue : NSObject
{
    unsigned int _deadline;
    NSString *_simplifiedChineseTitle;
    NSString *_traditionalChineseTitle;
    NSString *_desciptionUrl;
    NSString *_occurDate;
}

+ (id)majorIssueWithProtoModel:(const struct MatterItem *)arg1;
@property(readonly, copy, nonatomic) NSString *occurDate; // @synthesize occurDate=_occurDate;
@property(readonly, copy, nonatomic) NSString *desciptionUrl; // @synthesize desciptionUrl=_desciptionUrl;
@property(readonly, nonatomic) unsigned int deadline; // @synthesize deadline=_deadline;
@property(readonly, copy, nonatomic) NSString *traditionalChineseTitle; // @synthesize traditionalChineseTitle=_traditionalChineseTitle;
@property(readonly, copy, nonatomic) NSString *simplifiedChineseTitle; // @synthesize simplifiedChineseTitle=_simplifiedChineseTitle;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)initWithSimplifiedChinese:(id)arg1 traditionalChinese:(id)arg2 deadline:(unsigned int)arg3 desciptionUrl:(id)arg4 occurDate:(id)arg5;

@end

