//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLWatchGroup.h>

@interface FLMarketGroup : FLWatchGroup
{
    unsigned long long _marketType;
    BOOL _shouldUpdate;
}

+ (id)groupNameForStockMarket:(unsigned long long)arg1;
+ (unsigned int)groupIDForStockMarket:(unsigned long long)arg1;
@property(nonatomic) BOOL shouldUpdate; // @synthesize shouldUpdate=_shouldUpdate;
- (id)stocks;
- (unsigned long long)marketType;
- (BOOL)isMarketGroup;
- (id)initWithStockMarket:(unsigned long long)arg1;

@end

