//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLMedalModel : FTCodingModel <NSCopying>
{
    BOOL _medalEnableFlag;
    unsigned int _medalLevel;
    unsigned int _currentValue;
    unsigned int _minValueOfCurrentLevel;
    unsigned int _needValueToUpgrade;
    unsigned int _tradeVolume;
    unsigned int _needTradeVolumeToUpgrade;
    unsigned int _tradeCount;
    unsigned int _needTradeCountToUpgrade;
    unsigned int _fortuneScore;
    unsigned int _needFortuneScoreToUpgrade;
    unsigned long long _userId;
    unsigned long long _profileType;
    unsigned long long _clientProfileType;
    NSString *_medalPicUrl;
    NSString *_ruleDesc;
}

@property(retain, nonatomic) NSString *ruleDesc; // @synthesize ruleDesc=_ruleDesc;
@property(nonatomic) unsigned int needFortuneScoreToUpgrade; // @synthesize needFortuneScoreToUpgrade=_needFortuneScoreToUpgrade;
@property(nonatomic) unsigned int fortuneScore; // @synthesize fortuneScore=_fortuneScore;
@property(nonatomic) unsigned int needTradeCountToUpgrade; // @synthesize needTradeCountToUpgrade=_needTradeCountToUpgrade;
@property(nonatomic) unsigned int tradeCount; // @synthesize tradeCount=_tradeCount;
@property(nonatomic) unsigned int needTradeVolumeToUpgrade; // @synthesize needTradeVolumeToUpgrade=_needTradeVolumeToUpgrade;
@property(nonatomic) unsigned int tradeVolume; // @synthesize tradeVolume=_tradeVolume;
@property(nonatomic) unsigned int needValueToUpgrade; // @synthesize needValueToUpgrade=_needValueToUpgrade;
@property(nonatomic) unsigned int minValueOfCurrentLevel; // @synthesize minValueOfCurrentLevel=_minValueOfCurrentLevel;
@property(nonatomic) unsigned int currentValue; // @synthesize currentValue=_currentValue;
@property(retain, nonatomic) NSString *medalPicUrl; // @synthesize medalPicUrl=_medalPicUrl;
@property(nonatomic) unsigned int medalLevel; // @synthesize medalLevel=_medalLevel;
@property(nonatomic) BOOL medalEnableFlag; // @synthesize medalEnableFlag=_medalEnableFlag;
@property(nonatomic) unsigned long long clientProfileType; // @synthesize clientProfileType=_clientProfileType;
@property(nonatomic) unsigned long long profileType; // @synthesize profileType=_profileType;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)activeMedalDesc;
- (id)inactiveMedalDesc;
@property(readonly, nonatomic) NSString *profileTypeDesc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

