//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface FLMultiLangugeManager : NSObject
{
    int _appLanguage;
    NSDictionary *_languagesSummaryDic;
    NSArray *_supportedLanguages;
}

+ (id)sharedInstance;
@property(nonatomic) int appLanguage; // @synthesize appLanguage=_appLanguage;
@property(retain, nonatomic) NSArray *supportedLanguages; // @synthesize supportedLanguages=_supportedLanguages;
@property(retain, nonatomic) NSDictionary *languagesSummaryDic; // @synthesize languagesSummaryDic=_languagesSummaryDic;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *supportedLanguageNames;
@property(readonly, nonatomic) int currentAppLanguage;
@property(readonly, nonatomic) unsigned long long currentLanguageIndex;
@property(readonly, nonatomic) NSString *currentLanguageName;
@property(readonly, nonatomic) NSDictionary *currentLanguageDic;
- (void)applyLanguage:(int)arg1;
- (void)applyLanguageByDic:(id)arg1;
- (void)applyLanguageByIndex:(unsigned long long)arg1;
- (void)loadSupportedLanguages;
- (id)init;

@end

