//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLNewsStorage : NSObject
{
}

- (void)clearLocalStorage;
- (id)refreshTimePath;
- (id)getLocalSectionsRefreshTime;
- (BOOL)saveLocalSectionsRefreshTime:(id)arg1;
- (id)bannerPath;
- (id)getLocalBannerList;
- (BOOL)saveLocalBannerList:(id)arg1;
- (id)getLocalCalendarTypes;
- (BOOL)saveLocalCalendarTypes:(id)arg1;
- (id)fileNameForCalendarTypes;
- (id)fileNameForSectionType:(int)arg1 withTagType:(int)arg2;
- (id)getLocalNewsInfoDicForSectionType:(int)arg1 withTagType:(int)arg2;
- (BOOL)savelocalNewsInfoDicForSectionType:(int)arg1 withTagType:(int)arg2 newsInfoDic:(id)arg3;

@end

