//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLNewsBaseManager.h>

@interface FLNewsServerManager : FLNewsBaseManager
{
}

+ (id)sharedInstance;
- (void)clearNewsStorage;
- (id)liveNewsWithPbModel:(struct news *)arg1;
- (id)newsModelWithPbModel:(struct News_Rsp_NewsInfo *)arg1;
- (BOOL)fetchLiveNewsWithRequestType:(int)arg1 beginTime:(long long)arg2 endTime:(long long)arg3 requestCounts:(unsigned int)arg4 response:(CDUnknownBlockType)arg5;
- (BOOL)fetchNewsListWithSectionType:(int)arg1 requestType:(int)arg2 nnNewsId:(id)arg3 requestCounts:(unsigned int)arg4 response:(CDUnknownBlockType)arg5;
- (BOOL)fetchNewsListWithFetchModel:(id)arg1 withResponse:(CDUnknownBlockType)arg2;

@end

