//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLNetIPFectherDelegate-Protocol.h>
#import <FTEngine/FLNetIPStrategy-Protocol.h>
#import <FTEngine/FLShortConnectionTaskDelegate-Protocol.h>

@class FLNetIPTcpFecther, NSArray, NSMutableDictionary, NSString;

@interface FLNetIPStrategyMac : NSObject <FLNetIPFectherDelegate, FLShortConnectionTaskDelegate, FLNetIPStrategy>
{
    BOOL _guestMode;
    BOOL _testEnvironment;
    NSString *_designatedUserIP;
    NSArray *_netIPs;
    FLNetIPTcpFecther *_tcpFecther;
    NSArray *_tcpSniffers;
    unsigned long long _receivedCount;
    NSMutableDictionary *_domainIPIndex;
}

@property(readonly, nonatomic) BOOL testEnvironment; // @synthesize testEnvironment=_testEnvironment;
@property(readonly, nonatomic) BOOL guestMode; // @synthesize guestMode=_guestMode;
@property(retain, nonatomic) NSMutableDictionary *domainIPIndex; // @synthesize domainIPIndex=_domainIPIndex;
@property(nonatomic) unsigned long long receivedCount; // @synthesize receivedCount=_receivedCount;
@property(retain, nonatomic) NSArray *tcpSniffers; // @synthesize tcpSniffers=_tcpSniffers;
@property(retain, nonatomic) FLNetIPTcpFecther *tcpFecther; // @synthesize tcpFecther=_tcpFecther;
@property(retain) NSArray *netIPs; // @synthesize netIPs=_netIPs;
@property(retain, nonatomic) NSString *designatedUserIP; // @synthesize designatedUserIP=_designatedUserIP;
- (void).cxx_destruct;
- (void)shortConnectionTaskDidFinish:(id)arg1;
- (void)netIPFectherDidFail:(id)arg1;
- (void)netIPFecther:(id)arg1 didSuccessFetchIPs:(id)arg2;
@property(readonly, nonatomic) NSArray *sortedIPs;
- (void)fetchBackIPInfo;
- (id)nextIPWithDomainName:(id)arg1;
- (id)currentIPWithDomainName:(id)arg1;
- (void)configTestEnvironment:(BOOL)arg1 guestMode:(BOOL)arg2;
- (void)onNetworkStatusNotification:(id)arg1;
- (void)loadDefaultNetIPs;
- (void)fetchTcpIPs;
- (void)testNetIPs;
- (void)saveToFile;
- (void)loadFromFile;
- (id)fileName;
- (id)defaultDomain;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

