//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSDictionary, NSMutableArray, NSString;

@interface FLNetModel : FTCodingModel
{
    int _netType;
    NSString *_carrierName;
    NSString *_MCC;
    NSString *_MNC;
    NSString *_SSID;
    NSMutableArray *_userIpList;
    NSMutableArray *_guestIPList;
    NSDictionary *_dnsPodInfo;
}

@property(retain) NSDictionary *dnsPodInfo; // @synthesize dnsPodInfo=_dnsPodInfo;
@property(retain) NSMutableArray *guestIPList; // @synthesize guestIPList=_guestIPList;
@property(retain) NSMutableArray *userIpList; // @synthesize userIpList=_userIpList;
@property(retain, nonatomic) NSString *SSID; // @synthesize SSID=_SSID;
@property(retain, nonatomic) NSString *MNC; // @synthesize MNC=_MNC;
@property(retain, nonatomic) NSString *MCC; // @synthesize MCC=_MCC;
@property(retain, nonatomic) NSString *carrierName; // @synthesize carrierName=_carrierName;
@property(nonatomic) int netType; // @synthesize netType=_netType;
- (void).cxx_destruct;
- (id)description;
- (id)dnsPodIPListWithInfo:(id)arg1;
- (void)updateWithDnsPodInfo:(id)arg1;
- (id)sortedBackupIP:(id)arg1 withTestedIPList:(id)arg2;
- (id)sortedIPList:(id)arg1 withTestedIPList:(id)arg2;
- (void)updateWithBackupIPInfo:(id)arg1 andDnsPodInfo:(id)arg2 testedIPList:(id)arg3 grayEnvIPList:(id)arg4 isGuest:(BOOL)arg5;
- (void)updateWithBackupIPInfo:(id)arg1 andDnsPodInfo:(id)arg2 testedPingDataList:(id)arg3;
- (BOOL)hasNoMobileOperator;
- (BOOL)isInChinaMainLand;
@property(readonly, nonatomic) NSString *netName;
- (id)mobileOperatorName;
- (BOOL)isEqual:(id)arg1;
- (id)getIPWithIndex:(unsigned long long)arg1 isGuest:(BOOL)arg2;

@end

