//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLNetIPStrategy-Protocol.h>
#import <FTEngine/FLPingTesterDelegate-Protocol.h>
#import <FTEngine/NSURLConnectionDataDelegate-Protocol.h>
#import <FTEngine/NSURLConnectionDelegate-Protocol.h>

@class FLBaseAPIClient, FLNetModel, FLPingTester, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSURLConnection;

@interface FLNetIPMan : NSObject <FLPingTesterDelegate, NSURLConnectionDelegate, NSURLConnectionDataDelegate, FLNetIPStrategy>
{
    BOOL _guestMode;
    BOOL _testEnvironment;
    NSString *_designatedUserIP;
    NSString *_designatedGuestIP;
    FLBaseAPIClient *_httpClient;
    NSURLConnection *_userDnsPodConnection;
    NSURLConnection *_guestDnsPodConnection;
    NSDictionary *_backIPInfo;
    NSDictionary *_dnsPodIPInfo;
    FLPingTester *_pingTester;
    FLNetModel *_currentNetModel;
    NSMutableArray *_testedNetModelList;
    NSDictionary *_ipConfigInfo;
    NSMutableDictionary *_IPIndexInfo;
    NSArray *_guestServerIPs;
    NSArray *_serverIPs;
}

@property(readonly, nonatomic) BOOL testEnvironment; // @synthesize testEnvironment=_testEnvironment;
@property(readonly, nonatomic) BOOL guestMode; // @synthesize guestMode=_guestMode;
@property(retain, nonatomic) NSArray *serverIPs; // @synthesize serverIPs=_serverIPs;
@property(retain, nonatomic) NSArray *guestServerIPs; // @synthesize guestServerIPs=_guestServerIPs;
@property(retain, nonatomic) NSMutableDictionary *IPIndexInfo; // @synthesize IPIndexInfo=_IPIndexInfo;
@property(retain, nonatomic) NSDictionary *ipConfigInfo; // @synthesize ipConfigInfo=_ipConfigInfo;
@property(retain, nonatomic) NSMutableArray *testedNetModelList; // @synthesize testedNetModelList=_testedNetModelList;
@property(retain, nonatomic) FLNetModel *currentNetModel; // @synthesize currentNetModel=_currentNetModel;
@property(retain, nonatomic) FLPingTester *pingTester; // @synthesize pingTester=_pingTester;
@property(retain, nonatomic) NSDictionary *dnsPodIPInfo; // @synthesize dnsPodIPInfo=_dnsPodIPInfo;
@property(retain, nonatomic) NSDictionary *backIPInfo; // @synthesize backIPInfo=_backIPInfo;
@property(retain, nonatomic) NSURLConnection *guestDnsPodConnection; // @synthesize guestDnsPodConnection=_guestDnsPodConnection;
@property(retain, nonatomic) NSURLConnection *userDnsPodConnection; // @synthesize userDnsPodConnection=_userDnsPodConnection;
@property(retain, nonatomic) FLBaseAPIClient *httpClient; // @synthesize httpClient=_httpClient;
@property(retain, nonatomic) NSString *designatedGuestIP; // @synthesize designatedGuestIP=_designatedGuestIP;
@property(retain, nonatomic) NSString *designatedUserIP; // @synthesize designatedUserIP=_designatedUserIP;
- (void).cxx_destruct;
- (void)pingTesterDoneWithNetIPs:(id)arg1 context:(id)arg2;
- (void)rePingServerIPs;
- (BOOL)isValidIP:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)fetchGuestDnsPodIPInfo;
- (void)fetchUserDnsPodIPInfo;
- (void)fetchDNSPodIPInfo;
- (void)updateDnsPodInfo:(id)arg1;
- (id)loadIPConfigInfo;
- (void)fetchBackIPInfo;
- (void)updateBackIPInfo:(id)arg1;
@property(readonly, nonatomic) NSArray *sortedIPs;
- (unsigned int)totalIPCount;
- (void)resetIPIndex;
- (unsigned long long)changeToNextIPIndexForDomainName:(id)arg1;
- (unsigned long long)getCurrentIPIndexForDomainName:(id)arg1;
- (id)indexKeyWithDomainName:(id)arg1;
- (id)nextIPWithDomainName:(id)arg1;
- (id)currentIPWithDomainName:(id)arg1;
- (void)configTestEnvironment:(BOOL)arg1 guestMode:(BOOL)arg2;
- (void)saveTestedNetModelList;
- (id)loadTestedNetModelList;
- (void)addNetModel:(id)arg1;
- (id)getTestedNetModelWithNetModel:(id)arg1;
- (id)getCurrentSSID;
- (void)updateWWANInfoWithNetModel:(id)arg1;
- (void)setNetStatus:(long long)arg1;
- (void)onNetworkStatusNotification:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

