//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Reachability;

@interface FLNetStatusManager : NSObject
{
    Reachability *_netReachability;
    long long _lastNetStatus;
}

+ (id)defaultManager;
@property(nonatomic) long long lastNetStatus; // @synthesize lastNetStatus=_lastNetStatus;
@property(retain, nonatomic) Reachability *netReachability; // @synthesize netReachability=_netReachability;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long netStatus;
@property(readonly, nonatomic) BOOL isNetworkAvailable;
- (void)reachabilityChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

