//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLShortConnectionTask.h>

@class FLNetIP, NSDate, NSString;

@interface FLNetIPTcpSniffer : FLShortConnectionTask
{
    FLNetIP *_netIP;
    unsigned long long _userID;
    NSString *_deviceID;
    NSDate *_beginTime;
    double _duration;
}

@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSDate *beginTime; // @synthesize beginTime=_beginTime;
@property(retain, nonatomic) NSString *deviceID; // @synthesize deviceID=_deviceID;
@property(nonatomic) unsigned long long userID; // @synthesize userID=_userID;
@property(retain, nonatomic) FLNetIP *netIP; // @synthesize netIP=_netIP;
- (void).cxx_destruct;
- (void)fetchIPInfoDecode:(struct ft_packer *)arg1;
- (void)fetchIPInfo;
- (void)decodePacker:(struct ft_packer *)arg1;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)startSending;
- (void)start;
- (id)initWithDeviceID:(id)arg1;

@end

