//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol FLNetIPStrategy <NSObject>
@property(retain, nonatomic) NSString *designatedUserIP;
@property(readonly, nonatomic) NSArray *sortedIPs;
- (void)fetchBackIPInfo;
- (NSString *)nextIPWithDomainName:(NSString *)arg1;
- (NSString *)currentIPWithDomainName:(NSString *)arg1;
- (void)configTestEnvironment:(BOOL)arg1 guestMode:(BOOL)arg2;
@end

