//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class FLNewsStorage, NSDictionary, NSMutableDictionary;

@interface FLNewsBaseManager : FLBaseManager
{
    NSDictionary *_calendatTypeListDict;
    NSMutableDictionary *_nnNewsListDict;
    FLNewsStorage *_storage;
    NSMutableDictionary *_lastRefreshTimeStampDic;
}

@property(retain, nonatomic) NSMutableDictionary *lastRefreshTimeStampDic; // @synthesize lastRefreshTimeStampDic=_lastRefreshTimeStampDic;
@property(retain, nonatomic) FLNewsStorage *storage; // @synthesize storage=_storage;
@property(retain, nonatomic) NSMutableDictionary *nnNewsListDict; // @synthesize nnNewsListDict=_nnNewsListDict;
@property(retain, nonatomic) NSDictionary *calendatTypeListDict; // @synthesize calendatTypeListDict=_calendatTypeListDict;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setLastRefreshTimeStamp:(double)arg1 inSection:(int)arg2 withTagType:(int)arg3;
- (BOOL)shouldAutoRefreshSection:(int)arg1 withTagType:(int)arg2;
- (BOOL)fetchFinanceCalendarTypesWithResponse:(CDUnknownBlockType)arg1;
- (BOOL)fetchNewsListWithFetchModel:(id)arg1 withResponse:(CDUnknownBlockType)arg2;
- (void)updateLocalNewsInfoDicWithSectionType:(int)arg1 tagType:(int)arg2 newsInfoDic:(id)arg3 isAppending:(BOOL)arg4;
- (void)updateLocalNewsUnitDicWithSectionType:(int)arg1 newsDic:(id)arg2 isAppending:(BOOL)arg3;
- (id)newsDicWithSectionType:(int)arg1 withTagType:(int)arg2;
- (id)keyForSectionType:(int)arg1;
- (void)clearNewsStorage;
- (void)updateCalendarTypes:(id)arg1;
- (void)updateLocalBannerList:(id)arg1;
- (void)updatelocalNewsDicWithSection:(int)arg1 tagType:(int)arg2 withNewsDic:(id)arg3 isAppending:(BOOL)arg4;
- (void)updateLocalFinanceCalendarWithType:(unsigned short)arg1 withTime:(id)arg2 withMoreType:(int)arg3 withNewsDic:(id)arg4 isAppending:(BOOL)arg5;
- (id)getCalendarTypes;
- (id)getNewsSequenceWithSectionType:(int)arg1 withTagType:(int)arg2;
- (id)getNewsInfoListWithSectionType:(int)arg1 withTagType:(int)arg2;
- (id)getBannerList;

@end

