//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSArray, NSMutableArray, NSString;

@interface FLNewsInfoUnit : FTCodingModel
{
    int _sectionType;
    NSString *_yearOfDate;
    NSString *_monthOfDate;
    NSString *_dayOfDate;
    NSArray *_dataList;
    NSMutableArray *_modelDateArray;
}

+ (id)appendingToNewsInfoUnits:(id)arg1 withNewsInfoModelList:(id)arg2;
@property(retain, nonatomic) NSMutableArray *modelDateArray; // @synthesize modelDateArray=_modelDateArray;
@property(retain, nonatomic) NSArray *dataList; // @synthesize dataList=_dataList;
@property(nonatomic) int sectionType; // @synthesize sectionType=_sectionType;
@property(copy, nonatomic) NSString *dayOfDate; // @synthesize dayOfDate=_dayOfDate;
@property(copy, nonatomic) NSString *monthOfDate; // @synthesize monthOfDate=_monthOfDate;
@property(copy, nonatomic) NSString *yearOfDate; // @synthesize yearOfDate=_yearOfDate;
- (void).cxx_destruct;
- (id)chineseWithNum:(long long)arg1;
- (void)convertToDateWithTime:(long long)arg1;
- (void)addNewsInfoModel:(id)arg1;
- (BOOL)canReceiveNewsInfoModel:(id)arg1;

@end

