//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>

@class NSString;

@interface FLNetIP : NSObject <NSCoding>
{
    BOOL _isGrayEnvIP;
    BOOL _isGuest;
    unsigned int _weight;
    NSString *_address;
    NSString *_caption;
    NSString *_tcCaption;
    NSString *_isp;
    double _duration;
}

@property(nonatomic) double duration; // @synthesize duration=_duration;
@property BOOL isGuest; // @synthesize isGuest=_isGuest;
@property(nonatomic) unsigned int weight; // @synthesize weight=_weight;
@property(retain, nonatomic) NSString *isp; // @synthesize isp=_isp;
@property(nonatomic) BOOL isGrayEnvIP; // @synthesize isGrayEnvIP=_isGrayEnvIP;
@property(retain, nonatomic) NSString *tcCaption; // @synthesize tcCaption=_tcCaption;
@property(retain, nonatomic) NSString *caption; // @synthesize caption=_caption;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
- (void).cxx_destruct;
- (id)description;
- (long long)compare:(id)arg1;
- (long long)compareDuration:(id)arg1;
@property(readonly, nonatomic) NSString *markedAddress;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

