//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSMutableDictionary;

@interface FLNNCFeedRedPointModel : FTCodingModel <NSCopying>
{
    unsigned long long _pointType;
    unsigned long long _square_mark;
    unsigned long long _friends_mark;
    unsigned long long _essence_mark;
    unsigned long long _popular_mark;
    unsigned long long _follows_mark;
    NSMutableDictionary *_stockMarkDic;
}

@property(retain, nonatomic) NSMutableDictionary *stockMarkDic; // @synthesize stockMarkDic=_stockMarkDic;
@property(nonatomic) unsigned long long follows_mark; // @synthesize follows_mark=_follows_mark;
@property(nonatomic) unsigned long long popular_mark; // @synthesize popular_mark=_popular_mark;
@property(nonatomic) unsigned long long essence_mark; // @synthesize essence_mark=_essence_mark;
@property(nonatomic) unsigned long long friends_mark; // @synthesize friends_mark=_friends_mark;
@property(nonatomic) unsigned long long square_mark; // @synthesize square_mark=_square_mark;
@property(nonatomic) unsigned long long pointType; // @synthesize pointType=_pointType;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

