//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLNNCFeedElemSummary, FLNNCFeedElemUserInfo, FLNNCMsgContentModel;

@interface FLNNCMsgModel : FTCodingModel <NSCopying>
{
    int _feedType;
    unsigned long long _msgId;
    FLNNCFeedElemUserInfo *_authorInfo;
    FLNNCMsgContentModel *_msgContent;
    unsigned long long _timestamp;
    unsigned long long _feedId;
    FLNNCFeedElemSummary *_summary;
    unsigned long long _commentId;
    FLNNCFeedElemUserInfo *_feedAuthorInfo;
}

@property(nonatomic) int feedType; // @synthesize feedType=_feedType;
@property(retain, nonatomic) FLNNCFeedElemUserInfo *feedAuthorInfo; // @synthesize feedAuthorInfo=_feedAuthorInfo;
@property(nonatomic) unsigned long long commentId; // @synthesize commentId=_commentId;
@property(retain, nonatomic) FLNNCFeedElemSummary *summary; // @synthesize summary=_summary;
@property(nonatomic) unsigned long long feedId; // @synthesize feedId=_feedId;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) FLNNCMsgContentModel *msgContent; // @synthesize msgContent=_msgContent;
@property(retain, nonatomic) FLNNCFeedElemUserInfo *authorInfo; // @synthesize authorInfo=_authorInfo;
@property(nonatomic) unsigned long long msgId; // @synthesize msgId=_msgId;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

