//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLNNCSendTaskModel.h>

@class FLNNCFeedModel, NSDictionary;

@interface FLNNCLikeTaskModel : FLNNCSendTaskModel
{
    BOOL _isLike;
    unsigned long long _userId;
    FLNNCFeedModel *_feedModel;
    NSDictionary *_context;
}

@property(retain, nonatomic) NSDictionary *context; // @synthesize context=_context;
@property(retain, nonatomic) FLNNCFeedModel *feedModel; // @synthesize feedModel=_feedModel;
@property(nonatomic) BOOL isLike; // @synthesize isLike=_isLike;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (void)startSend;

@end

