//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLNNCSendTaskModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLNNCFeedElemUserInfo, FLNNCFeedLayoutModel, FLNNCFeedModel, FLNNCPostTaskModel, NSArray, NSString;

@interface FLNNCFeedElemComment : FLNNCSendTaskModel <NSCopying>
{
    BOOL _isFake;
    unsigned int _opMask;
    unsigned int _commentStatus;
    unsigned long long _commentId;
    FLNNCFeedElemUserInfo *_author;
    unsigned long long _timestamp;
    NSArray *_richTextList;
    NSArray *_pictureList;
    NSString *_textContent;
    unsigned long long _replyToCommentId;
    FLNNCFeedElemUserInfo *_replyToUser;
    unsigned long long _relatedFeedId;
    FLNNCFeedModel *_relatedFeed;
    FLNNCFeedLayoutModel *_layoutInfo;
    unsigned long long _clientKey;
    FLNNCPostTaskModel *_postTask;
}

@property(retain, nonatomic) FLNNCPostTaskModel *postTask; // @synthesize postTask=_postTask;
@property(nonatomic) unsigned long long clientKey; // @synthesize clientKey=_clientKey;
@property(nonatomic) BOOL isFake; // @synthesize isFake=_isFake;
@property(retain, nonatomic) FLNNCFeedLayoutModel *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(nonatomic) __weak FLNNCFeedModel *relatedFeed; // @synthesize relatedFeed=_relatedFeed;
@property(nonatomic) unsigned long long relatedFeedId; // @synthesize relatedFeedId=_relatedFeedId;
@property(nonatomic) unsigned int commentStatus; // @synthesize commentStatus=_commentStatus;
@property(retain, nonatomic) FLNNCFeedElemUserInfo *replyToUser; // @synthesize replyToUser=_replyToUser;
@property(nonatomic) unsigned long long replyToCommentId; // @synthesize replyToCommentId=_replyToCommentId;
@property(retain, nonatomic) NSString *textContent; // @synthesize textContent=_textContent;
@property(retain, nonatomic) NSArray *pictureList; // @synthesize pictureList=_pictureList;
@property(retain, nonatomic) NSArray *richTextList; // @synthesize richTextList=_richTextList;
@property(nonatomic) unsigned int opMask; // @synthesize opMask=_opMask;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) FLNNCFeedElemUserInfo *author; // @synthesize author=_author;
@property(nonatomic) unsigned long long commentId; // @synthesize commentId=_commentId;
- (void).cxx_destruct;
- (void)startSend;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) BOOL canDelete;
- (id)description;
- (void)dealloc;

@end

