//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLSNSBaseMgr.h>

@class NSMutableDictionary;

@interface FLNNCFeedOperateMgr : FLSNSBaseMgr
{
    NSMutableDictionary *_draftCommentsInfo;
    unsigned long long _currentUserId;
}

@property(nonatomic) unsigned long long currentUserId; // @synthesize currentUserId=_currentUserId;
@property(retain, nonatomic) NSMutableDictionary *draftCommentsInfo; // @synthesize draftCommentsInfo=_draftCommentsInfo;
- (void).cxx_destruct;
- (id)getDraftCommentForFeedId:(unsigned long long)arg1 commentId:(unsigned long long)arg2;
- (void)deleteDraftCommentForFeedId:(unsigned long long)arg1 commentId:(unsigned long long)arg2;
- (void)setDraftComment:(id)arg1 forFeedId:(unsigned long long)arg2 commentId:(unsigned long long)arg3;
- (void)shareWithFakeFeed:(id)arg1;
- (int)shareContentWithRichTextList:(id)arg1 orgRichTextList:(id)arg2 orgPicList:(id)arg3 orgUrl:(id)arg4 feedFrom:(id)arg5 context:(id)arg6;
- (int)reportFeedWithReportModel:(id)arg1;
- (int)deleteFeedCommentWithContactId:(unsigned long long)arg1 feedModel:(id)arg2 comment:(id)arg3 context:(id)arg4;
- (int)doComment:(id)arg1;
- (int)commentFeedWithContactId:(unsigned long long)arg1 feedModel:(id)arg2 replyTofeedComment:(id)arg3 richTextList:(id)arg4 pictureList:(id)arg5 clientKey:(unsigned long long)arg6 context:(id)arg7;
- (id)generateCommentWithRichText:(id)arg1 pictureList:(id)arg2 replyTofeedComment:(id)arg3 clientKey:(unsigned long long)arg4 feed:(id)arg5 context:(id)arg6;
- (int)doLikeFeedWithTask:(id)arg1;
- (int)likeFeedWithContactId:(unsigned long long)arg1 feedModel:(id)arg2 context:(id)arg3;
- (void)fakeLikeFeedModel:(id)arg1 isLike:(BOOL)arg2;
- (int)deleteFeedWithContactId:(unsigned long long)arg1 feedModel:(id)arg2 from:(int)arg3 subID:(unsigned long long)arg4 context:(id)arg5;
- (void)editWithFakeFeed:(id)arg1;
- (int)editFeedWithFeedId:(unsigned long long)arg1 contactId:(unsigned long long)arg2 richTextItems:(id)arg3 pictureList:(id)arg4 orgRichTextList:(id)arg5 orgPicList:(id)arg6 orgUrl:(id)arg7 feedFrom:(id)arg8 clientKey:(unsigned long long)arg9 context:(id)arg10;
- (void)postWithFakeFeed:(id)arg1;
- (int)postFeedWithContactId:(unsigned long long)arg1 richTextItems:(id)arg2 pictureList:(id)arg3 clientKey:(unsigned long long)arg4 context:(id)arg5;
- (id)generateFakeFeedModelWithContactId:(unsigned long long)arg1 richTextItems:(id)arg2 pictureList:(id)arg3 orgRichTextList:(id)arg4 orgPictureList:(id)arg5 orgUrl:(id)arg6 feedFrom:(id)arg7 clientKey:(unsigned long long)arg8 context:(id)arg9;
- (void)reloadDataForLoginUser:(unsigned long long)arg1;
- (id)init;

@end

