//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLNNCFeedElemUserInfo : FTCodingModel <NSCopying>
{
    unsigned int _gender;
    unsigned long long _userId;
    NSString *_nickName;
    NSString *_avatorUrl;
}

@property(nonatomic) unsigned int gender; // @synthesize gender=_gender;
@property(retain, nonatomic) NSString *avatorUrl; // @synthesize avatorUrl=_avatorUrl;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)debugDescription;
- (id)description;

@end

