//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLNNCFeedElemCommon, FLNNCFeedElemContent, FLNNCFeedElemLike, FLNNCFeedElemOriginal, FLNNCFeedElemSummary, FLNNCFeedElemUserInfo, FLNNCFeedLayoutModel, FLNNCPostTaskModel, NSArray, NSDictionary, NSMutableArray, NSString;

@interface FLNNCFeedModel : FTCodingModel <NSCopying>
{
    BOOL _hasMoreComments;
    BOOL _isFake;
    BOOL _isSendFailed;
    BOOL _showAllLikeUser;
    unsigned int _commentsTotalCount;
    int _feedFromType;
    int _feedUploadStatus;
    FLNNCFeedElemCommon *_feedComm;
    FLNNCFeedElemUserInfo *_authorInfo;
    FLNNCFeedElemSummary *_summary;
    FLNNCFeedElemContent *_content;
    FLNNCFeedElemOriginal *_original;
    FLNNCFeedElemLike *_like;
    NSMutableArray *_commentsList;
    unsigned long long _commentsMark;
    NSString *_contentHtml;
    NSArray *_plates;
    unsigned long long _browseCount;
    NSArray *_popularComments;
    NSString *_feedfrom;
    FLNNCFeedLayoutModel *_layoutInfo;
    NSDictionary *_extraInfo;
    FLNNCPostTaskModel *_postTask;
}

@property(retain, nonatomic) FLNNCPostTaskModel *postTask; // @synthesize postTask=_postTask;
@property(retain, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(retain, nonatomic) FLNNCFeedLayoutModel *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(nonatomic) BOOL showAllLikeUser; // @synthesize showAllLikeUser=_showAllLikeUser;
@property(nonatomic) BOOL isSendFailed; // @synthesize isSendFailed=_isSendFailed;
@property(nonatomic) BOOL isFake; // @synthesize isFake=_isFake;
@property(nonatomic) int feedUploadStatus; // @synthesize feedUploadStatus=_feedUploadStatus;
@property(nonatomic) int feedFromType; // @synthesize feedFromType=_feedFromType;
@property(retain, nonatomic) NSString *feedfrom; // @synthesize feedfrom=_feedfrom;
@property(retain, nonatomic) NSArray *popularComments; // @synthesize popularComments=_popularComments;
@property(nonatomic) unsigned long long browseCount; // @synthesize browseCount=_browseCount;
@property(retain, nonatomic) NSArray *plates; // @synthesize plates=_plates;
@property(retain, nonatomic) NSString *contentHtml; // @synthesize contentHtml=_contentHtml;
@property(nonatomic) unsigned int commentsTotalCount; // @synthesize commentsTotalCount=_commentsTotalCount;
@property(nonatomic) unsigned long long commentsMark; // @synthesize commentsMark=_commentsMark;
@property(nonatomic) BOOL hasMoreComments; // @synthesize hasMoreComments=_hasMoreComments;
@property(retain, nonatomic) NSMutableArray *commentsList; // @synthesize commentsList=_commentsList;
@property(retain, nonatomic) FLNNCFeedElemLike *like; // @synthesize like=_like;
@property(retain, nonatomic) FLNNCFeedElemOriginal *original; // @synthesize original=_original;
@property(retain, nonatomic) FLNNCFeedElemContent *content; // @synthesize content=_content;
@property(retain, nonatomic) FLNNCFeedElemSummary *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) FLNNCFeedElemUserInfo *authorInfo; // @synthesize authorInfo=_authorInfo;
@property(retain, nonatomic) FLNNCFeedElemCommon *feedComm; // @synthesize feedComm=_feedComm;
- (void).cxx_destruct;
- (BOOL)extraInfoContainsStockId:(unsigned long long)arg1;
- (void)clearLayoutInfo;
- (void)publish;
- (void)startShare;
- (void)startEditPost;
- (BOOL)shouldCompeleteInfo:(id)arg1;
- (void)startPost;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) BOOL hidenFeedFrom;
@property(readonly, nonatomic) BOOL canShare;
@property(readonly, nonatomic) BOOL canComment;
@property(readonly, nonatomic) BOOL canLike;
@property(readonly, nonatomic) BOOL canDelete;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

