//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/uploadDelegate-Protocol.h>

@class FLNNCFeedElemComment, FLNNCFeedModel, NSMutableArray, NSString;

@interface FLNNCPostTaskModel : FTCodingModel <uploadDelegate>
{
    int _requestId;
    FLNNCFeedModel *_delegateFeed;
    FLNNCFeedElemComment *_delegateComment;
    CDUnknownBlockType _uploadDoneBlock;
    NSMutableArray *_picElemList;
}

+ (id)postTaskModelWithFeedModel:(id)arg1;
@property(retain, nonatomic) NSMutableArray *picElemList; // @synthesize picElemList=_picElemList;
@property(nonatomic) int requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) CDUnknownBlockType uploadDoneBlock; // @synthesize uploadDoneBlock=_uploadDoneBlock;
@property(nonatomic) __weak FLNNCFeedElemComment *delegateComment; // @synthesize delegateComment=_delegateComment;
@property(nonatomic) __weak FLNNCFeedModel *delegateFeed; // @synthesize delegateFeed=_delegateFeed;
- (void).cxx_destruct;
- (void)uploadTaskChangedStatus:(int)arg1 withContextObj:(id)arg2;
- (void)uploadPictures;
- (void)uploadTaskDone;
- (void)doPost;
- (void)start;
- (void)setUploadPictureList:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

