//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLNNCReportModel : FTCodingModel <NSCopying>
{
    int _reportType;
    unsigned long long _userId;
    unsigned long long _feedId;
    unsigned long long _commentId;
    NSString *_reportReason;
}

@property(copy, nonatomic) NSString *reportReason; // @synthesize reportReason=_reportReason;
@property(nonatomic) int reportType; // @synthesize reportType=_reportType;
@property(nonatomic) unsigned long long commentId; // @synthesize commentId=_commentId;
@property(nonatomic) unsigned long long feedId; // @synthesize feedId=_feedId;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

