//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLSNSBaseMgr.h>

@class FLNNCFeedCacheModel, NSArray, NSMutableArray, NSMutableDictionary;
@protocol FLNNCircleIMServiceProtocol, FLNNCircleLayoutProtocol;

@interface FLNNCFeedsListMgr : FLSNSBaseMgr
{
    id <FLNNCircleLayoutProtocol> _layoutManager;
    id <FLNNCircleIMServiceProtocol> _imservice;
    FLNNCFeedCacheModel *_allFeedsCacheModel;
    FLNNCFeedCacheModel *_personalFeedsCacheModel;
    FLNNCFeedCacheModel *_stockFeedsCacheModel;
    FLNNCFeedCacheModel *_essenceFeedsCacheModel;
    FLNNCFeedCacheModel *_popularFeedsCacheModel;
    FLNNCFeedCacheModel *_followsFeedsCacheModel;
    NSMutableArray *_waitingFeedsList;
    NSMutableArray *_waitingCommentsList;
    NSMutableArray *_waitingLikeList;
    NSArray *_stockFailedFeeds;
    NSMutableDictionary *_plateVisitTimeDic;
    unsigned long long _currentUserId;
}

@property(nonatomic) unsigned long long currentUserId; // @synthesize currentUserId=_currentUserId;
@property(retain, nonatomic) NSMutableDictionary *plateVisitTimeDic; // @synthesize plateVisitTimeDic=_plateVisitTimeDic;
@property(readonly, nonatomic) NSArray *stockFailedFeeds; // @synthesize stockFailedFeeds=_stockFailedFeeds;
@property(retain, nonatomic) NSMutableArray *waitingLikeList; // @synthesize waitingLikeList=_waitingLikeList;
@property(retain, nonatomic) NSMutableArray *waitingCommentsList; // @synthesize waitingCommentsList=_waitingCommentsList;
@property(retain, nonatomic) NSMutableArray *waitingFeedsList; // @synthesize waitingFeedsList=_waitingFeedsList;
@property(retain, nonatomic) FLNNCFeedCacheModel *followsFeedsCacheModel; // @synthesize followsFeedsCacheModel=_followsFeedsCacheModel;
@property(retain, nonatomic) FLNNCFeedCacheModel *popularFeedsCacheModel; // @synthesize popularFeedsCacheModel=_popularFeedsCacheModel;
@property(retain, nonatomic) FLNNCFeedCacheModel *essenceFeedsCacheModel; // @synthesize essenceFeedsCacheModel=_essenceFeedsCacheModel;
@property(retain, nonatomic) FLNNCFeedCacheModel *stockFeedsCacheModel; // @synthesize stockFeedsCacheModel=_stockFeedsCacheModel;
@property(retain, nonatomic) FLNNCFeedCacheModel *personalFeedsCacheModel; // @synthesize personalFeedsCacheModel=_personalFeedsCacheModel;
@property(retain, nonatomic) FLNNCFeedCacheModel *allFeedsCacheModel; // @synthesize allFeedsCacheModel=_allFeedsCacheModel;
@property(nonatomic) __weak id <FLNNCircleIMServiceProtocol> imservice; // @synthesize imservice=_imservice;
@property(retain, nonatomic) id <FLNNCircleLayoutProtocol> layoutManager; // @synthesize layoutManager=_layoutManager;
- (void).cxx_destruct;
- (id)getSendFailedFeedsList;
@property(readonly, nonatomic) NSArray *failedFeedsList;
- (void)setListSequence:(id)arg1 relationType:(int)arg2 andPlateId:(unsigned int)arg3;
- (id)getListSequeceFrom:(int)arg1 plateId:(unsigned int)arg2;
- (id)getPlateVisitTimeKey:(int)arg1 plateID:(unsigned int)arg2;
- (void)layoutDetailFeed:(id)arg1;
- (void)layoutListFeed:(id)arg1;
- (void)layoutListFeeds:(id)arg1;
- (void)updateFeedModel:(id)arg1 userId:(unsigned long long)arg2 disPlayName:(id)arg3;
- (void)updateComment:(id)arg1 userId:(unsigned long long)arg2 disPlayName:(id)arg3;
- (void)handleDisplayNameUpdate:(id)arg1;
- (void)languageChanged:(id)arg1;
- (void)mainThreadPostNotification:(id)arg1 object:(id)arg2 resultInfo:(id)arg3;
- (int)fetchSerRedPointDataByRedPointType:(unsigned long long)arg1 context:(id)arg2;
- (void)nncPushRedPointDecodeMsgPush:(struct util_byteios_net *)arg1;
- (BOOL)clearLocalFeedCacheWithUserId:(unsigned long long)arg1;
- (void)updateCacheWithFeed:(id)arg1;
- (void)syncCacheWithPushedFeedsList:(id)arg1;
- (id)getLocalFeedModelWithFeedId:(unsigned long long)arg1;
- (void)updateDraftCommentWithPostResult:(id)arg1;
- (void)updateDraftFeedWithPostResult:(id)arg1;
- (void)updateFeedStatusWithFeedModel:(id)arg1;
- (void)doUpdateFeedStatus:(id)arg1 withOtherFeed:(id)arg2;
- (void)removeLikeTask:(id)arg1;
- (void)likeLocalFeedWithTask:(id)arg1;
- (void)operateLocalComment:(id)arg1 feedModel:(id)arg2 isAdd:(BOOL)arg3;
- (void)doOperateLocalComment:(id)arg1 feedModel:(id)arg2 isAdd:(BOOL)arg3;
- (void)updateCommentStatusWithComment:(id)arg1 feedId:(unsigned long long)arg2;
- (void)doUpdateComment:(id)arg1 toFeed:(id)arg2;
- (void)addLocalComment:(id)arg1 toFeedModel:(id)arg2;
- (void)deleteLocalComment:(id)arg1 fromFeedModel:(id)arg2;
- (void)replaceLocalFeed:(id)arg1;
- (void)replaceFeedModel:(id)arg1 inCache:(id)arg2;
- (void)addLocalFeed:(id)arg1;
- (void)deleteLocalFeed:(id)arg1;
- (void)insertFeed:(id)arg1 toFeedsList:(id)arg2;
- (void)insertDraftFeedsToFeedsList:(id)arg1 withStockId:(unsigned long long)arg2;
- (void)insertDraftFeedsToFeedsList:(id)arg1;
- (id)updateWithRequestCacheModel:(id)arg1 loginUserId:(unsigned long long)arg2 relationType:(int)arg3 feedList:(id)arg4 hasMore:(BOOL)arg5 feedsMark:(unsigned long long)arg6 personalFeedsOwnerId:(unsigned long long)arg7 isAppending:(BOOL)arg8;
- (void)checkAndUpdateDraftLikeWithFeedModel:(id)arg1;
- (void)checkAndUpdateDraftCommentWithFeedModel:(id)arg1;
- (void)checkAndUpdateDraftFeedsWithFeedModel:(id)arg1;
- (int)fetchFeedListWithContactId:(unsigned long long)arg1 relationType:(int)arg2 plateID:(unsigned int)arg3 refreshType:(int)arg4 cacheModel:(id)arg5 feedsOwnerId:(unsigned long long)arg6 stock:(id)arg7 count:(unsigned int)arg8 notifyName:(id)arg9;
- (int)fetchFeedCommentsWithFeedModel:(id)arg1 context:(id)arg2;
- (int)fetchFeedDetailWithFeedModel:(id)arg1 context:(id)arg2;
- (int)fetchFollowsFeedsWithContactId:(unsigned long long)arg1 plateID:(unsigned int)arg2 refreshType:(int)arg3 context:(id)arg4;
- (id)getLocalFollowsFeedsList;
- (int)fetchPopularFeedsWithContactId:(unsigned long long)arg1 plateID:(unsigned int)arg2 refreshType:(int)arg3 context:(id)arg4;
- (id)getLocalPopularFeedsList;
- (int)fetchEssenceFeedsWithContactId:(unsigned long long)arg1 plateID:(unsigned int)arg2 refreshType:(int)arg3 context:(id)arg4;
- (id)getLocalEssenceFeedsList;
- (int)fetchStockFeedsWithStock:(id)arg1 limitCount:(long long)arg2 context:(id)arg3;
- (int)fetchStockFeedsWithStock:(id)arg1 refreshType:(int)arg2 context:(id)arg3;
- (id)getLocalStockFeedsWithStock:(id)arg1;
- (int)fetchPersonalLatestFeedOfContactId:(unsigned long long)arg1;
- (int)fetchPersonalFeedsWithContactId:(unsigned long long)arg1 refreshType:(int)arg2 feedsOwnerId:(unsigned long long)arg3 cacheModel:(id)arg4 context:(id)arg5;
- (id)getLocalPersonalFeedsWhose:(unsigned long long)arg1;
- (int)fetchAllFeedsWithContactId:(unsigned long long)arg1 plateID:(unsigned int)arg2 refreshType:(int)arg3 context:(id)arg4;
- (id)getLocalAllFeeds;
- (id)getSendFailedStockFeedsByStockId:(unsigned long long)arg1;
- (void)loadLocalFeedsWithUserId:(unsigned long long)arg1;
- (void)resetPlateVisitTime;
- (void)updateFeedListVisitTimeToNowByFeedType:(int)arg1 plateID:(unsigned int)arg2;
- (void)setFeedListType:(int)arg1 plateID:(unsigned int)arg2 visitTime:(double)arg3;
- (void)setFeedListVisitTime:(double)arg1 relationType:(int)arg2;
- (BOOL)shouldAutoRefresh:(int)arg1 plateID:(unsigned int)arg2;
- (void)reloadDataForLoginUser:(unsigned long long)arg1;
- (id)init;

@end

