//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSMutableArray, NSMutableDictionary;

@interface FLNNCFeedCacheModel : FTCodingModel <NSCopying>
{
    BOOL _hasMore;
    int _relationType;
    unsigned int _plateID;
    NSMutableArray *_feedList;
    unsigned long long _feedsMark;
    unsigned long long _loginUserId;
    unsigned long long _personalFeedsOwnerId;
    unsigned long long _stockId;
    unsigned long long _subID;
    NSMutableDictionary *_subCacheModelDic;
}

@property(retain, nonatomic) NSMutableDictionary *subCacheModelDic; // @synthesize subCacheModelDic=_subCacheModelDic;
@property(nonatomic) unsigned long long subID; // @synthesize subID=_subID;
@property(nonatomic) unsigned long long stockId; // @synthesize stockId=_stockId;
@property(nonatomic) unsigned long long personalFeedsOwnerId; // @synthesize personalFeedsOwnerId=_personalFeedsOwnerId;
@property(nonatomic) unsigned int plateID; // @synthesize plateID=_plateID;
@property(nonatomic) unsigned long long loginUserId; // @synthesize loginUserId=_loginUserId;
@property(nonatomic) unsigned long long feedsMark; // @synthesize feedsMark=_feedsMark;
@property(nonatomic) BOOL hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableArray *feedList; // @synthesize feedList=_feedList;
@property(nonatomic) int relationType; // @synthesize relationType=_relationType;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)keyForType:(int)arg1 subID:(unsigned long long)arg2;
- (void)setSubCacheModel:(id)arg1 relationType:(int)arg2 subId:(unsigned long long)arg3;
- (id)subCacheModel:(int)arg1 subID:(unsigned long long)arg2;
- (id)init;

@end

