//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLSNSBaseMgr.h>

@class FLNNCMsgUnreadModel, NSMutableDictionary, NSTimer;

@interface FLNNCMsgListMgr : FLSNSBaseMgr
{
    BOOL _firstKeepAliveAfterLogin;
    NSMutableDictionary *_msgCacheModelDict;
    FLNNCMsgUnreadModel *_msgUnreadModel;
    double _lastTryTime;
    double _keepAliveInterverl;
    NSTimer *_keepAliveTimer;
}

@property(nonatomic) BOOL firstKeepAliveAfterLogin; // @synthesize firstKeepAliveAfterLogin=_firstKeepAliveAfterLogin;
@property(retain, nonatomic) NSTimer *keepAliveTimer; // @synthesize keepAliveTimer=_keepAliveTimer;
@property(nonatomic) double keepAliveInterverl; // @synthesize keepAliveInterverl=_keepAliveInterverl;
@property(nonatomic) double lastTryTime; // @synthesize lastTryTime=_lastTryTime;
@property(retain, nonatomic) FLNNCMsgUnreadModel *msgUnreadModel; // @synthesize msgUnreadModel=_msgUnreadModel;
@property(retain, nonatomic) NSMutableDictionary *msgCacheModelDict; // @synthesize msgCacheModelDict=_msgCacheModelDict;
- (void).cxx_destruct;
- (void)keepAlive;
- (void)onTimer:(id)arg1;
- (void)deleteMsgCache:(unsigned long long)arg1;
- (void)resetMsgUnreadNum:(unsigned int)arg1;
- (void)updateMsgUnreadNum:(id)arg1;
- (void)updateMsgListAfterDelete:(unsigned int)arg1 forUser:(unsigned long long)arg2 msgId:(unsigned long long)arg3;
- (void)updateMsgListWithMsgModel:(id)arg1;
- (int)requestDeleteMsgWithMsgId:(unsigned long long)arg1 willDeleteAll:(unsigned int)arg2 context:(id)arg3;
- (int)fetchNewMsgFeedsWithMsgMark:(unsigned long long)arg1 reqType:(int)arg2 msg_num:(unsigned int)arg3 cacheArray:(id)arg4 context:(id)arg5;
- (int)fetchNewMsgFeedsWithMsgMark:(unsigned long long)arg1 reqType:(int)arg2 msg_num:(unsigned int)arg3 context:(id)arg4;
- (void)decodeMsgPush:(struct util_byteios_net *)arg1;
- (id)getUnreadMsgNum;
- (id)getLocalMsgCacheModel:(unsigned long long)arg1;
- (void)reloadDataForLoginUser:(unsigned long long)arg1;
- (id)init;
- (void)dealloc;

@end

