//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLNNCFeedViewPermission;

@interface FLNNCFeedElemCommon : FTCodingModel <NSCopying>
{
    BOOL _isEssenc;
    BOOL _isPopular;
    BOOL _isFriend;
    BOOL _isFollow;
    BOOL _isStock;
    unsigned int _feedType;
    int _feedStatus;
    unsigned int _opMask;
    unsigned long long _feedid;
    unsigned long long _timestamp;
    unsigned long long _clientKey;
    FLNNCFeedViewPermission *_feedPermission;
}

@property(nonatomic) BOOL isStock; // @synthesize isStock=_isStock;
@property(nonatomic) BOOL isFollow; // @synthesize isFollow=_isFollow;
@property(nonatomic) BOOL isFriend; // @synthesize isFriend=_isFriend;
@property(nonatomic) BOOL isPopular; // @synthesize isPopular=_isPopular;
@property(nonatomic) BOOL isEssenc; // @synthesize isEssenc=_isEssenc;
@property(retain, nonatomic) FLNNCFeedViewPermission *feedPermission; // @synthesize feedPermission=_feedPermission;
@property(nonatomic) unsigned long long clientKey; // @synthesize clientKey=_clientKey;
@property(nonatomic) unsigned int opMask; // @synthesize opMask=_opMask;
@property(nonatomic) int feedStatus; // @synthesize feedStatus=_feedStatus;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned long long feedid; // @synthesize feedid=_feedid;
@property(nonatomic) unsigned int feedType; // @synthesize feedType=_feedType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

