//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLNNCFeedElemUserInfo, NSMutableArray;

@interface FLNNCMsgUnreadModel : FTCodingModel <NSCopying>
{
    unsigned int _unreadNum;
    unsigned long long _userId;
    FLNNCFeedElemUserInfo *_latestAuthorUserInfo;
    NSMutableArray *_relatedFeedsList;
}

@property(retain, nonatomic) NSMutableArray *relatedFeedsList; // @synthesize relatedFeedsList=_relatedFeedsList;
@property(retain, nonatomic) FLNNCFeedElemUserInfo *latestAuthorUserInfo; // @synthesize latestAuthorUserInfo=_latestAuthorUserInfo;
@property(nonatomic) unsigned int unreadNum; // @synthesize unreadNum=_unreadNum;
@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

