//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSMutableArray;

@interface FLNNCMsgCacheModel : FTCodingModel <NSCopying>
{
    BOOL _hasMore;
    int _reqType;
    NSMutableArray *_msgList;
    unsigned long long _msgMark;
    unsigned long long _userId;
}

@property(nonatomic) unsigned long long userId; // @synthesize userId=_userId;
@property(nonatomic) unsigned long long msgMark; // @synthesize msgMark=_msgMark;
@property(nonatomic) BOOL hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableArray *msgList; // @synthesize msgList=_msgList;
@property(nonatomic) int reqType; // @synthesize reqType=_reqType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

