//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLNNCFeedLayoutModel, NSMutableArray, NSString;

@interface FLNNCFeedElemLike : FTCodingModel <NSCopying>
{
    BOOL _alreadyLiked;
    unsigned int _likedNum;
    NSMutableArray *_likedUserList;
    NSString *_namesText;
    FLNNCFeedLayoutModel *_layoutInfo;
}

@property(retain, nonatomic) FLNNCFeedLayoutModel *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(retain, nonatomic) NSString *namesText; // @synthesize namesText=_namesText;
@property(retain, nonatomic) NSMutableArray *likedUserList; // @synthesize likedUserList=_likedUserList;
@property(nonatomic) unsigned int likedNum; // @synthesize likedNum=_likedNum;
@property(nonatomic) BOOL alreadyLiked; // @synthesize alreadyLiked=_alreadyLiked;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

