//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSDictionary;

@interface FLNNCFeedLayoutModel : FTCodingModel <NSCopying>
{
    BOOL _showWholeTextButton;
    double _totalHeight;
    double _totalWidth;
    double _contentLabelHeight;
    double _photoWallHeight;
    double _commentTableHeight;
    NSDictionary *_contentInfoDic;
    NSDictionary *_linkDic;
    NSDictionary *_personalHistoryLayoutDic;
}

@property(retain, nonatomic) NSDictionary *personalHistoryLayoutDic; // @synthesize personalHistoryLayoutDic=_personalHistoryLayoutDic;
@property(retain, nonatomic) NSDictionary *linkDic; // @synthesize linkDic=_linkDic;
@property(retain, nonatomic) NSDictionary *contentInfoDic; // @synthesize contentInfoDic=_contentInfoDic;
@property(nonatomic) BOOL showWholeTextButton; // @synthesize showWholeTextButton=_showWholeTextButton;
@property(nonatomic) double commentTableHeight; // @synthesize commentTableHeight=_commentTableHeight;
@property(nonatomic) double photoWallHeight; // @synthesize photoWallHeight=_photoWallHeight;
@property(nonatomic) double contentLabelHeight; // @synthesize contentLabelHeight=_contentLabelHeight;
@property(nonatomic) double totalWidth; // @synthesize totalWidth=_totalWidth;
@property(nonatomic) double totalHeight; // @synthesize totalHeight=_totalHeight;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)debugDescription;

@end

