//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>

@class NSString;

@interface FLOperationAnnouncementModel : NSObject <NSCoding>
{
    BOOL _closed;
    BOOL _isValid;
    int _oaID;
    int _area;
    int _position;
    int _style;
    long long _startTime;
    long long _endTime;
    NSString *_title;
    NSString *_content;
    NSString *_link;
    long long _contentUpdateTime;
}

@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic) BOOL isValid; // @synthesize isValid=_isValid;
@property(nonatomic) BOOL closed; // @synthesize closed=_closed;
@property(nonatomic) int position; // @synthesize position=_position;
@property(nonatomic) int area; // @synthesize area=_area;
@property(nonatomic) long long contentUpdateTime; // @synthesize contentUpdateTime=_contentUpdateTime;
@property(copy, nonatomic) NSString *link; // @synthesize link=_link;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) int oaID; // @synthesize oaID=_oaID;
- (void).cxx_destruct;
- (void)decodeWithDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;

@end

