//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLStockSimple.h>

@interface FLOptionSimple : FLStockSimple
{
    unsigned int _openInterest;
    unsigned int _prevOpenInterest;
    unsigned long long _priceStrike;
    long long _delta;
    long long _gamma;
    long long _rho;
    long long _theta;
    long long _vega;
    long long _impvol;
}

@property(nonatomic) long long impvol; // @synthesize impvol=_impvol;
@property(nonatomic) long long vega; // @synthesize vega=_vega;
@property(nonatomic) long long theta; // @synthesize theta=_theta;
@property(nonatomic) long long rho; // @synthesize rho=_rho;
@property(nonatomic) long long gamma; // @synthesize gamma=_gamma;
@property(nonatomic) long long delta; // @synthesize delta=_delta;
@property(nonatomic) unsigned long long priceStrike; // @synthesize priceStrike=_priceStrike;
@property(nonatomic) unsigned int prevOpenInterest; // @synthesize prevOpenInterest=_prevOpenInterest;
@property(nonatomic) unsigned int openInterest; // @synthesize openInterest=_openInterest;
@property(readonly, nonatomic) long long priceChangePercent;
@property(readonly, nonatomic) long long priceChangeValue;

@end

