//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSMutableDictionary;

@interface FLOperationAnnouncementManager : FLBaseManager
{
    BOOL _haveNewOperationAnnouncement;
    BOOL _isFetchingOperationAnnouncements;
    NSMutableDictionary *_operationAnnouncementData;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL isFetchingOperationAnnouncements; // @synthesize isFetchingOperationAnnouncements=_isFetchingOperationAnnouncements;
@property(nonatomic) BOOL haveNewOperationAnnouncement; // @synthesize haveNewOperationAnnouncement=_haveNewOperationAnnouncement;
@property(retain, nonatomic) NSMutableDictionary *operationAnnouncementData; // @synthesize operationAnnouncementData=_operationAnnouncementData;
- (void).cxx_destruct;
- (void)clearOperationAnnouncementData:(id)arg1;
- (void)saveClosedAction:(id)arg1;
- (id)selectOperationAnnouncementModels;
- (id)selectOperationAnnouncementModelWithAreaType:(int)arg1;
- (id)getCurrentUserDocPath;
- (void)saveLocalData;
- (BOOL)isNewAnnouncementsWithAnnouncementModel:(id)arg1 inNSArray:(id)arg2;
- (id)setNewOperationAnnouncementData:(id)arg1;
- (void)setLastUpdateTime:(long long)arg1;
- (long long)getLocalUpdateTime;
- (void)updateOperationAnnouncementData:(id)arg1;
- (void)handleRequestResponse:(id)arg1;
- (void)saveLastRequestTime;
- (double)getLastRequestTime;
- (BOOL)shouldRequestOperationAnnouncementData;
- (void)requestOperationAnnouncementData;
- (void)dealloc;
- (id)init;

@end

