//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseHandler.h>

@interface FLOrderHandler : FLBaseHandler
{
}

- (void)decodePacker:(struct ft_packer *)arg1;
- (void)keyUpdate;
- (void)keepAliveWithTimeout:(unsigned int)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)sessionLoginDecode:(struct util_byteios_net *)arg1;
- (void)sessionLoginDecodeErrorCodes:(struct util_byteios_net *)arg1;
- (void)startAuthenticiateClientSigAndClientKey;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (BOOL)isLoginSuccess;
- (id)initWithQueue:(id)arg1;

@end

