//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseModel.h>

@class NSDate, NSString;

@interface FLOrder : FLBaseModel
{
    BOOL _directionLock;
    BOOL _triggerOrder;
    BOOL _isTimeout;
    unsigned int _errorCode;
    int _triggerState;
    int _triggerCompareType;
    int _priceFollowType;
    int _triggerPriceFollowType;
    int _triggerOrderType;
    int _statusSortedKey;
    int _statusCategory;
    int _triggerStateCategory;
    long long _oldPrice;
    long long _oldQuantity;
    long long _successQuantity;
    long long _averagePrice;
    unsigned long long _localID;
    NSString *_orderID;
    long long _side;
    NSString *_lastError;
    NSString *_displayErrorMessage;
    NSString *_statusText;
    NSDate *_createdDate;
    NSDate *_updatedDate;
    unsigned long long _triggerPrice;
    NSDate *_triggerExpired;
    NSDate *_triggerDate;
    unsigned long long _triggerOrderID;
    long long _priceFollow;
    long long _triggerPriceFollow;
    NSString *_triggerDesc;
}

+ (int)defaultStockUnit;
@property(nonatomic) int triggerStateCategory; // @synthesize triggerStateCategory=_triggerStateCategory;
@property(nonatomic) int statusCategory; // @synthesize statusCategory=_statusCategory;
@property(nonatomic) int statusSortedKey; // @synthesize statusSortedKey=_statusSortedKey;
@property(nonatomic) BOOL isTimeout; // @synthesize isTimeout=_isTimeout;
@property(nonatomic) int triggerOrderType; // @synthesize triggerOrderType=_triggerOrderType;
@property(readonly, nonatomic) NSString *triggerDesc; // @synthesize triggerDesc=_triggerDesc;
@property(nonatomic) long long triggerPriceFollow; // @synthesize triggerPriceFollow=_triggerPriceFollow;
@property(nonatomic) int triggerPriceFollowType; // @synthesize triggerPriceFollowType=_triggerPriceFollowType;
@property(nonatomic) long long priceFollow; // @synthesize priceFollow=_priceFollow;
@property(nonatomic) int priceFollowType; // @synthesize priceFollowType=_priceFollowType;
@property(nonatomic) unsigned long long triggerOrderID; // @synthesize triggerOrderID=_triggerOrderID;
@property(nonatomic) int triggerCompareType; // @synthesize triggerCompareType=_triggerCompareType;
@property(retain, nonatomic) NSDate *triggerDate; // @synthesize triggerDate=_triggerDate;
@property(retain, nonatomic) NSDate *triggerExpired; // @synthesize triggerExpired=_triggerExpired;
@property(nonatomic) unsigned long long triggerPrice; // @synthesize triggerPrice=_triggerPrice;
@property(nonatomic) int triggerState; // @synthesize triggerState=_triggerState;
@property(nonatomic) BOOL triggerOrder; // @synthesize triggerOrder=_triggerOrder;
@property(retain, nonatomic) NSDate *updatedDate; // @synthesize updatedDate=_updatedDate;
@property(retain, nonatomic) NSDate *createdDate; // @synthesize createdDate=_createdDate;
@property(retain, nonatomic) NSString *statusText; // @synthesize statusText=_statusText;
@property(readonly, nonatomic) NSString *displayErrorMessage; // @synthesize displayErrorMessage=_displayErrorMessage;
@property(copy, nonatomic) NSString *lastError; // @synthesize lastError=_lastError;
@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) BOOL directionLock; // @synthesize directionLock=_directionLock;
@property(nonatomic) long long side; // @synthesize side=_side;
@property(copy, nonatomic) NSString *orderID; // @synthesize orderID=_orderID;
@property(nonatomic) unsigned long long localID; // @synthesize localID=_localID;
@property(nonatomic) long long averagePrice; // @synthesize averagePrice=_averagePrice;
@property(nonatomic) long long successQuantity; // @synthesize successQuantity=_successQuantity;
@property(nonatomic) long long oldQuantity; // @synthesize oldQuantity=_oldQuantity;
@property(nonatomic) long long oldPrice; // @synthesize oldPrice=_oldPrice;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) BOOL isPriceTooFar;
@property(readonly, nonatomic) BOOL isTriggerPriceTooFar;
@property(readonly, nonatomic) BOOL isPriceInSpreads;
@property(readonly, nonatomic) BOOL isRequirePrice;
@property(readonly, nonatomic) BOOL isPending;
@property(readonly, nonatomic) BOOL isSuccess;
@property(readonly, nonatomic) BOOL isFailed;
@property(readonly, nonatomic) BOOL priceAdjustable;
@property(readonly, nonatomic) BOOL removable;
@property(readonly, nonatomic) BOOL cancelable;
@property(readonly, nonatomic) BOOL editable;
@property(readonly, nonatomic) NSString *triggerPriceString;
@property(readonly, nonatomic) NSString *oldPriceString;
- (long long)compareStatus:(id)arg1;
- (long long)compareDateDesc:(id)arg1;
- (long long)compareDateAsc:(id)arg1;
@property(readonly, nonatomic) NSString *successQuantityString;
- (id)updateStatus;
@property(readonly, nonatomic) NSString *typeText;
@property(readonly, nonatomic) NSString *directionString;
@property(readonly, nonatomic) int priceStep;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

