//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLNetIP, FLPingOperation;

@interface FLPingData : NSObject
{
    FLPingOperation *_pingOp;
    FLNetIP *_netIP;
}

@property(retain, nonatomic) FLNetIP *netIP; // @synthesize netIP=_netIP;
@property(retain, nonatomic) FLPingOperation *pingOp; // @synthesize pingOp=_pingOp;
- (void).cxx_destruct;
- (double)averageDuration;
- (void)stopPing;
- (void)setupPingOperation;

@end

