//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLLinkageStockItem.h>

@interface FLPlateStockItem : FLLinkageStockItem
{
    int _priceChangeRatio;
    unsigned int _highestPrice;
    unsigned int _lowestPrice;
    unsigned int _openPrice;
    unsigned int _turnoverRate;
    unsigned int _volumeRate;
    int _buySellRatio;
    int _eyRatio;
    unsigned int _peRatio;
    float _amplitude;
    long long _turnover;
    unsigned long long _volume;
    unsigned long long _marketValue;
    unsigned long long _riseLeaderStockID;
}

@property(nonatomic) unsigned long long riseLeaderStockID; // @synthesize riseLeaderStockID=_riseLeaderStockID;
@property(nonatomic) unsigned long long marketValue; // @synthesize marketValue=_marketValue;
@property(nonatomic) float amplitude; // @synthesize amplitude=_amplitude;
@property(nonatomic) unsigned int peRatio; // @synthesize peRatio=_peRatio;
@property(nonatomic) int eyRatio; // @synthesize eyRatio=_eyRatio;
@property(nonatomic) int buySellRatio; // @synthesize buySellRatio=_buySellRatio;
@property(nonatomic) unsigned int volumeRate; // @synthesize volumeRate=_volumeRate;
@property(nonatomic) unsigned int turnoverRate; // @synthesize turnoverRate=_turnoverRate;
@property(nonatomic) unsigned int openPrice; // @synthesize openPrice=_openPrice;
@property(nonatomic) unsigned int lowestPrice; // @synthesize lowestPrice=_lowestPrice;
@property(nonatomic) unsigned int highestPrice; // @synthesize highestPrice=_highestPrice;
@property(nonatomic) unsigned long long volume; // @synthesize volume=_volume;
@property(nonatomic) long long turnover; // @synthesize turnover=_turnover;
@property(nonatomic) int priceChangeRatio; // @synthesize priceChangeRatio=_priceChangeRatio;
@property(readonly, nonatomic) unsigned long long capital;

@end

