//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLPlateInfo : NSObject
{
    unsigned long long _plateID;
    unsigned long long _ownerSetID;
}

@property(nonatomic) unsigned long long ownerSetID; // @synthesize ownerSetID=_ownerSetID;
@property(nonatomic) unsigned long long plateID; // @synthesize plateID=_plateID;
- (id)description;

@end

