//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLPositionNoticeSetting : NSObject
{
    BOOL _repeat;
    BOOL _nearStrikeEnabled;
    BOOL _nearLastTradeDayEnabled;
    BOOL _positionLossEnabled;
    int _nearLastTradeDayCount;
    double _nearStrikePercent;
    double _positionLossPercent;
}

@property(nonatomic) double positionLossPercent; // @synthesize positionLossPercent=_positionLossPercent;
@property(nonatomic) BOOL positionLossEnabled; // @synthesize positionLossEnabled=_positionLossEnabled;
@property(nonatomic) int nearLastTradeDayCount; // @synthesize nearLastTradeDayCount=_nearLastTradeDayCount;
@property(nonatomic) BOOL nearLastTradeDayEnabled; // @synthesize nearLastTradeDayEnabled=_nearLastTradeDayEnabled;
@property(nonatomic) double nearStrikePercent; // @synthesize nearStrikePercent=_nearStrikePercent;
@property(nonatomic) BOOL nearStrikeEnabled; // @synthesize nearStrikeEnabled=_nearStrikeEnabled;
@property(nonatomic) BOOL repeat; // @synthesize repeat=_repeat;

@end

