//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseModel.h>

@class NSString;

@interface FLPosition : FLBaseModel
{
    long long _costPrice;
    NSString *_costPriceString;
    long long _value;
    long long _todayValue;
    long long _profit;
    long long _todayProfit;
    double _profitRate;
    NSString *_profitRateString;
    long long _quantityTradeable;
    long long _todayBuyQuantity;
    long long _todayBuyValue;
    long long _todayBuyAveragePrice;
    long long _todaySellQuantity;
    long long _todaySellValue;
    long long _todaySellAveragePrice;
}

@property(nonatomic) long long todaySellAveragePrice; // @synthesize todaySellAveragePrice=_todaySellAveragePrice;
@property(nonatomic) long long todaySellValue; // @synthesize todaySellValue=_todaySellValue;
@property(nonatomic) long long todaySellQuantity; // @synthesize todaySellQuantity=_todaySellQuantity;
@property(nonatomic) long long todayBuyAveragePrice; // @synthesize todayBuyAveragePrice=_todayBuyAveragePrice;
@property(nonatomic) long long todayBuyValue; // @synthesize todayBuyValue=_todayBuyValue;
@property(nonatomic) long long todayBuyQuantity; // @synthesize todayBuyQuantity=_todayBuyQuantity;
@property(nonatomic) long long quantityTradeable; // @synthesize quantityTradeable=_quantityTradeable;
@property(retain, nonatomic) NSString *profitRateString; // @synthesize profitRateString=_profitRateString;
@property(nonatomic) double profitRate; // @synthesize profitRate=_profitRate;
@property(nonatomic) long long todayProfit; // @synthesize todayProfit=_todayProfit;
@property(nonatomic) long long profit; // @synthesize profit=_profit;
@property(nonatomic) long long todayValue; // @synthesize todayValue=_todayValue;
@property(nonatomic) long long value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *costPriceString; // @synthesize costPriceString=_costPriceString;
@property(nonatomic) long long costPrice; // @synthesize costPrice=_costPrice;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) BOOL hasPositionMarkForStock;
@property(readonly, nonatomic) NSString *todaySell;
@property(readonly, nonatomic) NSString *todayBuy;
- (long long)compare:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@end

