//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSArray;

@interface FLPopularStocksManager : FLBaseManager
{
    NSArray *_cachedStocksList;
    double _lastRefreshTime;
}

+ (id)sharedInstance;
@property(nonatomic) double lastRefreshTime; // @synthesize lastRefreshTime=_lastRefreshTime;
@property(retain, nonatomic) NSArray *cachedStocksList; // @synthesize cachedStocksList=_cachedStocksList;
- (void).cxx_destruct;
- (void)forceToRefreshData;
- (void)refreshDataIfNeeded;
- (id)loadPopularStocksList;
- (void)saveStockList:(id)arg1;
- (void)loadCachedData;
- (id)init;

@end

