//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLPlateStocksFetcher, FLQuoteBasicData, FLStockNewsManager, FLVersionFileDataManager;
@protocol FLTradeTimeManager, OS_dispatch_queue;

@interface FLQuoteService : NSObject
{
    NSObject<OS_dispatch_queue> *_processQueue;
    FLQuoteBasicData *_quoteBasicData;
    FLStockNewsManager *_stockNewsManager;
    FLVersionFileDataManager *_exRightManager;
    FLPlateStocksFetcher *_plateStocksFetcher;
}

+ (Class)exRightManagerClass;
+ (id)quoteService;
@property(retain, nonatomic) FLPlateStocksFetcher *plateStocksFetcher; // @synthesize plateStocksFetcher=_plateStocksFetcher;
@property(retain, nonatomic) FLVersionFileDataManager *exRightManager; // @synthesize exRightManager=_exRightManager;
@property(retain, nonatomic) FLStockNewsManager *stockNewsManager; // @synthesize stockNewsManager=_stockNewsManager;
@property(retain) FLQuoteBasicData *quoteBasicData; // @synthesize quoteBasicData=_quoteBasicData;
- (void).cxx_destruct;
- (void)saveAllDataToFile;
- (void)cleanupAllLocalQuoteData:(BOOL)arg1;
- (void)cleanupLocalQuoteData;
- (void)cleanupLocalQuoteDataWithResultBlock:(CDUnknownBlockType)arg1;
- (void)cleanupLocalDataRoutine;
- (void)cleanupPlateFiles;
- (BOOL)cleanupKlineRelatedFiles;
- (void)cleanupLocalQuoteDataRoutine;
- (unsigned long long)localQuoteDataSize;
- (void)resetAllKlineData;
- (void)setupKlineRelatedManagers;
@property(readonly, nonatomic) id <FLTradeTimeManager> tradeTimeManager;
- (id)quoteProcessQueue;
- (void)onFLQuoteLatestTradeTimeDidChangedNotification:(id)arg1;
- (void)onLatestTradeTimeChangedNotification:(id)arg1;
- (void)onQuoteDidLogout:(id)arg1;
- (void)onQuoteDidLogin:(id)arg1;
- (void)dealloc;
- (id)init;

@end

