//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLQuantityOption : NSObject <NSCopying>
{
    BOOL _setting;
    NSString *_name;
    long long _quantity;
    NSString *_quantityString;
}

@property(nonatomic) BOOL setting; // @synthesize setting=_setting;
@property(retain, nonatomic) NSString *quantityString; // @synthesize quantityString=_quantityString;
@property(nonatomic) long long quantity; // @synthesize quantity=_quantity;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

