//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseHandler.h>

@interface FLQuoteHandler : FLBaseHandler
{
    int _lastStockListFetchTime;
}

+ (unsigned char)marketTypeForStock:(id)arg1;
- (id)dencryptBytes:(char *)arg1 length:(int)arg2 key:(char *)arg3;
- (id)encryptBytes:(char *)arg1 length:(int)arg2 key:(char *)arg3;
- (void)decodePacker:(struct ft_packer *)arg1;
- (void)analyzeWithReceivedCommand:(unsigned short)arg1 bodyLength:(unsigned int)arg2;
- (void)messageDecode:(struct ft_packer *)arg1;
- (void)getQuoteDataVersionDecode:(struct util_byteios_net *)arg1;
- (void)getQuoteDataVersion;
- (void)globalInfoDispatchMarketStatus:(id)arg1 push:(BOOL)arg2;
- (void)globalInfoDecode:(struct util_byteios_net *)arg1 push:(BOOL)arg2;
- (void)globalInfoGetStateForMarketType:(unsigned char)arg1;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)disconnectWithoutStatusFeedback;
- (void)keyUpdate;
- (void)keepAliveWithTimeout:(unsigned int)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)registerInfoPushForType:(unsigned char)arg1;
- (void)userDidLogined;
- (void)userLoginDecode:(struct util_byteios_net *)arg1;
- (void)userStartLogin;
- (void)guestLoginDecode:(struct util_byteios_net *)arg1;
- (void)guestStartLogin;
- (void)startAuthenticiateClientSigAndClientKey;
- (id)initWithQueue:(id)arg1;

@end

