//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSArray, NSString;

@interface FLRecommendedStockPageModel : FTCodingModel
{
    NSString *_simplifyTitle;
    NSString *_traditionalTitle;
    NSArray *_recommendedStocks;
}

+ (id)decodeListFromArray:(id)arg1;
@property(retain, nonatomic) NSArray *recommendedStocks; // @synthesize recommendedStocks=_recommendedStocks;
@property(copy, nonatomic) NSString *traditionalTitle; // @synthesize traditionalTitle=_traditionalTitle;
@property(copy, nonatomic) NSString *simplifyTitle; // @synthesize simplifyTitle=_simplifyTitle;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *title;
- (void)decodeFromDictionary:(id)arg1;

@end

