//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLReportModel, NSString, NSTimer;
@protocol FLReportProtocol, OS_dispatch_queue;

@interface FLReportManager : NSObject
{
    NSString *_devName;
    NSString *_osType;
    id <FLReportProtocol> _delegate;
    FLReportModel *_reportModel;
    NSObject<OS_dispatch_queue> *_reportQueue;
    double _sessionFirstForegroundTime;
    double _sessionLastForeGroundTime;
    double _sessionLastBackGroundTime;
    double _sesstionDuration;
    double _sesstionTimes;
    NSTimer *_timer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) double sesstionTimes; // @synthesize sesstionTimes=_sesstionTimes;
@property(nonatomic) double sesstionDuration; // @synthesize sesstionDuration=_sesstionDuration;
@property(nonatomic) double sessionLastBackGroundTime; // @synthesize sessionLastBackGroundTime=_sessionLastBackGroundTime;
@property(nonatomic) double sessionLastForeGroundTime; // @synthesize sessionLastForeGroundTime=_sessionLastForeGroundTime;
@property(nonatomic) double sessionFirstForegroundTime; // @synthesize sessionFirstForegroundTime=_sessionFirstForegroundTime;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *reportQueue; // @synthesize reportQueue=_reportQueue;
@property(retain, nonatomic) FLReportModel *reportModel; // @synthesize reportModel=_reportModel;
@property(nonatomic) __weak id <FLReportProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *osType; // @synthesize osType=_osType;
@property(retain, nonatomic) NSString *devName; // @synthesize devName=_devName;
- (void).cxx_destruct;
- (id)currentNetType;
- (void)reportImageDownloadWithUrl:(id)arg1 result:(int)arg2 costTime:(double)arg3 fileSize:(unsigned long long)arg4;
- (void)reportImageUploadResult:(int)arg1 costTime:(double)arg2 fileSize:(unsigned long long)arg3 module:(id)arg4;
- (void)checkToAddDailyReportInfo;
- (void)reportLoginResult;
- (void)reportAppFirstLaunch;
- (void)reportDeviceInfo;
- (void)reportSessionWithDuration:(double)arg1 times:(unsigned long long)arg2;
- (void)reportUserSettings;
- (void)reportUserSettingsWithEventId:(id)arg1 value:(int)arg2;
- (void)reportUserSettingsWithEventId:(id)arg1 value:(int)arg2 ext1:(id)arg3 ext2:(id)arg4 ext3:(id)arg5 ext4:(id)arg6;
- (void)reportExposureEventWithEventId:(id)arg1 beginTime:(double)arg2 duration:(double)arg3;
- (void)reportExposureEventWithEventId:(id)arg1 beginTime:(double)arg2 duration:(double)arg3 ext1:(id)arg4 ext2:(id)arg5 ext3:(id)arg6 ext4:(id)arg7;
- (void)reportClickEventWithEventId:(id)arg1 extensions:(id)arg2;
- (void)reportClickEventWithEventId:(id)arg1;
- (void)reportClickEventWithEventId:(id)arg1 ext1:(id)arg2 ext2:(id)arg3 ext3:(id)arg4 ext4:(id)arg5;
- (void)reportNetDisconnectWithHost:(id)arg1 reason:(int)arg2 time:(double)arg3 code:(int)arg4;
- (void)reportUserProcessWithHost:(id)arg1 result:(int)arg2 startTime:(double)arg3 dataCostTime:(double)arg4 count:(int)arg5 type:(id)arg6;
- (void)reportUserLoginProcessWithHost:(id)arg1 result:(int)arg2 startTime:(double)arg3 dataCostTime:(double)arg4 count:(int)arg5;
- (void)reportUserAuthProcessWithHost:(id)arg1 result:(int)arg2 startTime:(double)arg3 dataCostTime:(double)arg4 count:(int)arg5;
- (void)reportUserConnWithHost:(id)arg1 result:(int)arg2 startTime:(double)arg3 connCostTime:(double)arg4 dataCostTime:(double)arg5 type:(id)arg6;
- (void)reportUserAuthConnWithHost:(id)arg1 result:(int)arg2 startTime:(double)arg3 connCostTime:(double)arg4 dataCostTime:(double)arg5;
- (void)reportUserLoginConnWithHost:(id)arg1 result:(int)arg2 startTime:(double)arg3 connCostTime:(double)arg4 dataCostTime:(double)arg5;
- (void)reportNetConnectionWithHost:(id)arg1 result:(int)arg2 costTime:(double)arg3;
- (void)reportServerRequestWithCmd:(int)arg1 ipAddress:(id)arg2 result:(int)arg3 costTime:(double)arg4;
- (void)reportWebAPIWithUrl:(id)arg1 result:(int)arg2 businessCode:(int)arg3 costTime:(double)arg4;
- (void)handleNotify:(id)arg1;
- (void)checkAndReportInfo:(BOOL)arg1;
- (void)checkAndReport;
- (void)addReportInfo:(id)arg1 reportNow:(BOOL)arg2;
- (void)addReportInfo:(id)arg1;
- (void)deleteCachedReportInfo;
- (void)loadReportInfo;
- (void)saveReportInfo;
- (id)cacheFilePath;
- (id)init;
- (void)dealloc;

@end

