//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@interface FLRecommendFilterStrategyRequestModel : FTCodingModel <NSCopying>
{
    unsigned int _marketType;
}

+ (id)requestWithMarketType:(unsigned int)arg1;
@property(nonatomic) unsigned int marketType; // @synthesize marketType=_marketType;
- (unsigned char)reqMarketType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;
- (id)initWithMarketType:(unsigned int)arg1;

@end

