//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@interface FLRecommendedStockModel : FTCodingModel
{
    BOOL _hasSelected;
    unsigned long long _stockID;
}

@property(nonatomic) BOOL hasSelected; // @synthesize hasSelected=_hasSelected;
@property(nonatomic) unsigned long long stockID; // @synthesize stockID=_stockID;
- (void)decodeFromDictionary:(id)arg1;

@end

