//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSTimer;

@interface FLSendTaskManager : NSObject
{
    NSTimer *_timer;
    NSMutableArray *_taskList;
    unsigned long long _currentUserId;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned long long currentUserId; // @synthesize currentUserId=_currentUserId;
@property(retain, nonatomic) NSMutableArray *taskList; // @synthesize taskList=_taskList;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (id)sendBoxArchiveFileNameWithUserId:(unsigned long long)arg1;
- (void)loadTaskList;
- (void)saveTaskList;
- (void)removeSendTask:(id)arg1;
- (void)addSendTask:(id)arg1;
- (void)checkSendTaskToStart;
- (void)onTimer:(id)arg1;
- (void)loadDataWithUserId:(unsigned long long)arg1;
- (id)init;
- (void)dealloc;

@end

