//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FLSearchFieldInfoModel : NSObject
{
    BOOL _needSearchPinYin;
    unsigned int _hitType;
    NSString *_field;
}

+ (id)createSearchFieldInfoModelWithField:(id)arg1 hitType:(unsigned int)arg2 needSearchPinYin:(BOOL)arg3;
@property(nonatomic) unsigned int hitType; // @synthesize hitType=_hitType;
@property(nonatomic) BOOL needSearchPinYin; // @synthesize needSearchPinYin=_needSearchPinYin;
@property(retain, nonatomic) NSString *field; // @synthesize field=_field;
- (void).cxx_destruct;

@end

