//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLSharedPostDataModel : FTCodingModel
{
    BOOL _isGuest;
    unsigned short _sharedContentType;
    unsigned short _sharedType;
    int _sharedResult;
    NSString *_userId;
    double _timeStamp;
    NSString *_sharedTitle;
}

@property(nonatomic) int sharedResult; // @synthesize sharedResult=_sharedResult;
@property(nonatomic) unsigned short sharedType; // @synthesize sharedType=_sharedType;
@property(copy, nonatomic) NSString *sharedTitle; // @synthesize sharedTitle=_sharedTitle;
@property(nonatomic) unsigned short sharedContentType; // @synthesize sharedContentType=_sharedContentType;
@property(nonatomic) double timeStamp; // @synthesize timeStamp=_timeStamp;
@property(nonatomic) BOOL isGuest; // @synthesize isGuest=_isGuest;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;

@end

