//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLStock;

@interface FLShortTermTicker : NSObject
{
    unsigned int _time;
    unsigned int _volume;
    unsigned int _tickerType;
    unsigned int _actionType;
    unsigned int _valueType;
    FLStock *_stock;
    unsigned long long _tickerKey;
    long long _lastClosePrice;
    long long _price;
}

@property(nonatomic) unsigned int valueType; // @synthesize valueType=_valueType;
@property(nonatomic) unsigned int actionType; // @synthesize actionType=_actionType;
@property(nonatomic) unsigned int tickerType; // @synthesize tickerType=_tickerType;
@property(nonatomic) unsigned int volume; // @synthesize volume=_volume;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(nonatomic) long long lastClosePrice; // @synthesize lastClosePrice=_lastClosePrice;
@property(nonatomic) unsigned int time; // @synthesize time=_time;
@property(nonatomic) unsigned long long tickerKey; // @synthesize tickerKey=_tickerKey;
@property(nonatomic) __weak FLStock *stock; // @synthesize stock=_stock;
- (void).cxx_destruct;
- (id)valueString;
- (id)description;
- (id)timeString;

@end

