//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLStock;
@protocol FLShortTickerSubscriber;

@interface FLShortTickerSubscribeInfo : NSObject
{
    BOOL _watchedOnly;
    unsigned int _shortTickerType;
    id <FLShortTickerSubscriber> _subsciber;
    FLStock *_stock;
}

@property(nonatomic) BOOL watchedOnly; // @synthesize watchedOnly=_watchedOnly;
@property(nonatomic) unsigned int shortTickerType; // @synthesize shortTickerType=_shortTickerType;
@property(retain, nonatomic) FLStock *stock; // @synthesize stock=_stock;
@property(nonatomic) __weak id <FLShortTickerSubscriber> subsciber; // @synthesize subsciber=_subsciber;
- (void).cxx_destruct;

@end

