//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GCDAsyncSocket, MSWeakTimer, NSData, NSMutableDictionary, NSString;
@protocol FLShortConnectionTaskDelegate, OS_dispatch_queue;

@interface FLShortConnectionTask : NSObject
{
    NSData *_remainData;
    unsigned int _checkTime;
    unsigned int _checkDuration;
    BOOL _redirected;
    unsigned short _port;
    unsigned int _redirectCommand;
    unsigned int _serialNumber;
    NSString *_name;
    NSString *_server;
    GCDAsyncSocket *_socket;
    FLShortConnectionTask *_nextTask;
    id <FLShortConnectionTaskDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    MSWeakTimer *_checkTimer;
    NSMutableDictionary *_commands;
}

@property(retain, nonatomic) NSMutableDictionary *commands; // @synthesize commands=_commands;
@property unsigned int serialNumber; // @synthesize serialNumber=_serialNumber;
@property(retain, nonatomic) MSWeakTimer *checkTimer; // @synthesize checkTimer=_checkTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) BOOL redirected; // @synthesize redirected=_redirected;
@property(nonatomic) __weak id <FLShortConnectionTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int redirectCommand; // @synthesize redirectCommand=_redirectCommand;
@property(retain, nonatomic) FLShortConnectionTask *nextTask; // @synthesize nextTask=_nextTask;
@property(retain, nonatomic) GCDAsyncSocket *socket; // @synthesize socket=_socket;
@property(nonatomic) unsigned short port; // @synthesize port=_port;
@property(retain, nonatomic) NSString *server; // @synthesize server=_server;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)checkTimeOutCommands;
- (void)writeWithCommand:(id)arg1 packerBlock:(CDUnknownBlockType)arg2;
- (void)writeWithCommand:(unsigned short)arg1 timeOutInterval:(unsigned int)arg2 packerBlock:(CDUnknownBlockType)arg3 responseBlock:(CDUnknownBlockType)arg4;
- (void)writeCommand:(unsigned short)arg1 packerBlock:(CDUnknownBlockType)arg2;
- (unsigned int)_decodePacker:(struct ft_packer *)arg1 data:(char *)arg2 len:(unsigned int)arg3;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)decodeRedirectPacker:(struct ft_packer *)arg1;
- (void)decodePacker:(struct ft_packer *)arg1;
- (void)startSending;
- (void)finish;
- (void)checkTask;
- (void)connect;
- (void)onRecvCurrentProxyContextInfoChangedNotification:(id)arg1;
- (void)start;
- (void)dealloc;
- (id)init;

@end

