//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLSNSSettings : NSObject
{
}

+ (id)loadObjectFromFile:(id)arg1;
+ (void)archiveObject:(id)arg1 toFile:(id)arg2;
+ (id)filePathWithFileName:(id)arg1;
+ (id)getMutableDicForKey:(id)arg1;
+ (id)getDicForKey:(id)arg1;
+ (void)setDic:(id)arg1 forKey:(id)arg2;
+ (id)getArrayForKey:(id)arg1;
+ (void)setArray:(id)arg1 forTheKey:(id)arg2;
+ (id)SNSSettingsPathForKey:(id)arg1;
+ (void)createPath:(id)arg1;
+ (id)userSNSDocPath:(unsigned long long)arg1;

@end

