//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLSNSUtil : NSObject
{
}

+ (void)mainThreadPostNotification:(id)arg1 object:(id)arg2 resultInfo:(id)arg3;
+ (void)setPhoneNumForF3CNN:(id)arg1;
+ (id)getFTNNTextViewElemList:(id)arg1 params:(id)arg2 textElemHandler:(CDUnknownBlockType)arg3 faceElemHandler:(CDUnknownBlockType)arg4 stockElemHandler:(CDUnknownBlockType)arg5 atElemHandler:(CDUnknownBlockType)arg6 imageElemHandler:(CDUnknownBlockType)arg7 titleElemHandler:(CDUnknownBlockType)arg8;
+ (id)roomChatDetailText;
+ (id)newFriendDetailText:(id)arg1;
+ (unsigned int)getMsgTimestampFromMsgId:(id)arg1;
+ (unsigned int)getMsgSeqFromMsgId:(id)arg1;
+ (void)setMyBasicInfo:(id)arg1;
+ (id)commissionInfoStringOfSubAccountCardNumber:(id)arg1;
+ (id)getMyBasicInfo;
+ (id)myBasicInfoKey;
+ (void)setMySNSInfo:(id)arg1;
+ (id)getMySNSInfo;
+ (id)mySNSInfoKey;
+ (int)getSNSStockMarketTypeByMarket:(id)arg1;
+ (id)getSNSStockMarketByType:(int)arg1;
+ (int)stockMarketSNSTypeForMarketID:(unsigned char)arg1;
+ (id)getMsgIdByTimestamp:(unsigned int)arg1 andSeq:(unsigned int)arg2;
+ (id)getDateFromString:(id)arg1;
+ (id)getPlatformFromResource:(id)arg1;
+ (double)getSNSSvrTimeInterval;
+ (unsigned int)getSendMsgSequence;
+ (unsigned long long)generateClientKey;
+ (int)getRequestId;

@end

