//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface FLSpreadsManager : NSObject
{
    NSDictionary *_spreads;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)saveSpreadsToLocal:(id)arg1;
- (id)localCachePath;
- (void)setAndSaveSpreads:(id)arg1;
- (void)initDataFromLocalPath:(id)arg1;
@property(retain, nonatomic) NSDictionary *spreads;

@end

