//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLShortConnectionTask.h>

@protocol FLStockListDownloadTaskDelegate;

@interface FLStockListDownloadTask : FLShortConnectionTask
{
    unsigned long long _clientSequence;
    unsigned long long _sumOfID;
    unsigned long long _sumOfSequence;
}

@property(nonatomic) unsigned long long sumOfSequence; // @synthesize sumOfSequence=_sumOfSequence;
@property(nonatomic) unsigned long long sumOfID; // @synthesize sumOfID=_sumOfID;
@property(nonatomic) unsigned long long clientSequence; // @synthesize clientSequence=_clientSequence;
- (void)fetchStockListDecode:(struct clt_crypt_codec_clt_side *)arg1;
- (void)fetchStockList;
- (void)decodePacker:(struct ft_packer *)arg1;
- (void)startSending;
- (void)finish;
- (id)init;

// Remaining properties
@property(nonatomic) __weak id <FLStockListDownloadTaskDelegate> delegate; // @dynamic delegate;

@end

