//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@interface FLStockWikiManager : FLBaseManager
{
}

- (id)stockWikiModelOfPbModel:(struct StockWiki)arg1;
- (BOOL)fetchStockWikiInfoWithStockId:(unsigned long long)arg1 stockCode:(id)arg2 marketId:(unsigned int)arg3 response:(CDUnknownBlockType)arg4;

@end

