//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString;

@interface FLStockNewsItem : NSObject
{
    BOOL _isOutLink;
    unsigned int _itemID;
    unsigned int _time;
    NSDate *_date;
    NSString *_title;
    NSString *_strURL;
    NSString *_strSymbolForNews;
    long long _clientType;
    long long _skinType;
    unsigned long long _stockMarketType;
    NSString *_strURLWithRelatedStockHidden;
    NSArray *_arySymbol;
    NSString *_url;
}

@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSArray *arySymbol; // @synthesize arySymbol=_arySymbol;
@property(readonly, nonatomic) NSString *strURLWithRelatedStockHidden; // @synthesize strURLWithRelatedStockHidden=_strURLWithRelatedStockHidden;
@property(nonatomic) unsigned long long stockMarketType; // @synthesize stockMarketType=_stockMarketType;
@property(nonatomic) BOOL isOutLink; // @synthesize isOutLink=_isOutLink;
@property(nonatomic) long long skinType; // @synthesize skinType=_skinType;
@property(nonatomic) long long clientType; // @synthesize clientType=_clientType;
@property(copy, nonatomic) NSString *strSymbolForNews; // @synthesize strSymbolForNews=_strSymbolForNews;
@property(copy, nonatomic) NSString *strURL; // @synthesize strURL=_strURL;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) unsigned int time; // @synthesize time=_time;
@property(nonatomic) unsigned int itemID; // @synthesize itemID=_itemID;
- (void).cxx_destruct;
- (id)description;

@end

