//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSDate, NSString;

@interface FLStockNewsModel : FTCodingModel
{
    BOOL _isOuterLink;
    unsigned int _stockNewsId;
    int _stockNewsType;
    unsigned int _publishTime;
    NSString *_title;
    NSString *_url;
}

@property(nonatomic) BOOL isOuterLink; // @synthesize isOuterLink=_isOuterLink;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned int publishTime; // @synthesize publishTime=_publishTime;
@property(nonatomic) int stockNewsType; // @synthesize stockNewsType=_stockNewsType;
@property(nonatomic) unsigned int stockNewsId; // @synthesize stockNewsId=_stockNewsId;
- (void).cxx_destruct;
- (id)description;
- (id)initWithNewsId:(unsigned int)arg1 newsType:(int)arg2 publishTime:(unsigned int)arg3 title:(id)arg4 url:(id)arg5 bitFlag:(unsigned int)arg6;
@property(readonly, nonatomic) NSDate *date;

@end

