//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLSearchProtocol-Protocol.h>
#import <FTEngine/FLStockObject-Protocol.h>
#import <FTEngine/NSCoding-Protocol.h>
#import <FTEngine/NSCopying-Protocol.h>

@class FLCASReferencePrice, FLHandicapData, FLLinkageItem, FLOrderQueueStatement, FLStockExtremum, FLStockSimple, FLUOptionStaticInfo, FLVCMTrigger, NSArray, NSString;

@interface FLStock : NSObject <FLSearchProtocol, NSCopying, NSCoding, FLStockObject>
{
    unsigned char _marketID;
    BOOL _delisted;
    BOOL _delisting;
    BOOL _hasPosition;
    BOOL _noSearch;
    BOOL _noSubscription;
    unsigned short _spreadKey;
    unsigned short _raiseCount;
    unsigned short _fallCount;
    unsigned short _parityCount;
    unsigned int _listingTime;
    int _stockType;
    unsigned int _unit;
    int _hotDegree;
    int _change;
    float _percent;
    unsigned int _currentPriceUpdateTime;
    int _watchIndex;
    int _warrantType;
    int _suspendStatus;
    unsigned int _plateType;
    unsigned int _continuentStockCount;
    unsigned int _casFlag;
    unsigned int _vcmFlag;
    unsigned int _marginFlag;
    unsigned int _shortSellRefRatio;
    unsigned int _shortSellFlag;
    unsigned int _simpleSequence;
    unsigned long long _ID;
    unsigned long long _stockMarketType;
    NSString *_code;
    NSString *_englishName;
    NSString *_simplifiedName;
    NSString *_traditionalName;
    NSString *_keyword;
    NSString *_shortPinYin;
    unsigned long long _lastClosePrice;
    unsigned long long _price;
    NSString *_percentString;
    NSString *_name;
    unsigned long long _serverSequence;
    unsigned long long _underlineID;
    NSString *_plateIDs;
    FLStockSimple *_simple;
    FLStockExtremum *_extremum;
    FLLinkageItem *_linkageItem;
    unsigned long long _linkageID;
    unsigned long long _circulationValue;
    unsigned long long _circulatingCapital;
    NSArray *_tickers;
    unsigned long long _tickerNextKey;
    unsigned long long _tickerCurrentFetchingKey;
    FLHandicapData *_spriteData;
    FLHandicapData *_issuerData;
    FLCASReferencePrice *_casReferencePrice;
    FLVCMTrigger *_vcmTrigger;
    FLOrderQueueStatement *_orderQueueStatement;
    FLUOptionStaticInfo *_usOptionInfo;
}

+ (BOOL)isUSOptionID:(id)arg1;
+ (BOOL)isUSOptionCode:(id)arg1;
@property(retain, nonatomic) FLUOptionStaticInfo *usOptionInfo; // @synthesize usOptionInfo=_usOptionInfo;
@property(nonatomic) unsigned int simpleSequence; // @synthesize simpleSequence=_simpleSequence;
@property(retain, nonatomic) FLOrderQueueStatement *orderQueueStatement; // @synthesize orderQueueStatement=_orderQueueStatement;
@property(nonatomic) unsigned int shortSellFlag; // @synthesize shortSellFlag=_shortSellFlag;
@property(nonatomic) unsigned int shortSellRefRatio; // @synthesize shortSellRefRatio=_shortSellRefRatio;
@property(nonatomic) unsigned int marginFlag; // @synthesize marginFlag=_marginFlag;
@property(retain, nonatomic) FLVCMTrigger *vcmTrigger; // @synthesize vcmTrigger=_vcmTrigger;
@property(retain, nonatomic) FLCASReferencePrice *casReferencePrice; // @synthesize casReferencePrice=_casReferencePrice;
@property(nonatomic) unsigned int vcmFlag; // @synthesize vcmFlag=_vcmFlag;
@property(nonatomic) unsigned int casFlag; // @synthesize casFlag=_casFlag;
@property(nonatomic) BOOL noSubscription; // @synthesize noSubscription=_noSubscription;
@property(nonatomic) BOOL noSearch; // @synthesize noSearch=_noSearch;
@property(nonatomic) unsigned int continuentStockCount; // @synthesize continuentStockCount=_continuentStockCount;
@property(nonatomic) unsigned int plateType; // @synthesize plateType=_plateType;
@property(nonatomic) int suspendStatus; // @synthesize suspendStatus=_suspendStatus;
@property(nonatomic) BOOL hasPosition; // @synthesize hasPosition=_hasPosition;
@property(nonatomic) unsigned short parityCount; // @synthesize parityCount=_parityCount;
@property(nonatomic) unsigned short fallCount; // @synthesize fallCount=_fallCount;
@property(nonatomic) unsigned short raiseCount; // @synthesize raiseCount=_raiseCount;
@property(retain, nonatomic) FLHandicapData *issuerData; // @synthesize issuerData=_issuerData;
@property(retain, nonatomic) FLHandicapData *spriteData; // @synthesize spriteData=_spriteData;
@property(nonatomic) unsigned long long tickerCurrentFetchingKey; // @synthesize tickerCurrentFetchingKey=_tickerCurrentFetchingKey;
@property(nonatomic) unsigned long long tickerNextKey; // @synthesize tickerNextKey=_tickerNextKey;
@property(retain) NSArray *tickers; // @synthesize tickers=_tickers;
@property(nonatomic) unsigned long long circulatingCapital; // @synthesize circulatingCapital=_circulatingCapital;
@property(nonatomic) unsigned long long circulationValue; // @synthesize circulationValue=_circulationValue;
@property(nonatomic) unsigned long long linkageID; // @synthesize linkageID=_linkageID;
@property(retain, nonatomic) FLLinkageItem *linkageItem; // @synthesize linkageItem=_linkageItem;
@property(retain) FLStockExtremum *extremum; // @synthesize extremum=_extremum;
@property(retain) FLStockSimple *simple; // @synthesize simple=_simple;
@property(nonatomic) int warrantType; // @synthesize warrantType=_warrantType;
@property(retain, nonatomic) NSString *plateIDs; // @synthesize plateIDs=_plateIDs;
@property(nonatomic) unsigned long long underlineID; // @synthesize underlineID=_underlineID;
@property(nonatomic) unsigned long long serverSequence; // @synthesize serverSequence=_serverSequence;
@property(nonatomic) BOOL delisting; // @synthesize delisting=_delisting;
@property(nonatomic) BOOL delisted; // @synthesize delisted=_delisted;
@property(nonatomic) int watchIndex; // @synthesize watchIndex=_watchIndex;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned int currentPriceUpdateTime; // @synthesize currentPriceUpdateTime=_currentPriceUpdateTime;
@property(retain, nonatomic) NSString *percentString; // @synthesize percentString=_percentString;
@property(nonatomic) float percent; // @synthesize percent=_percent;
@property(nonatomic) int change; // @synthesize change=_change;
@property(nonatomic) unsigned long long price; // @synthesize price=_price;
@property(nonatomic) unsigned long long lastClosePrice; // @synthesize lastClosePrice=_lastClosePrice;
@property(nonatomic) int hotDegree; // @synthesize hotDegree=_hotDegree;
@property(retain, nonatomic) NSString *shortPinYin; // @synthesize shortPinYin=_shortPinYin;
@property(nonatomic) unsigned short spreadKey; // @synthesize spreadKey=_spreadKey;
@property(retain, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(nonatomic) unsigned int unit; // @synthesize unit=_unit;
@property(retain, nonatomic) NSString *traditionalName; // @synthesize traditionalName=_traditionalName;
@property(retain, nonatomic) NSString *simplifiedName; // @synthesize simplifiedName=_simplifiedName;
@property(retain, nonatomic) NSString *englishName; // @synthesize englishName=_englishName;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) unsigned long long stockMarketType; // @synthesize stockMarketType=_stockMarketType;
@property(nonatomic) int stockType; // @synthesize stockType=_stockType;
@property(nonatomic) unsigned int listingTime; // @synthesize listingTime=_listingTime;
@property(nonatomic) unsigned char marketID; // @synthesize marketID=_marketID;
@property(nonatomic) unsigned long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (BOOL)isUSOptionValid;
- (BOOL)isUSOption;
- (long long)tradeQuantityForQuantity:(long long)arg1 percent:(long long)arg2 increase:(BOOL)arg3;
- (int)priceStepForPrice:(unsigned long long)arg1 increase:(BOOL)arg2;
@property(readonly, nonatomic) BOOL supportShortSell;
@property(readonly, nonatomic) unsigned int marginRatio;
@property(readonly, nonatomic) BOOL supportMargin;
@property(readonly, nonatomic) BOOL supportVCM;
@property(readonly, nonatomic) BOOL supportCAS;
- (void)updateSimpleSequence;
- (void)decodeWebDic:(id)arg1;
- (void)createSimpleIfNeeded;
@property(readonly, nonatomic) BOOL suspended;
@property(readonly, nonatomic) BOOL isPriceNoticable;
@property(readonly, nonatomic) BOOL isWatchable;
@property(readonly, nonatomic) BOOL isTradable;
@property(readonly, nonatomic) BOOL isHengShengIndex;
@property(readonly, nonatomic) BOOL isHKContinueFuture;
@property(readonly, nonatomic) BOOL isHKFuture;
- (void)updatePercent;
@property(readonly, nonatomic) NSString *warrantTypeString;
- (long long)compare:(id)arg1;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *displayContent;
@property(readonly, copy) NSString *description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) NSString *symbol;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)searchFieldsInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

