//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLShortConnectionTaskDelegate-Protocol.h>

@class FLStock, FLStockListDownloadTask, NSArray;

@protocol FLStockListDownloadTaskDelegate <FLShortConnectionTaskDelegate>

@optional
- (void)stockListDownloadTask:(FLStockListDownloadTask *)arg1 shouldUpdateStocks:(NSArray *)arg2 deleteStockIDs:(NSArray *)arg3;
- (FLStock *)stockListDownloadTask:(FLStockListDownloadTask *)arg1 stockForID:(unsigned long long)arg2;
- (void)stockListDownloadTaskDidFinish;
@end

