//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLFilterModel.h>

@class FLStock, NSString;

@interface FLStockFilterModel : FLFilterModel
{
    BOOL _supportMargin;
    BOOL _supportShortSell;
    unsigned int _currentPrice;
    unsigned int _lastClosePrice;
    unsigned int _buyPrice;
    unsigned int _sellPrice;
    unsigned int _open;
    unsigned int _high;
    unsigned int _low;
    unsigned int _turnoverRate;
    unsigned int _priceEarningsRatio;
    int _ascDscRate;
    unsigned int _amplitude;
    unsigned int _quantityRelativeRatio;
    int _commissionRatio;
    unsigned int _marginRatio;
    unsigned int _shortSellFeeRatio;
    unsigned long long _buyingVolume;
    unsigned long long _sellingVolume;
    unsigned long long _volume;
    unsigned long long _turnover;
    unsigned long long _marketValue;
    FLStock *_stock;
}

+ (id)modelWithProtoBufferModel:(struct StockCondition_Item *)arg1;
@property(retain, nonatomic) FLStock *stock; // @synthesize stock=_stock;
@property(nonatomic) unsigned int shortSellFeeRatio; // @synthesize shortSellFeeRatio=_shortSellFeeRatio;
@property(nonatomic) unsigned int marginRatio; // @synthesize marginRatio=_marginRatio;
@property(nonatomic) BOOL supportShortSell; // @synthesize supportShortSell=_supportShortSell;
@property(nonatomic) BOOL supportMargin; // @synthesize supportMargin=_supportMargin;
@property(nonatomic) int commissionRatio; // @synthesize commissionRatio=_commissionRatio;
@property(nonatomic) unsigned int quantityRelativeRatio; // @synthesize quantityRelativeRatio=_quantityRelativeRatio;
@property(nonatomic) unsigned long long marketValue; // @synthesize marketValue=_marketValue;
@property(nonatomic) unsigned int amplitude; // @synthesize amplitude=_amplitude;
@property(nonatomic) int ascDscRate; // @synthesize ascDscRate=_ascDscRate;
@property(nonatomic) unsigned int priceEarningsRatio; // @synthesize priceEarningsRatio=_priceEarningsRatio;
@property(nonatomic) unsigned int turnoverRate; // @synthesize turnoverRate=_turnoverRate;
@property(nonatomic) unsigned int low; // @synthesize low=_low;
@property(nonatomic) unsigned int high; // @synthesize high=_high;
@property(nonatomic) unsigned int open; // @synthesize open=_open;
@property(nonatomic) unsigned long long turnover; // @synthesize turnover=_turnover;
@property(nonatomic) unsigned long long volume; // @synthesize volume=_volume;
@property(nonatomic) unsigned long long sellingVolume; // @synthesize sellingVolume=_sellingVolume;
@property(nonatomic) unsigned long long buyingVolume; // @synthesize buyingVolume=_buyingVolume;
@property(nonatomic) unsigned int sellPrice; // @synthesize sellPrice=_sellPrice;
@property(nonatomic) unsigned int buyPrice; // @synthesize buyPrice=_buyPrice;
@property(nonatomic) unsigned int lastClosePrice; // @synthesize lastClosePrice=_lastClosePrice;
@property(nonatomic) unsigned int currentPrice; // @synthesize currentPrice=_currentPrice;
- (void).cxx_destruct;
- (id)description;
@property(readonly, copy, nonatomic) NSString *negativeSymbol;
@property(readonly, nonatomic) BOOL negative;
- (id)code;
@property(readonly, nonatomic) int priceChangeRate;
@property(readonly, nonatomic) int priceChangeValue;

@end

