//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol FLStockAdapterDataSource;

@interface FLStockAdapter : NSObject
{
    Class _adapterClass;
}

@property(nonatomic) Class adapterClass; // @synthesize adapterClass=_adapterClass;
@property(readonly, nonatomic) __weak id <FLStockAdapterDataSource> adapterDataSource;
- (id)encodeDictionaryFromAdapterObject:(id)arg1;
- (id)adapterObjectFromEncodeDictionary:(id)arg1;
- (id)initWithAdapterClass:(Class)arg1;

@end

