//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLStockObject.h>

@class NSArray;

@interface FLStockOwnerPlateInfo : FLStockObject
{
    NSArray *_stockPlateInfoList;
}

@property(retain, nonatomic) NSArray *stockPlateInfoList; // @synthesize stockPlateInfoList=_stockPlateInfoList;
- (void).cxx_destruct;
- (id)description;

@end

