//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSSet, NSString;

@interface FLStockNote : NSObject
{
    unsigned long long _ID;
    NSString *_title;
    NSDate *_createdAt;
    NSDate *_modifiedAt;
    NSDate *_stickTo;
    unsigned long long _stockID;
    NSSet *_relatedStockIDs;
    NSArray *_elements;
}

@property(retain, nonatomic) NSArray *elements; // @synthesize elements=_elements;
@property(retain, nonatomic) NSSet *relatedStockIDs; // @synthesize relatedStockIDs=_relatedStockIDs;
@property(nonatomic) unsigned long long stockID; // @synthesize stockID=_stockID;
@property(retain, nonatomic) NSDate *stickTo; // @synthesize stickTo=_stickTo;
@property(retain, nonatomic) NSDate *modifiedAt; // @synthesize modifiedAt=_modifiedAt;
@property(retain, nonatomic) NSDate *createdAt; // @synthesize createdAt=_createdAt;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (BOOL)decodePBData:(id)arg1;
- (id)encodedPBData;

@end

