//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface FLStockNewsData : NSObject
{
    unsigned int _updatedTime;
    unsigned int _accessTime;
    unsigned long long _stockID;
    NSString *_stockCode;
    unsigned long long _stockMarketType;
    NSString *_strSymbolForNews;
    NSArray *_aryNewsItem;
}

@property(nonatomic) unsigned int accessTime; // @synthesize accessTime=_accessTime;
@property(nonatomic) unsigned int updatedTime; // @synthesize updatedTime=_updatedTime;
@property(retain, nonatomic) NSArray *aryNewsItem; // @synthesize aryNewsItem=_aryNewsItem;
@property(copy, nonatomic) NSString *strSymbolForNews; // @synthesize strSymbolForNews=_strSymbolForNews;
@property(nonatomic) unsigned long long stockMarketType; // @synthesize stockMarketType=_stockMarketType;
@property(retain, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
@property(nonatomic) unsigned long long stockID; // @synthesize stockID=_stockID;
- (void).cxx_destruct;
- (BOOL)containNewsItemWithID:(long long)arg1;
- (id)init;

@end

