//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLStockWikiModel : FTCodingModel
{
    BOOL _enableWiki;
    BOOL _enableShowWatchStockNum;
    BOOL _enableShowBrowseNum;
    unsigned int _watchStockNum;
    unsigned int _browseNum;
    unsigned long long _stockId;
    NSString *_logoUrl;
    NSString *_desc;
    NSString *_detailUrl;
    NSString *_detailScheme;
}

@property(retain, nonatomic) NSString *detailScheme; // @synthesize detailScheme=_detailScheme;
@property(nonatomic) unsigned int browseNum; // @synthesize browseNum=_browseNum;
@property(nonatomic) BOOL enableShowBrowseNum; // @synthesize enableShowBrowseNum=_enableShowBrowseNum;
@property(nonatomic) unsigned int watchStockNum; // @synthesize watchStockNum=_watchStockNum;
@property(nonatomic) BOOL enableShowWatchStockNum; // @synthesize enableShowWatchStockNum=_enableShowWatchStockNum;
@property(copy, nonatomic) NSString *detailUrl; // @synthesize detailUrl=_detailUrl;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *logoUrl; // @synthesize logoUrl=_logoUrl;
@property(nonatomic) BOOL enableWiki; // @synthesize enableWiki=_enableWiki;
@property(nonatomic) unsigned long long stockId; // @synthesize stockId=_stockId;
- (void).cxx_destruct;

@end

