//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSArray, NSMutableArray, NSString;

@interface FLStockNoteManager : FLBaseManager
{
    unsigned long long _userID;
    NSString *_localDir;
    NSMutableArray *_mutableNotes;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableArray *mutableNotes; // @synthesize mutableNotes=_mutableNotes;
@property(retain, nonatomic) NSString *localDir; // @synthesize localDir=_localDir;
@property(nonatomic) unsigned long long userID; // @synthesize userID=_userID;
- (void).cxx_destruct;
- (void)onClientDataUpdate:(id)arg1;
- (void)uploadStockNote:(id)arg1 data:(id)arg2;
- (void)downloadStockNotes;
- (void)saveStockNoteID:(unsigned long long)arg1 data:(id)arg2;
- (void)loadLocalStockNotes;
- (void)deleteStockNote:(id)arg1;
- (void)saveStockNote:(id)arg1;
@property(readonly, nonatomic) NSArray *stockNotes;
- (void)onSessionLogin:(id)arg1;
- (void)dealloc;
- (id)init;

@end

