//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseStockFilterRequest.h>

@interface FLStockRecommendFilterRequest : FLBaseStockFilterRequest
{
    int _sortType;
    unsigned int _marketType;
    unsigned long long _strategyID;
}

@property(readonly, nonatomic) unsigned int marketType; // @synthesize marketType=_marketType;
@property(readonly, nonatomic) unsigned long long strategyID; // @synthesize strategyID=_strategyID;
@property(nonatomic) int sortType; // @synthesize sortType=_sortType;
- (unsigned char)reqMarketType;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)filterMarketType;
- (BOOL)supportBMP;
- (id)init;
- (id)initWithStrategyID:(unsigned long long)arg1 marketType:(unsigned int)arg2;

@end

