//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSMutableDictionary;

@interface FLStockF10Manager : FLBaseManager
{
    BOOL _enableFileCache;
    NSMutableDictionary *_briefingCache;
    NSMutableDictionary *_financeCache;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *financeCache; // @synthesize financeCache=_financeCache;
@property(retain, nonatomic) NSMutableDictionary *briefingCache; // @synthesize briefingCache=_briefingCache;
@property(readonly, nonatomic) BOOL enableFileCache; // @synthesize enableFileCache=_enableFileCache;
- (void).cxx_destruct;
- (BOOL)shouldRefreshWithStockId:(unsigned long long)arg1 withType:(int)arg2;
- (void)setLastRefreshTimeStamp:(double)arg1 withStockId:(unsigned long long)arg2 withType:(int)arg3;
- (id)filePathWithStockId:(unsigned long long)arg1 withType:(int)arg2 withLanguage:(int)arg3;
- (id)getPathWithStockId:(unsigned long long)arg1 withType:(int)arg2 withLanguage:(int)arg3;
- (void)updateLocalFinanceBriefingModel:(id)arg1 withStockId:(unsigned long long)arg2 withLanguage:(int)arg3;
- (void)updateLocalCompanyBriefingModel:(id)arg1 withStockId:(unsigned long long)arg2 withLanguage:(int)arg3;
- (id)getFinanceBriefingModelWithStockId:(unsigned long long)arg1 withLanguage:(int)arg2;
- (id)getCompanyBriefingModelWithStockId:(unsigned long long)arg1 withLanguage:(int)arg2;
- (id)usNormalFinanceBalanceModelWithPbModel:(struct BriefingBalanceSheet_US)arg1;
- (id)usFinanceBalanceModelWithPbModel:(struct BriefingBalanceSheet_US_BnkIns)arg1;
- (id)usNormalFinanceIncomeModelWithPbModel:(struct BriefingIncomeInfo_US)arg1;
- (id)usFinanceIncomeModelWithPbModel:(struct BriefingIncomeInfo_US_BnkIns)arg1;
- (id)usFinanceCashFlowModelWithPbModel:(struct BriefingCashFlow_US)arg1;
- (id)hkFinanceCashFlowModelWithPbModel:(struct BriefingCashFlow_HK)arg1;
- (id)hkNoFinFinanceBalanceModelWithPbModel:(struct BriefingBalanceSheet_HK_NoFin)arg1;
- (id)hkFinFinanceBalanceModelWithPbModel:(struct BriefingBalanceSheet_HK_Fin)arg1;
- (id)hkNoFinFinanceIncomeModelWithPbModel:(struct BriefingIncomeInfo_HK_NoFin)arg1;
- (id)hkFinFinanceIncomeModelWithPbModel:(struct BriefingIncomeInfo_HK_Fin)arg1;
- (id)cnFinanceCashFLowModelWithPbModel:(struct BriefingCashFlow_A)arg1;
- (id)cnFinanceBalanceModelWithPbModel:(struct BriefingBalanceSheet_A)arg1;
- (id)cnFinanceIncomeModelWithPbModel:(struct BriefingIncomeInfo_A)arg1;
- (id)cnFinanceKeyIndexModelWithPbModel:(struct BriefingKeyIndexInfo_A)arg1;
- (id)splitModelWithPbModel:(struct BriefingSplitInfo)arg1;
- (id)buybackModelWithPbModel:(struct BriefingBuybackInfo)arg1;
- (id)dividendModelWithPbModel:(struct BriefingDividendInfo)arg1;
- (id)sharesModelWithPbModel:(struct BriefingSharesInfo)arg1;
- (id)infoModelWithPbModel:(struct BriefingCompanyInfo)arg1;
- (id)plateModelWithPbModel:(struct OwnerPlateInfo)arg1;
- (id)wikiModelWithPbModel:(struct BaikeInfo)arg1;
- (BOOL)fetchFinanceBriefingWithStockId:(unsigned long long)arg1 withLanguage:(int)arg2 response:(CDUnknownBlockType)arg3;
- (BOOL)fetchCompanyBriefingWithStockId:(unsigned long long)arg1 withLanguage:(int)arg2 response:(CDUnknownBlockType)arg3;
- (id)init;

@end

