//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FLStockForecastPriceItem : NSObject
{
    unsigned long long _forecastType;
    NSArray *_forecastRangeItemList;
}

@property(retain, nonatomic) NSArray *forecastRangeItemList; // @synthesize forecastRangeItemList=_forecastRangeItemList;
@property(nonatomic) unsigned long long forecastType; // @synthesize forecastType=_forecastType;
- (void).cxx_destruct;
- (id)debugDescription;

@end

