//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLStockNoteElement-Protocol.h>

@class NSString;

@interface FLStockNoteStockElement : NSObject <FLStockNoteElement>
{
    unsigned long long _stockID;
    NSString *_text;
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) unsigned long long stockID; // @synthesize stockID=_stockID;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) unsigned long long type;
- (id)initWithStockID:(unsigned long long)arg1 text:(id)arg2;
- (id)initWithStock:(id)arg1;

@end

