//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLPlateStockItem.h>

@interface FLStockItem : FLPlateStockItem
{
    unsigned int _askPrice;
    unsigned int _buyPrice;
    unsigned int _ipoPrice;
    unsigned int _listingDate;
    unsigned int _ipoPe;
    int _ipoPriceChangeRatio;
    unsigned int _continuousRiseDayCount;
    unsigned int _preMarketPrice;
    int _preMarketPCA;
    unsigned int _afterHourPrice;
    int _afterHourPCA;
    unsigned int _preMarketAmplitude;
    unsigned int _afterHourAmplitude;
    unsigned int _annualPERatio;
    unsigned int _ttmPERatio;
    unsigned int _dividendRatio;
    int _annualEPS;
    int _ttmEPS;
    int _dividend;
    unsigned long long _askVolume;
    unsigned long long _buyVolume;
    long long _firstDayPriceChangeRatio;
    long long _firstDayRealPriceChangeRatio;
    unsigned long long _ipoIssueVolume;
    long long _preMarketPCR;
    long long _afterHourPCR;
    unsigned long long _preMarketTurnover;
    unsigned long long _afterHourTurnover;
    unsigned long long _hkCaptical;
}

@property(nonatomic) int dividend; // @synthesize dividend=_dividend;
@property(nonatomic) int ttmEPS; // @synthesize ttmEPS=_ttmEPS;
@property(nonatomic) int annualEPS; // @synthesize annualEPS=_annualEPS;
@property(nonatomic) unsigned int dividendRatio; // @synthesize dividendRatio=_dividendRatio;
@property(nonatomic) unsigned int ttmPERatio; // @synthesize ttmPERatio=_ttmPERatio;
@property(nonatomic) unsigned int annualPERatio; // @synthesize annualPERatio=_annualPERatio;
@property(nonatomic) unsigned long long hkCaptical; // @synthesize hkCaptical=_hkCaptical;
@property(nonatomic) unsigned long long afterHourTurnover; // @synthesize afterHourTurnover=_afterHourTurnover;
@property(nonatomic) unsigned long long preMarketTurnover; // @synthesize preMarketTurnover=_preMarketTurnover;
@property(nonatomic) unsigned int afterHourAmplitude; // @synthesize afterHourAmplitude=_afterHourAmplitude;
@property(nonatomic) unsigned int preMarketAmplitude; // @synthesize preMarketAmplitude=_preMarketAmplitude;
@property(nonatomic) long long afterHourPCR; // @synthesize afterHourPCR=_afterHourPCR;
@property(nonatomic) int afterHourPCA; // @synthesize afterHourPCA=_afterHourPCA;
@property(nonatomic) unsigned int afterHourPrice; // @synthesize afterHourPrice=_afterHourPrice;
@property(nonatomic) long long preMarketPCR; // @synthesize preMarketPCR=_preMarketPCR;
@property(nonatomic) int preMarketPCA; // @synthesize preMarketPCA=_preMarketPCA;
@property(nonatomic) unsigned int preMarketPrice; // @synthesize preMarketPrice=_preMarketPrice;
@property(nonatomic) unsigned long long ipoIssueVolume; // @synthesize ipoIssueVolume=_ipoIssueVolume;
@property(nonatomic) long long firstDayRealPriceChangeRatio; // @synthesize firstDayRealPriceChangeRatio=_firstDayRealPriceChangeRatio;
@property(nonatomic) long long firstDayPriceChangeRatio; // @synthesize firstDayPriceChangeRatio=_firstDayPriceChangeRatio;
@property(nonatomic) unsigned int continuousRiseDayCount; // @synthesize continuousRiseDayCount=_continuousRiseDayCount;
@property(nonatomic) int ipoPriceChangeRatio; // @synthesize ipoPriceChangeRatio=_ipoPriceChangeRatio;
@property(nonatomic) unsigned int ipoPe; // @synthesize ipoPe=_ipoPe;
@property(nonatomic) unsigned int listingDate; // @synthesize listingDate=_listingDate;
@property(nonatomic) unsigned int ipoPrice; // @synthesize ipoPrice=_ipoPrice;
@property(nonatomic) unsigned int buyPrice; // @synthesize buyPrice=_buyPrice;
@property(nonatomic) unsigned int askPrice; // @synthesize askPrice=_askPrice;
@property(nonatomic) unsigned long long buyVolume; // @synthesize buyVolume=_buyVolume;
@property(nonatomic) unsigned long long askVolume; // @synthesize askVolume=_askVolume;

@end

