//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseFilterManager.h>

@interface FLStockFilterManager : FLBaseFilterManager
{
}

+ (id)defaultManager;
- (id)userInfoWithRecommendProtoBuffer:(struct PickingStrategyStocks_Rsp *)arg1;
- (BOOL)fetchFilterModelsWithRecommendRequest:(id)arg1 response:(CDUnknownBlockType)arg2;
- (id)userInfoWithConditionProtoBuffer:(const struct StockCondition_Rsp *)arg1;
- (BOOL)fetchFilterModelsWithConditionRequest:(id)arg1 response:(CDUnknownBlockType)arg2;
- (BOOL)fetchFilterModelsWithRequest:(id)arg1 response:(CDUnknownBlockType)arg2;

@end

