//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/FLStockObject-Protocol.h>

@class NSString;

@interface FLStockObject : FTCodingModel <FLStockObject>
{
    unsigned long long _ID;
}

@property(nonatomic) unsigned long long ID; // @synthesize ID=_ID;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

