//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLStockManager.h>

@class NSObject;
@protocol OS_dispatch_queue;

@interface FLStockManager (WatchStocks)
+ (void)load;
- (id)stockAdapter;
- (void)setStockAdapter:(id)arg1;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *callbackQueue;
- (void)positionStocksDidUpdate:(id)arg1;
- (id)stocksWithStockIDs:(id)arg1;
- (void)stocksWithStockIDs:(id)arg1 reponseBlock:(CDUnknownBlockType)arg2;
- (id)containerFilePathWithUserID:(unsigned long long)arg1;
- (void)postNotificationWithUserID:(unsigned long long)arg1 container:(id)arg2;
- (id)loadWatchStockContainerForUser:(unsigned long long)arg1;
- (void)saveWatchStockContainer:(id)arg1 forUser:(unsigned long long)arg2;
- (id)updateWatchPositionGroupStocksWithPositionStocks:(id)arg1 Container:(id)arg2;
- (void)updateCurrentUserWatchStockContainer:(id)arg1;
- (void)refetchCurrentUserWatchStockContainer;
- (void)groupCoverActionWithGroup:(id)arg1 stocks:(id)arg2 reachedMax:(BOOL)arg3;
- (void)groupDeleteActionWithGroup:(id)arg1 stocks:(id)arg2 reachedMax:(BOOL)arg3;
- (void)groupAddActionWithGroup:(id)arg1 stocks:(id)arg2 toEnd:(BOOL)arg3 reachedMax:(BOOL)arg4;
- (void)groupDidReceive:(id)arg1 error:(id)arg2;
- (void)groupListForceCleanAndRepullWithGroups:(id)arg1 reachedMax:(BOOL)arg2;
- (void)groupListCoverActionWithGroups:(id)arg1 reachedMax:(BOOL)arg2;
- (void)groupListRenameActionWithGroups:(id)arg1 reachedMax:(BOOL)arg2;
- (void)groupListSortActionWithGroups:(id)arg1 reachedMax:(BOOL)arg2;
- (void)groupListDeleteActionWithGroups:(id)arg1 reachedMax:(BOOL)arg2;
- (void)groupListAddActionWithGroups:(id)arg1 reachedMax:(BOOL)arg2;
- (void)groupListDidReceive:(id)arg1 error:(id)arg2;
- (BOOL)fetchWatchStocksWithGroupID:(unsigned int)arg1 forUser:(unsigned long long)arg2 response:(CDUnknownBlockType)arg3;
- (BOOL)fetchWatchStocksWithGroupID:(unsigned int)arg1 response:(CDUnknownBlockType)arg2;
- (BOOL)fetchWatchGroupsForUser:(unsigned long long)arg1 sequence:(unsigned long long)arg2 response:(CDUnknownBlockType)arg3;
- (BOOL)fetchContainerForUser:(unsigned long long)arg1 sequence:(unsigned long long)arg2 response:(CDUnknownBlockType)arg3;
- (BOOL)fetchContainerWithResponse:(CDUnknownBlockType)arg1;
- (BOOL)move:(id)arg1 from:(id)arg2 to:(id)arg3 notify:(BOOL)arg4 response:(CDUnknownBlockType)arg5;
- (BOOL)sort:(id)arg1 inGroup:(id)arg2 notify:(BOOL)arg3 response:(CDUnknownBlockType)arg4;
- (BOOL)sort:(id)arg1 below:(id)arg2 notify:(BOOL)arg3 response:(CDUnknownBlockType)arg4;
- (BOOL)remove:(id)arg1 from:(id)arg2 notify:(BOOL)arg3 response:(CDUnknownBlockType)arg4;
- (BOOL)removeFromAllGroups:(id)arg1 notify:(BOOL)arg2 response:(CDUnknownBlockType)arg3;
- (BOOL)innerAdd:(id)arg1 to:(id)arg2 append:(BOOL)arg3 notify:(BOOL)arg4 response:(CDUnknownBlockType)arg5;
- (BOOL)add:(id)arg1 to:(id)arg2 append:(BOOL)arg3 notify:(BOOL)arg4 response:(CDUnknownBlockType)arg5;
- (BOOL)rename:(id)arg1 response:(CDUnknownBlockType)arg2;
- (BOOL)sort:(id)arg1 response:(CDUnknownBlockType)arg2;
- (BOOL)remove:(id)arg1 response:(CDUnknownBlockType)arg2;
- (BOOL)add:(id)arg1 response:(CDUnknownBlockType)arg2;
- (id)container;
- (unsigned long long)userID;
- (void)watchStockContainerFetch;
- (void)watchStocksContainerLoad;
- (void)initializePushService;
@end

