//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLVersionFileDataManager.h>

@class NSMutableDictionary;

@interface FLStockNewsManager : FLVersionFileDataManager
{
    NSMutableDictionary *_cachedDic;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *cachedDic; // @synthesize cachedDic=_cachedDic;
- (void).cxx_destruct;
- (BOOL)shouldRefreshWithStockId:(unsigned long long)arg1 withStockName:(id)arg2 inSubType:(int)arg3;
- (void)setLastRefreshTimeStamp:(double)arg1 withStockId:(unsigned long long)arg2 withStockName:(id)arg3 inSubType:(int)arg4;
- (id)filePathWithStockId:(unsigned long long)arg1 withStockName:(id)arg2 inSubType:(int)arg3;
- (id)getPathWithStockId:(unsigned long long)arg1 withStockName:(id)arg2 inSubType:(int)arg3;
- (id)getStockNewsArrayWithStockId:(unsigned long long)arg1 withStockName:(id)arg2 inSubType:(int)arg3;
- (void)updateLocalStockNewsArray:(id)arg1 withStockId:(unsigned long long)arg2 withStockName:(id)arg3 inSubType:(int)arg4 isAppending:(BOOL)arg5;
- (id)stockNewsModelWithPbModel:(struct BulletinItem *)arg1;
- (BOOL)fetchNewsWithStockId:(unsigned long long)arg1 stockName:(id)arg2 from:(unsigned int)arg3 to:(unsigned int)arg4 subType:(int)arg5 maxCount:(unsigned int)arg6 cached:(BOOL)arg7 response:(CDUnknownBlockType)arg8;

@end

