//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLStock, NSMutableArray;

@interface FLSubscribeItem : NSObject
{
    NSMutableArray *_subscribeObservers;
    FLStock *_stock;
    unsigned long long _subscribeType;
}

@property(nonatomic) unsigned long long subscribeType; // @synthesize subscribeType=_subscribeType;
@property(retain, nonatomic) FLStock *stock; // @synthesize stock=_stock;
- (void).cxx_destruct;
- (id)logStringForSubscribeType:(unsigned long long)arg1;
- (id)description;
- (BOOL)removeSubscribeType:(unsigned long long)arg1 observer:(id)arg2;
- (BOOL)addSubscribeType:(unsigned long long)arg1 observer:(id)arg2;
@property(readonly, nonatomic) unsigned long long subscribeObserversCount;
- (id)init;

@end

