//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLStock.h>

#import <FTEngine/FLWeakKVOObserverCleaner-Protocol.h>

@class NSString;

@interface FLSubscribeStock : FLStock <FLWeakKVOObserverCleaner>
{
}

- (unsigned long long)subscribeTypeForKeyPath:(id)arg1;
- (void)removeSubscribeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)cleanerRemoveWeakKVOObserver:(id)arg1;
- (void)setWeakObservers:(id)arg1;
- (id)weakObservers;
- (void)removeAllWeakObservers;
- (void)removeWeakObserver:(id)arg1;
- (id)addWeakObserverForRealObserver:(id)arg1 keyPath:(id)arg2;
- (id)getWeakObserverByRealObserver:(id)arg1 keyPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

