//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLSubAccountBroker : FTCodingModel
{
    long long _ID;
    NSString *_name;
    NSString *_longName;
}

@property(copy, nonatomic) NSString *longName; // @synthesize longName=_longName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

