//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSString;

@interface FLTransferBankTransaction : NSObject <NSCopying>
{
    BOOL _currencyType;
    NSString *_date;
    NSString *_time;
    long long _transactionValue;
    NSString *_transactionValueString;
    long long _status;
    NSString *_statusString;
    long long _sourceType;
    NSString *_sourceTypeString;
    NSString *_errorMessage;
}

@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(copy, nonatomic) NSString *sourceTypeString; // @synthesize sourceTypeString=_sourceTypeString;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@property(copy, nonatomic) NSString *statusString; // @synthesize statusString=_statusString;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *transactionValueString; // @synthesize transactionValueString=_transactionValueString;
@property(nonatomic) long long transactionValue; // @synthesize transactionValue=_transactionValue;
@property(nonatomic) BOOL currencyType; // @synthesize currencyType=_currencyType;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
- (void).cxx_destruct;
- (void)decodeWithTransferBankTransaction:(void *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

