//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSDictionary;
@protocol FLTimeSection;

@protocol FLTradeTimeManager
- (void)setSimpleConfig:(NSDictionary *)arg1;
- (NSArray<FLTimeSection> *)innerTimeSectionsWithStockMarketID:(unsigned char)arg1 forTradeDayTime:(unsigned int)arg2;
- (unsigned int)latestTradeTimeForStockMarketID:(unsigned char)arg1;
@end

