//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/NSObject-Protocol.h>

@class FLOrder, FLStock, FLSubAccount, NSArray, NSDate, NSString;

@protocol FLTradeManager <NSObject>
- (void)requestTradesOfOrder:(FLOrder *)arg1 page:(int)arg2 pageCount:(unsigned int)arg3 resultBlock:(void (^)(int, id))arg4;
- (void)requestHistoryOrdersOfStock:(FLStock *)arg1 page:(int)arg2 pageCount:(unsigned int)arg3 subAccount:(FLSubAccount *)arg4 resultBlock:(void (^)(int, id))arg5;
- (void)getMaxTradeQuantityForOrder:(FLOrder *)arg1 resultBlock:(void (^)(BOOL, FLMaxTransaction *))arg2;
- (void)getMaxTradeQuantityForStock:(FLStock *)arg1 forSubAccount:(FLSubAccount *)arg2 resultBlock:(void (^)(BOOL, FLMaxTransaction *))arg3;
- (unsigned long long)marketType;
- (NSArray *)subAccounts;
- (void)historyType:(int)arg1 fromDate:(NSDate *)arg2 toDate:(NSDate *)arg3 pageFlag:(NSString *)arg4 context:(id)arg5 subAccount:(FLSubAccount *)arg6;
- (void)requestHistoryDatesInYear:(unsigned short)arg1 subAccount:(FLSubAccount *)arg2 resultBlock:(void (^)(int, id))arg3;
- (void)orderSetting:(FLOrder *)arg1 actionType:(int)arg2 subAccount:(FLSubAccount *)arg3;
- (void)orderMake:(FLOrder *)arg1;
- (void)requestDataForSubAccount:(FLSubAccount *)arg1;
- (void)requestDataForSubAccounts;
@end

