//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLOrder.h>

@interface FLUOrder : FLOrder
{
    int _type;
    int _status;
    int _tradingSession;
    long long _loanType;
}

@property(nonatomic) int tradingSession; // @synthesize tradingSession=_tradingSession;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) long long loanType; // @synthesize loanType=_loanType;
@property(nonatomic) int type; // @synthesize type=_type;
- (id)description;
- (id)oldPriceString;
- (id)priceString;
- (int)priceStep;
- (id)typeText;
- (id)displayErrorMessage;
- (id)triggerPriceString;
- (void)setTriggerOrder:(BOOL)arg1;
- (BOOL)isRequirePrice;
- (BOOL)priceAdjustable;
- (BOOL)removable;
- (BOOL)cancelable;
- (BOOL)editable;
- (BOOL)isPending;
- (BOOL)isSuccess;
- (BOOL)isFailed;
- (id)triggerDesc;
- (long long)compareStatus:(id)arg1;
- (id)statusText;
- (id)updateStatus;
- (id)init;
- (void)triggerOrderDecodeWithDictionary:(id)arg1;
- (void)decodeWithDictionary:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

