//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLUOption;

@interface FLUOptionChainItem : NSObject
{
    FLUOption *_callOption;
    FLUOption *_putOption;
}

@property(retain, nonatomic) FLUOption *putOption; // @synthesize putOption=_putOption;
@property(retain, nonatomic) FLUOption *callOption; // @synthesize callOption=_callOption;
- (void).cxx_destruct;

@end

