//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLManagerProtocol-Protocol.h>

@class NSString;

@interface FLUOptionManager : NSObject <FLManagerProtocol>
{
}

+ (id)defaultManager;
- (id)errorWithDomain:(id)arg1 code:(int)arg2 errorInfo:(id)arg3;
- (BOOL)fetchOptionInfoWithOptionStringCodeList:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (BOOL)fetchOptionIDByOptionStringCodeList:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (BOOL)fetchOptionInfoWithOptionIDList:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (BOOL)fetchOptionChainByConditionWithStock:(unsigned long long)arg1 strikeTime:(unsigned int)arg2 optionType:(int)arg3 conditionType:(int)arg4 maxDataCount:(unsigned int)arg5 callBack:(CDUnknownBlockType)arg6;
- (BOOL)fetchOptionChainWithRequest:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (BOOL)fetchOptionStrikeDateWithUnderlyingStockID:(unsigned long long)arg1 callBack:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

