//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseFilterManager.h>

@interface FLUOptionFilterManager : FLBaseFilterManager
{
}

+ (id)defaultManager;
- (BOOL)fetchFilterModelsWithRequest:(id)arg1 response:(CDUnknownBlockType)arg2;
- (BOOL)fetchStrikeDatesWithUnderlyingStockID:(unsigned long long)arg1 response:(CDUnknownBlockType)arg2;

@end

