//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLStock;

@interface FLUOptionChainFilterModel : NSObject
{
    FLStock *_callOption;
    FLStock *_putOption;
    unsigned long long _optionChainSequence;
}

@property(nonatomic) unsigned long long optionChainSequence; // @synthesize optionChainSequence=_optionChainSequence;
@property(retain, nonatomic) FLStock *putOption; // @synthesize putOption=_putOption;
@property(retain, nonatomic) FLStock *callOption; // @synthesize callOption=_callOption;
- (void).cxx_destruct;
- (void)optionRemoveObserver;
- (void)optionAddObserver;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2 context:(void *)arg3;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;

@end

