//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseStockFilterRequest.h>

@interface FLUOptionFilterRequest : FLBaseStockFilterRequest
{
    unsigned int _strikeTime;
    int _optionType;
    int _conditionType;
    unsigned long long _stockID;
}

+ (id)request;
@property(nonatomic) int conditionType; // @synthesize conditionType=_conditionType;
@property(nonatomic) int optionType; // @synthesize optionType=_optionType;
@property(nonatomic) unsigned int strikeTime; // @synthesize strikeTime=_strikeTime;
@property(nonatomic) unsigned long long stockID; // @synthesize stockID=_stockID;
- (unsigned int)filterMarketType;
- (BOOL)supportBMP;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;
- (id)initWithStockID:(unsigned long long)arg1 strikeTime:(unsigned int)arg2 optionType:(int)arg3;

@end

