//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FLUOptionInfo : NSObject
{
    unsigned int _delistingFlag;
    unsigned int _strikeDate;
    int _optionType;
    unsigned int _suspendFlag;
    unsigned int _contractShareSize;
    NSString *_optionName;
    NSString *_optionStringCode;
    unsigned long long _optionID;
    unsigned long long _underlyingSecurityID;
    unsigned long long _strikePrice;
    NSString *_market;
    unsigned long long _sequence;
}

@property(nonatomic) unsigned long long sequence; // @synthesize sequence=_sequence;
@property(nonatomic) unsigned int contractShareSize; // @synthesize contractShareSize=_contractShareSize;
@property(nonatomic) unsigned int suspendFlag; // @synthesize suspendFlag=_suspendFlag;
@property(copy, nonatomic) NSString *market; // @synthesize market=_market;
@property(nonatomic) int optionType; // @synthesize optionType=_optionType;
@property(nonatomic) unsigned long long strikePrice; // @synthesize strikePrice=_strikePrice;
@property(nonatomic) unsigned int strikeDate; // @synthesize strikeDate=_strikeDate;
@property(nonatomic) unsigned int delistingFlag; // @synthesize delistingFlag=_delistingFlag;
@property(nonatomic) unsigned long long underlyingSecurityID; // @synthesize underlyingSecurityID=_underlyingSecurityID;
@property(nonatomic) unsigned long long optionID; // @synthesize optionID=_optionID;
@property(copy, nonatomic) NSString *optionStringCode; // @synthesize optionStringCode=_optionStringCode;
@property(copy, nonatomic) NSString *optionName; // @synthesize optionName=_optionName;
- (void).cxx_destruct;

@end

