//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCoding-Protocol.h>

@class NSDictionary, NSString;
@protocol uploadDelegate;

@interface FLUploadTaskModel : NSObject <NSCoding>
{
    int _dataType;
    int _statusType;
    int _percent;
    NSString *_fileName;
    NSString *_filePath;
    id _fileData;
    NSDictionary *_fileInfo;
    NSDictionary *_responseInfo;
    id <uploadDelegate> _delegate;
}

@property(nonatomic) __weak id <uploadDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *responseInfo; // @synthesize responseInfo=_responseInfo;
@property(retain, nonatomic) NSDictionary *fileInfo; // @synthesize fileInfo=_fileInfo;
@property(retain, nonatomic) id fileData; // @synthesize fileData=_fileData;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(nonatomic) int percent; // @synthesize percent=_percent;
@property(nonatomic) int statusType; // @synthesize statusType=_statusType;
@property(nonatomic) int dataType; // @synthesize dataType=_dataType;
- (void).cxx_destruct;
- (void)uploadVideo;
- (void)uploadAudio;
- (void)uploadFile;
- (void)uploadImage;
- (void)uploadImageWithSucceed:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)start;
- (void)startWithSuccessed:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

