//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLUploadHttpClient;

@interface FLUploadManager : NSObject
{
    FLUploadHttpClient *_httpClient;
}

+ (id)sharedInstance;
@property(retain, nonatomic) FLUploadHttpClient *httpClient; // @synthesize httpClient=_httpClient;
- (void).cxx_destruct;
- (id)signWithString:(id)arg1;
- (id)defaultDownloadParamsWithPath:(id)arg1 fileName:(id)arg2 BucketId:(id)arg3;
- (id)getUrlStringWithPath:(id)arg1 fileName:(id)arg2 bucketId:(id)arg3;
- (id)defaultCompressParamsWithFileInfo:(id)arg1;
- (id)defaultUploadParamsWithFileInfo:(id)arg1;
- (id)urlStringWithParam:(id)arg1 command:(id)arg2;
- (void)onlineGenerateBigImage:(id)arg1 responseBlock:(CDUnknownBlockType)arg2;
- (void)uploadImageData:(id)arg1 fileInfo:(id)arg2 progressBlock:(CDUnknownBlockType)arg3 reponse:(CDUnknownBlockType)arg4;

@end

