//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol FLUploadProtocol;

@interface FLUploadService : NSObject
{
    id <FLUploadProtocol> _uploadManager;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <FLUploadProtocol> uploadManager; // @synthesize uploadManager=_uploadManager;
- (void).cxx_destruct;

@end

