//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLUrlHelper : NSObject
{
}

+ (id)stockWithQuoteURL:(id)arg1;
+ (id)parseFutunnScheme:(id)arg1;
+ (void)handleFutunnScheme:(id)arg1;
+ (BOOL)handleOpenUrl:(id)arg1;

@end

