//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLUserSubscibeItem : FTCodingModel
{
    int _channelId;
    int _typeId;
    int _value;
    int _unsubscribeAble;
    NSString *_typeName;
}

@property(copy, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(nonatomic) int unsubscribeAble; // @synthesize unsubscribeAble=_unsubscribeAble;
@property(nonatomic) int value; // @synthesize value=_value;
@property(nonatomic) int typeId; // @synthesize typeId=_typeId;
@property(nonatomic) int channelId; // @synthesize channelId=_channelId;
- (void).cxx_destruct;

@end

