//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FLCNUserQuoteData, FLHKUserQuoteData, FLUSUserQuoteData, FLWatchStockContainer, NSArray, NSDate, NSString;

@interface FLUserData : NSObject
{
    BOOL _isGuest;
    BOOL _hasUSMarginSubAccount;
    BOOL _watchGroupsLimitReached;
    BOOL _watchStocksLimitReached;
    BOOL _isClient;
    unsigned int _usOptionFlag;
    unsigned int _futureFlag;
    unsigned int _serviceFlag;
    unsigned int _friendVerifyType;
    NSString *_login;
    NSString *_identifier;
    NSString *_name;
    NSString *_nickName;
    unsigned long long _userID;
    unsigned long long _sessionID;
    NSString *_uploadSig;
    NSString *_webSig;
    NSDate *_freeExpiredTime;
    NSString *_lastLoginIp;
    NSString *_lastLoginAddress;
    NSDate *_lastLoginTime;
    long long _USSubAccountsState;
    long long _HKSubAccountState;
    FLHKUserQuoteData *_hkQuoteData;
    FLUSUserQuoteData *_usQuoteData;
    FLCNUserQuoteData *_cnQuoteData;
    NSArray *_hkHistoryStocks;
    NSArray *_usHistoryStocks;
    NSArray *_cnHistoryStocks;
    FLWatchStockContainer *_watchStockContainer;
    NSArray *_visitedStocks;
}

@property(nonatomic) unsigned int friendVerifyType; // @synthesize friendVerifyType=_friendVerifyType;
@property(retain, nonatomic) NSArray *visitedStocks; // @synthesize visitedStocks=_visitedStocks;
@property(retain, nonatomic) FLWatchStockContainer *watchStockContainer; // @synthesize watchStockContainer=_watchStockContainer;
@property(nonatomic) BOOL isClient; // @synthesize isClient=_isClient;
@property(retain, nonatomic) NSArray *cnHistoryStocks; // @synthesize cnHistoryStocks=_cnHistoryStocks;
@property(retain, nonatomic) NSArray *usHistoryStocks; // @synthesize usHistoryStocks=_usHistoryStocks;
@property(retain, nonatomic) NSArray *hkHistoryStocks; // @synthesize hkHistoryStocks=_hkHistoryStocks;
@property(nonatomic) BOOL watchStocksLimitReached; // @synthesize watchStocksLimitReached=_watchStocksLimitReached;
@property(nonatomic) BOOL watchGroupsLimitReached; // @synthesize watchGroupsLimitReached=_watchGroupsLimitReached;
@property(retain, nonatomic) FLCNUserQuoteData *cnQuoteData; // @synthesize cnQuoteData=_cnQuoteData;
@property(retain, nonatomic) FLUSUserQuoteData *usQuoteData; // @synthesize usQuoteData=_usQuoteData;
@property(retain, nonatomic) FLHKUserQuoteData *hkQuoteData; // @synthesize hkQuoteData=_hkQuoteData;
@property(nonatomic) long long HKSubAccountState; // @synthesize HKSubAccountState=_HKSubAccountState;
@property(nonatomic) long long USSubAccountsState; // @synthesize USSubAccountsState=_USSubAccountsState;
@property(nonatomic) BOOL hasUSMarginSubAccount; // @synthesize hasUSMarginSubAccount=_hasUSMarginSubAccount;
@property BOOL isGuest; // @synthesize isGuest=_isGuest;
@property(nonatomic) unsigned int serviceFlag; // @synthesize serviceFlag=_serviceFlag;
@property(nonatomic) unsigned int futureFlag; // @synthesize futureFlag=_futureFlag;
@property(nonatomic) unsigned int usOptionFlag; // @synthesize usOptionFlag=_usOptionFlag;
@property(retain, nonatomic) NSDate *lastLoginTime; // @synthesize lastLoginTime=_lastLoginTime;
@property(retain, nonatomic) NSString *lastLoginAddress; // @synthesize lastLoginAddress=_lastLoginAddress;
@property(retain, nonatomic) NSString *lastLoginIp; // @synthesize lastLoginIp=_lastLoginIp;
@property(retain, nonatomic) NSDate *freeExpiredTime; // @synthesize freeExpiredTime=_freeExpiredTime;
@property(copy, nonatomic) NSString *webSig; // @synthesize webSig=_webSig;
@property(copy, nonatomic) NSString *uploadSig; // @synthesize uploadSig=_uploadSig;
@property(nonatomic) unsigned long long sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) unsigned long long userID; // @synthesize userID=_userID;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *login; // @synthesize login=_login;
- (void).cxx_destruct;
- (id)logUserQuoteState;
- (id)quoteDataForMarketType:(unsigned long long)arg1;
@property(nonatomic) BOOL hasSetLoginPsw;
@property(readonly, nonatomic) BOOL isLoginSuccess;
- (void)dealloc;
- (void)initQuoteMarketData;
- (id)init;

@end

