//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLSubAccount.h>

@interface FLUSubAccount : FLSubAccount
{
    int _marginCallRiskLevel;
    long long _shortPower;
    long long _marginCallBalance;
    double _marginCallBalanceRatio;
    long long _marginCallRecover;
    long long _longStockValue;
    long long _shortStockValue;
    long long _marginCall;
}

@property(nonatomic) long long marginCall; // @synthesize marginCall=_marginCall;
@property(nonatomic) long long shortStockValue; // @synthesize shortStockValue=_shortStockValue;
@property(nonatomic) long long longStockValue; // @synthesize longStockValue=_longStockValue;
@property(nonatomic) int marginCallRiskLevel; // @synthesize marginCallRiskLevel=_marginCallRiskLevel;
@property(nonatomic) long long marginCallRecover; // @synthesize marginCallRecover=_marginCallRecover;
@property(nonatomic) double marginCallBalanceRatio; // @synthesize marginCallBalanceRatio=_marginCallBalanceRatio;
@property(nonatomic) long long marginCallBalance; // @synthesize marginCallBalance=_marginCallBalance;
@property(nonatomic) long long shortPower; // @synthesize shortPower=_shortPower;

@end

