//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSMutableDictionary;

@interface FLUserProfileManager : FLBaseManager
{
    BOOL _hasRegisterPushCommand;
    NSMutableDictionary *_userProfiles;
}

@property(retain, nonatomic) NSMutableDictionary *userProfiles; // @synthesize userProfiles=_userProfiles;
- (void).cxx_destruct;
- (void)userInfoInnerDecode:(struct util_byteios_net *)arg1;
- (void)userInfoGet;
- (unsigned long long)getClientProfileTypeWithServerProfileType:(unsigned int)arg1;
- (unsigned int)getServerProfileTypeWithClientProfileType:(unsigned long long)arg1;
- (id)getServerProfileTypeListWithClientProfileType:(unsigned long long)arg1;
- (id)getMedalModelWithUserId:(unsigned long long)arg1 clientProfileType:(unsigned long long)arg2;
- (BOOL)fetchUsersProfile:(id)arg1 withProfileType:(unsigned long long)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (id)getSavePath;
- (void)load;
- (void)save;
- (id)getLocalUserProfileModelByUserId:(unsigned long long)arg1 succeed:(char *)arg2;
- (void)onSessionServerDidLogin:(id)arg1;
- (void)onDidLogout:(id)arg1;
- (void)dealloc;
- (id)init;

@end

