//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface FLUserAddressCheckingModel : NSObject
{
    NSString *_link;
    NSArray *_noticeTime;
    NSString *_explanation;
}

@property(copy, nonatomic) NSString *explanation; // @synthesize explanation=_explanation;
@property(retain, nonatomic) NSArray *noticeTime; // @synthesize noticeTime=_noticeTime;
@property(copy, nonatomic) NSString *link; // @synthesize link=_link;
- (void).cxx_destruct;
- (void)decodeUserAddressCheckingModelWithDictionary:(id)arg1;
- (id)description;

@end

