//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

@class NSString;

@interface FLUSFinanceCashFlowModel : FTCodingModel
{
    NSString *_currency;
    NSString *_typeAndDate;
    NSString *_operatingCashFlow;
    NSString *_investingCashFlow;
    NSString *_financingCashFlow;
}

@property(copy, nonatomic) NSString *financingCashFlow; // @synthesize financingCashFlow=_financingCashFlow;
@property(copy, nonatomic) NSString *investingCashFlow; // @synthesize investingCashFlow=_investingCashFlow;
@property(copy, nonatomic) NSString *operatingCashFlow; // @synthesize operatingCashFlow=_operatingCashFlow;
@property(copy, nonatomic) NSString *typeAndDate; // @synthesize typeAndDate=_typeAndDate;
@property(copy, nonatomic) NSString *currency; // @synthesize currency=_currency;
- (void).cxx_destruct;

@end

