//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLUSFinanceBalanceModel.h>

@class NSString;

@interface FLUSFinanceBalanceModel_Normal : FLUSFinanceBalanceModel
{
    NSString *_currentAssets;
    NSString *_currentLiabilities;
}

@property(copy, nonatomic) NSString *currentLiabilities; // @synthesize currentLiabilities=_currentLiabilities;
@property(copy, nonatomic) NSString *currentAssets; // @synthesize currentAssets=_currentAssets;
- (void).cxx_destruct;

@end

