//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSMutableDictionary;

@interface FLUserManager : FLBaseManager
{
    NSMutableDictionary *_orderPasswordOperations;
    BOOL _hasRegisterPushCommand;
    int _subAccountsFetchTriedCount;
}

- (void).cxx_destruct;
- (id)encryptCipher:(char *)arg1 length:(int)arg2;
- (void)exchangeTradeCipherForSubAccounts:(id)arg1;
- (void)verifyTokenCode:(id)arg1 authSig:(id)arg2 forSubAccounts:(id)arg3;
- (void)orderPasswordOperateForSubAccounts:(id)arg1 passwordList:(id)arg2 isUnLock:(BOOL)arg3;
- (void)fetchTokenInfoAndPasswordModeWithBlock:(CDUnknownBlockType)arg1;
- (id)filterSubAccounts:(id)arg1;
- (void)loadSubAccountsOfUserID:(unsigned long long)arg1;
- (void)saveSubAccounts:(id)arg1;
- (void)fetchSubAccountsPage:(int)arg1 subAccounts:(id)arg2;
- (void)fetchSubAccounts;
- (void)orderPasswordDidUnlockedForSubAccount:(id)arg1;
- (void)orderPasswordLockAllSubAccounts;
- (void)orderPasswordLockAllFutuSubAccounts;
- (void)removePasswordOperationForSubAccount:(id)arg1;
- (void)orderPasswordUnlockAllFutuSubAccounts:(id)arg1;
- (void)orderPasswordLockSubAccount:(id)arg1;
- (void)orderPasswordUnlockSubAccount:(id)arg1 orderPassword:(id)arg2 verifyCode:(id)arg3;
- (void)orderPasswordUnlockSubAccount:(id)arg1 orderPassword:(id)arg2;
- (void)orderPasswordToggleForSubAccount:(id)arg1 orderPassword:(id)arg2 verifyCode:(id)arg3;
- (void)orderPasswordToggleForSubAccounts:(id)arg1 orderPassword:(id)arg2 verifyCode:(id)arg3;
- (void)orderPasswordCheckForSubAccount:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)orderPasswordCheckForSubAccount:(id)arg1 filterMarket:(BOOL)arg2 block:(CDUnknownBlockType)arg3;
- (void)messageDecode:(struct util_byteios_net *)arg1;
- (void)quoteServerSwitch:(int)arg1;
- (void)userAgreeToUseFreeQuote;
- (void)getLastLoginData;
- (void)userDidLogined;
- (void)dealloc;
- (void)onSessionWillSwitchUser:(id)arg1;
- (void)onSessionServerDidLogin:(id)arg1;
- (id)init;

@end

