//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLUserQuoteData : NSObject
{
    unsigned long long _marketType;
    unsigned long long _state;
    unsigned long long _oldState;
    unsigned long long _quotePermissionStateDiffReason;
    unsigned long long _tryHighLevelQuoteState;
    double _tryHighLevelQuoteExpiredTime;
}

@property(nonatomic) double tryHighLevelQuoteExpiredTime; // @synthesize tryHighLevelQuoteExpiredTime=_tryHighLevelQuoteExpiredTime;
@property(nonatomic) unsigned long long tryHighLevelQuoteState; // @synthesize tryHighLevelQuoteState=_tryHighLevelQuoteState;
@property(nonatomic) unsigned long long quotePermissionStateDiffReason; // @synthesize quotePermissionStateDiffReason=_quotePermissionStateDiffReason;
@property(nonatomic) unsigned long long oldState; // @synthesize oldState=_oldState;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic) unsigned long long marketType; // @synthesize marketType=_marketType;
- (id)description;
- (BOOL)isDelay;
- (BOOL)isBMP;
- (long long)permission;
- (id)initWithMarketType:(unsigned long long)arg1;

@end

