//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseTradeManager.h>

#import <FTEngine/FLTradeManager-Protocol.h>

@class NSString;

@interface FLUTradeManager : FLBaseTradeManager <FLTradeManager>
{
    BOOL _hasRegisterPushCommand;
}

- (void)writeDictionary:(id)arg1 subAccount:(id)arg2 command:(unsigned short)arg3 responseBlock:(CDUnknownBlockType)arg4;
- (void)requestTradesOfOrder:(id)arg1 page:(int)arg2 pageCount:(unsigned int)arg3 resultBlock:(CDUnknownBlockType)arg4;
- (void)requestHistoryOrdersOfStock:(id)arg1 page:(int)arg2 pageCount:(unsigned int)arg3 subAccount:(id)arg4 resultBlock:(CDUnknownBlockType)arg5;
- (void)historyType:(int)arg1 fromDate:(id)arg2 toDate:(id)arg3 pageFlag:(id)arg4 context:(id)arg5 subAccount:(id)arg6;
- (void)requestHistoryDatesInYear:(unsigned short)arg1 subAccount:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)triggerOrdersPushDecode:(struct util_byteios_net *)arg1;
- (void)requestTriggerOrdersPage:(id)arg1 tempArray:(id)arg2 subAccount:(id)arg3;
- (void)getMaxTradeQuantityForOrder:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)requestTriggerOrdersForSubAccount:(id)arg1;
- (void)orderEdit:(id)arg1;
- (void)orderSetting:(id)arg1 actionType:(int)arg2 subAccount:(id)arg3;
- (void)orderMake:(id)arg1;
- (void)ordersPushDecode:(struct util_byteios_net *)arg1;
- (void)requestOrdersPage:(int)arg1 tempArray:(id)arg2 subAccount:(id)arg3;
- (void)requestOrdersForSubAccount:(id)arg1;
- (void)tradesPushDecode:(struct util_byteios_net *)arg1;
- (void)requestTradesPage:(int)arg1 tempArray:(id)arg2 subAccount:(id)arg3;
- (void)requestTradesForSubAccount:(id)arg1;
- (void)positionPushDecode:(struct util_byteios_net *)arg1;
- (void)requestPositionsPage:(int)arg1 tempArray:(id)arg2 subAccount:(id)arg3;
- (void)requestPositionsForSubAccount:(id)arg1;
- (void)statisticsPushDecode:(struct ft_packer *)arg1;
- (void)statisticsRequestDecode:(id)arg1 subAccount:(id)arg2;
- (void)requestStatisticsForSubAccount:(id)arg1;
- (void)cashInfoPushDecode:(struct ft_packer *)arg1;
- (void)cashInfoRequestDecode:(id)arg1 subAccount:(id)arg2;
- (void)requestCashInfoForSubAccount:(id)arg1;
- (void)switchUser:(id)arg1;
- (void)requestAccountInfoForSubAccount:(id)arg1;
- (void)setupManager;
- (unsigned long long)marketType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

