//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/NSObject-Protocol.h>

@class NSString;

@protocol FLVersionFileDataManager <NSObject>
+ (BOOL)removeFileLowerThanVersion:(int)arg1;
+ (BOOL)removeAllFileData;
+ (void)checkToCopyFileInBundleToAppDataFolder;
+ (NSString *)currentFilePath;
+ (NSString *)fileDirectoryPath;
+ (NSString *)fileExtension;
+ (NSString *)fileBaseName;
+ (int)currentFileVersion;
+ (unsigned long long)allFileDataSize;
- (void)saveAllDataToFile;
@end

