//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FTCodingModel.h>

#import <FTEngine/NSCopying-Protocol.h>

@class FLStock, NSArray, NSString;

@interface FLWarrantQuery : FTCodingModel <NSCopying>
{
    BOOL _sortAscend;
    int _issuerId;
    unsigned int _currentPriceMin;
    unsigned int _currentPriceMax;
    int _streetMin;
    int _streetMax;
    unsigned int _strikePriceMin;
    unsigned int _strikePriceMax;
    unsigned int _conversionMin;
    unsigned int _conversionMax;
    int _premiumMin;
    int _premiumMax;
    unsigned int _recoveryPriceMin;
    unsigned int _recoveryPriceMax;
    unsigned int _impliedMin;
    unsigned int _impliedMax;
    unsigned int _leverageRatioMin;
    unsigned int _leverageRatioMax;
    int _deltaMin;
    int _deltaMax;
    int _tradeStatus;
    int _sortType;
    unsigned long long _ID;
    NSString *_name;
    FLStock *_stock;
    NSArray *_types;
    unsigned long long _volumeMin;
    unsigned long long _volumeMax;
    unsigned long long _maturity;
    unsigned long long _priceRelated;
    long long _priceRecoveryRatioMin;
    long long _priceRecoveryRatioMax;
}

+ (id)skipIvarKeys;
+ (id)defaultQuery;
+ (id)issuerNameForID:(int)arg1;
+ (id)issuerNames;
+ (id)maturityNameForID:(int)arg1;
+ (id)maturityNames;
+ (id)warrantFilterRequestModelWithPbModel:(struct WarrantList_Req *)arg1 create:(unsigned int)arg2;
+ (unsigned long long)priceRelatedForPopMin:(int)arg1 max:(int)arg2;
+ (unsigned long long)maturityTypeForCreateTime:(unsigned int)arg1 From:(unsigned int)arg2 to:(unsigned int)arg3;
@property(nonatomic) BOOL sortAscend; // @synthesize sortAscend=_sortAscend;
@property(nonatomic) int sortType; // @synthesize sortType=_sortType;
@property(nonatomic) int tradeStatus; // @synthesize tradeStatus=_tradeStatus;
@property(nonatomic) int deltaMax; // @synthesize deltaMax=_deltaMax;
@property(nonatomic) int deltaMin; // @synthesize deltaMin=_deltaMin;
@property(nonatomic) long long priceRecoveryRatioMax; // @synthesize priceRecoveryRatioMax=_priceRecoveryRatioMax;
@property(nonatomic) long long priceRecoveryRatioMin; // @synthesize priceRecoveryRatioMin=_priceRecoveryRatioMin;
@property(nonatomic) unsigned int leverageRatioMax; // @synthesize leverageRatioMax=_leverageRatioMax;
@property(nonatomic) unsigned int leverageRatioMin; // @synthesize leverageRatioMin=_leverageRatioMin;
@property(nonatomic) unsigned int impliedMax; // @synthesize impliedMax=_impliedMax;
@property(nonatomic) unsigned int impliedMin; // @synthesize impliedMin=_impliedMin;
@property(nonatomic) unsigned int recoveryPriceMax; // @synthesize recoveryPriceMax=_recoveryPriceMax;
@property(nonatomic) unsigned int recoveryPriceMin; // @synthesize recoveryPriceMin=_recoveryPriceMin;
@property(nonatomic) int premiumMax; // @synthesize premiumMax=_premiumMax;
@property(nonatomic) int premiumMin; // @synthesize premiumMin=_premiumMin;
@property(nonatomic) unsigned long long priceRelated; // @synthesize priceRelated=_priceRelated;
@property(nonatomic) unsigned int conversionMax; // @synthesize conversionMax=_conversionMax;
@property(nonatomic) unsigned int conversionMin; // @synthesize conversionMin=_conversionMin;
@property(nonatomic) unsigned int strikePriceMax; // @synthesize strikePriceMax=_strikePriceMax;
@property(nonatomic) unsigned int strikePriceMin; // @synthesize strikePriceMin=_strikePriceMin;
@property(nonatomic) unsigned long long maturity; // @synthesize maturity=_maturity;
@property(nonatomic) unsigned long long volumeMax; // @synthesize volumeMax=_volumeMax;
@property(nonatomic) unsigned long long volumeMin; // @synthesize volumeMin=_volumeMin;
@property(nonatomic) int streetMax; // @synthesize streetMax=_streetMax;
@property(nonatomic) int streetMin; // @synthesize streetMin=_streetMin;
@property(nonatomic) unsigned int currentPriceMax; // @synthesize currentPriceMax=_currentPriceMax;
@property(nonatomic) unsigned int currentPriceMin; // @synthesize currentPriceMin=_currentPriceMin;
@property(retain, nonatomic) NSArray *types; // @synthesize types=_types;
@property(nonatomic) int issuerId; // @synthesize issuerId=_issuerId;
@property(retain, nonatomic) FLStock *stock; // @synthesize stock=_stock;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeParameters:(id)arg1;
- (id)encodedParameters;
@property(readonly, copy, nonatomic) NSString *deltaLocalString;
@property(readonly, copy, nonatomic) NSString *priceRecoveryRatioLocalString;
@property(readonly, copy, nonatomic) NSString *leverageRatioLocalString;
@property(readonly, copy, nonatomic) NSString *premiumLocalString;
@property(readonly, copy, nonatomic) NSString *volumeLocalString;
@property(readonly, copy, nonatomic) NSString *impliedLocalString;
@property(readonly, copy, nonatomic) NSString *conversionLocalString;
@property(readonly, copy, nonatomic) NSString *streetLocalString;
@property(readonly, copy, nonatomic) NSString *recoveryPriceLocalString;
@property(readonly, copy, nonatomic) NSString *strikePriceLocalString;
@property(readonly, copy, nonatomic) NSString *currentPriceLocalString;
@property(readonly, copy, nonatomic) NSString *priceRelatedLocalString;
@property(readonly, copy, nonatomic) NSString *maturityLocalString;
@property(readonly, copy, nonatomic) NSString *issuerNameLocalString;
@property(readonly, copy, nonatomic) NSString *stockNameLocalString;
@property(readonly, copy, nonatomic) NSString *desc;

@end

