//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLFilterModel.h>

@class NSString;

@interface FLWarrantFilterModel : FLFilterModel
{
    NSString *_mName;
    NSString *_mCode;
    int _issuerId;
    int _type;
    unsigned int _strikePrice;
    unsigned int _conversionRatio;
    unsigned int _lastClosePrice;
    unsigned int _recoveryPrice;
    unsigned int _stockOwnerPrice;
    unsigned int _currentPrice;
    unsigned int _askPrice;
    unsigned int _buyPrice;
    float _streetRate;
    unsigned int _high;
    unsigned int _low;
    unsigned int _impliedVolatility;
    int _delta;
    int _status;
    unsigned int _streetRateNew;
    unsigned long long _stockOwnerId;
    unsigned long long _maturityTime;
    unsigned long long _lastTradeTime;
    unsigned long long _volume;
    unsigned long long _turnover;
    unsigned long long _askVolume;
    unsigned long long _buyVolume;
}

+ (id)modelWithProtoBufferModel:(struct WarrantItem *)arg1;
@property(nonatomic) unsigned int streetRateNew; // @synthesize streetRateNew=_streetRateNew;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) int delta; // @synthesize delta=_delta;
@property(nonatomic) unsigned int impliedVolatility; // @synthesize impliedVolatility=_impliedVolatility;
@property(nonatomic) unsigned int low; // @synthesize low=_low;
@property(nonatomic) unsigned int high; // @synthesize high=_high;
@property(nonatomic) float streetRate; // @synthesize streetRate=_streetRate;
@property(nonatomic) unsigned int buyPrice; // @synthesize buyPrice=_buyPrice;
@property(nonatomic) unsigned int askPrice; // @synthesize askPrice=_askPrice;
@property(nonatomic) unsigned long long buyVolume; // @synthesize buyVolume=_buyVolume;
@property(nonatomic) unsigned long long askVolume; // @synthesize askVolume=_askVolume;
@property(nonatomic) unsigned long long turnover; // @synthesize turnover=_turnover;
@property(nonatomic) unsigned long long volume; // @synthesize volume=_volume;
@property(nonatomic) unsigned int currentPrice; // @synthesize currentPrice=_currentPrice;
@property(nonatomic) unsigned int stockOwnerPrice; // @synthesize stockOwnerPrice=_stockOwnerPrice;
@property(nonatomic) unsigned int recoveryPrice; // @synthesize recoveryPrice=_recoveryPrice;
@property(nonatomic) unsigned int lastClosePrice; // @synthesize lastClosePrice=_lastClosePrice;
@property(nonatomic) unsigned int conversionRatio; // @synthesize conversionRatio=_conversionRatio;
@property(nonatomic) unsigned long long lastTradeTime; // @synthesize lastTradeTime=_lastTradeTime;
@property(nonatomic) unsigned long long maturityTime; // @synthesize maturityTime=_maturityTime;
@property(nonatomic) unsigned int strikePrice; // @synthesize strikePrice=_strikePrice;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) int issuerId; // @synthesize issuerId=_issuerId;
@property(nonatomic) unsigned long long stockOwnerId; // @synthesize stockOwnerId=_stockOwnerId;
- (void).cxx_destruct;
- (void)updateWarrantCodeAndName;
- (id)name;
@property(readonly, copy, nonatomic) NSString *code;
@property(readonly, copy, nonatomic) NSString *issuerName;
@property(readonly, nonatomic) double amplitude;

@end

