//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/FLManagerProtocol-Protocol.h>

@class NSString;
@protocol FLWatchStockPushDelegate;

@interface FLWatchStockManager : NSObject <FLManagerProtocol>
{
    id <FLWatchStockPushDelegate> _delegate;
}

+ (id)defaultManager;
@property(nonatomic) __weak id <FLWatchStockPushDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)errorWithDomain:(id)arg1 code:(long long)arg2 userInfo:(id)arg3;
- (void)onRecvQuoteDidLogin:(id)arg1;
- (void)watchGroupPushDecode:(struct util_byteios_net *)arg1;
- (void)watchGroupListPushDecode:(struct util_byteios_net *)arg1;
- (void)registerWatchGroupPushNotification;
- (void)registerWatchGroupListPushNotification;
- (void)registerWatchStockPushService;
- (BOOL)uploadWatchStocks:(id)arg1 inGroup:(unsigned int)arg2 forUser:(unsigned long long)arg3 option:(unsigned long long)arg4 groups:(BOOL)arg5 append:(BOOL)arg6 callback:(CDUnknownBlockType)arg7;
- (BOOL)uploadWatchGroups:(id)arg1 forUser:(unsigned long long)arg2 option:(unsigned long long)arg3 groups:(BOOL)arg4 callback:(CDUnknownBlockType)arg5;
- (BOOL)fetchWatchStocksWithGroupID:(unsigned int)arg1 forUser:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3;
- (BOOL)fetchWatchGroupWithUserID:(unsigned long long)arg1 sequenceID:(unsigned long long)arg2 callback:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

