//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <FTEngine/NSCopying-Protocol.h>

@class NSArray, NSString;

@interface FLWatchGroup : NSObject <NSCopying>
{
    BOOL _containHKStock;
    unsigned int _ID;
    NSString *_name;
    NSArray *_stocks;
}

+ (id)pushedWatchGroupWithGroupID:(unsigned int)arg1;
+ (id)reservedUSOptionGroup;
+ (id)reservedWatchGroupWithMarketType:(unsigned long long)arg1;
+ (id)reservedPositionGroup;
+ (id)reservedDefaultGroup;
@property(readonly, nonatomic) BOOL containHKStock; // @synthesize containHKStock=_containHKStock;
@property(copy, nonatomic) NSArray *stocks; // @synthesize stocks=_stocks;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned int ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isCustom;
@property(readonly, nonatomic) BOOL isReserved;
@property(readonly, nonatomic) BOOL isInitialized;
@property(readonly, nonatomic) BOOL isUSOption;
@property(readonly, nonatomic) BOOL isMarket;
@property(readonly, nonatomic) BOOL isPosition;
@property(readonly, nonatomic) BOOL isDefault;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithGroupID:(unsigned int)arg1 name:(id)arg2;
@property(readonly, nonatomic) unsigned long long marketType;

@end

