//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;
@protocol FLWeakKVOObserverCleaner;

@interface FLWeakKVOObserver : NSObject
{
    NSString *_keyPath;
    NSString *_identifier;
    id <FLWeakKVOObserverCleaner> _cleaner;
    NSObject *_observer;
    NSString *_observerClassName;
    NSArray *_callStackSymbols;
}

+ (id)identifierForObserver:(id)arg1 keyPath:(id)arg2;
@property(copy) NSArray *callStackSymbols; // @synthesize callStackSymbols=_callStackSymbols;
@property(copy) NSString *observerClassName; // @synthesize observerClassName=_observerClassName;
@property __weak NSObject *observer; // @synthesize observer=_observer;
@property __weak id <FLWeakKVOObserverCleaner> cleaner; // @synthesize cleaner=_cleaner;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy) NSString *keyPath; // @synthesize keyPath=_keyPath;
- (void).cxx_destruct;
- (id)description;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithObserver:(id)arg1 keyPath:(id)arg2;

@end

