//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FTEngine/FLBaseManager.h>

@class NSString;

@interface FLWorldPlateMananger : FLBaseManager
{
}

+ (void)releaseInstance;
+ (id)shareInstance;
@property(readonly, nonatomic) NSString *worldPlateListDataPath;
- (void)saveWorlPlateList:(id)arg1;
- (id)worldPlateWithPbModel:(struct PriceItem *)arg1;
- (BOOL)fetchWorldPlatesListWithDataType:(unsigned long long)arg1 response:(CDUnknownBlockType)arg2;
- (id)loadWorldPlateList;

@end

