//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FTMessageCenterManager : NSObject
{
    BOOL _hasMorePriceNoticeMsg;
    NSArray *_priceNoticeListArr;
    unsigned long long _nextPriceNoticeCursorId;
}

@property(nonatomic) BOOL hasMorePriceNoticeMsg; // @synthesize hasMorePriceNoticeMsg=_hasMorePriceNoticeMsg;
@property(nonatomic) unsigned long long nextPriceNoticeCursorId; // @synthesize nextPriceNoticeCursorId=_nextPriceNoticeCursorId;
@property(retain, nonatomic) NSArray *priceNoticeListArr; // @synthesize priceNoticeListArr=_priceNoticeListArr;
- (void).cxx_destruct;
- (id)convertToPriceNoticeMessageModelWithMsgItem:(struct MsgItem)arg1;
@property(readonly, nonatomic) NSArray *priceNoticeList;
@property(readonly, nonatomic) BOOL hasMorePriceNoticeMessage;
- (void)deletePriceNoticeMessageHistoryWithMessageIdList:(id)arg1;
- (void)fetchPriceNoticeMessageHistoryListLoadMore:(BOOL)arg1;
- (void)deleteMessageHistory:(unsigned int)arg1 messageIdList:(id)arg2;
- (void)decodeMessageHistoryInfo:(struct GetMsgHistoryFullRsp *)arg1 loadMore:(BOOL)arg2;
- (id)getMessageFetchDoneNotifyNameWithType:(unsigned int)arg1;
- (id)getMessageUpdateNotifyNameWithType:(unsigned int)arg1;
- (void)fetchMessageHistoryListWithType:(unsigned int)arg1 loadMore:(BOOL)arg2;
- (void)deleteMessageHistoryWithType:(unsigned int)arg1 messageIdList:(id)arg2;
- (void)messageCenterPushInfoDecode:(struct util_byteios_net *)arg1;
- (void)onQuoteServerDidLogin:(id)arg1;
- (void)dealloc;
- (id)init;

@end

