//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KeyHelper : NSObject
{
}

- (id)exportRSAPublicKeyToPEM:(id)arg1 keySize:(int)arg2;
- (id)PEMKeyFromDERKey:(id)arg1;
- (id)exportRSAPublicKeyToDER:(id)arg1 keySize:(int)arg2;
- (int)encodeASN1LengthParameterWithLength:(int)arg1 buffer:(char *)arg2;
- (int)bytesNeededForRepresentingInter:(int)arg1;
- (struct OpaqueSecKeyRef *)_getKeyNamed:(id)arg1;
- (struct OpaqueSecKeyRef *)getPrivateKeyRefWithTag:(id)arg1;
- (id)getPublicKeyBitsWithtag:(id)arg1;
- (int)derEncodingGetSizeFrom:(id)arg1 at:(int *)arg2;
- (id)getPublicKeyMod;
- (id)getPublicKeyModFromKeyData:(id)arg1;
- (id)getPublicKeyExp;
- (id)getPublicKeyExpFromKeyData:(id)arg1;
- (id)getPublicKeyBits:(id)arg1;

@end

