//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@class NSString;

@interface NSDate (FLAdditions)
+ (id)timeZoneStringForUSDate:(id)arg1;
+ (BOOL)isTradeDayTime:(unsigned int)arg1 continousWithTime:(unsigned int)arg2 withCalendar:(id)arg3;
+ (unsigned int)normalizedToDayEndForTime:(unsigned int)arg1 withCalendar:(id)arg2;
+ (unsigned int)normalizedToDayBeginForTime:(unsigned int)arg1 withCalendar:(id)arg2;
@property(readonly, nonatomic) NSString *timeString;
@end

