//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (TBXML_Compression)
+ (id)dataWithBase64EncodedString:(id)arg1;
+ (id)dataWithUncompressedContentsOfFile:(id)arg1;
- (id)gzipInflate;
- (id)gzipDeflate;
- (id)base64EncodingWithLineLength:(unsigned int)arg1;
- (id)base64Encoding;
- (id)initWithBase64EncodedString:(id)arg1;
@end

