//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (TimeShow)
+ (id)getNoSecondStringFromDate:(id)arg1;
+ (id)getStringFromDate:(id)arg1;
+ (id)getDateFromString:(id)arg1;
+ (id)chineseMonthOfTimeStamp:(long long)arg1;
+ (long long)getPastMidNightsFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
+ (id)timestamp2date:(long long)arg1 withFormat:(id)arg2;
+ (id)dateFromString:(id)arg1 withFormat:(id)arg2;
+ (id)dayOfDateTimeFormat:(long long)arg1;
+ (id)monthOfDateTimeFormat:(long long)arg1;
+ (id)yearOfDateTimeFormat:(long long)arg1;
+ (id)thisYear;
+ (long long)getPastHoursFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
+ (long long)getPastHours:(long long)arg1;
+ (long long)getPastMidNightsWithUSDate:(id)arg1;
+ (long long)getPastMidNightsWithDate:(id)arg1;
+ (long long)getPastMidNights:(long long)arg1;
+ (long long)getPastMidNightsInUSTimeZone:(long long)arg1;
+ (id)getDaysDesInUSTimeZone:(long long)arg1;
+ (id)getDaysDes:(long long)arg1;
+ (id)nncChangeTimeToShowDetail:(long long)arg1;
+ (id)nncChangeTimeToShow:(long long)arg1;
+ (id)changeNewsTimeToShow:(id)arg1;
+ (id)changeNewsTimeStampToShow:(long long)arg1;
+ (id)changeIMTimeToShow:(long long)arg1;
+ (id)changeTimeToShow:(long long)arg1;
+ (id)convertToLocalDate:(id)arg1;
+ (id)getNSCalendarInstance;
+ (id)cachedDateFormatter;
@end

