//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (FLAdditions)
+ (id)dataWithBase64EncodedTargetKey:(id)arg1 randKey:(id)arg2;
+ (id)dataWithBase64EncodedString:(id)arg1;
+ (id)dataWithBase32String:(id)arg1;
- (id)aesDecryptWithKey:(id)arg1;
- (id)aesEncryptWithKey:(id)arg1;
- (id)base32String;
- (id)MD5String;
@end

