//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumber.h>

@interface NSNumber (FLAdditions)
+ (id)ftHundredUnitStringForValue:(unsigned long long)arg1 unit:(unsigned long long)arg2 fractionCount:(int)arg3;
+ (id)ftHundredUnitStringForUnit:(unsigned long long)arg1;
+ (unsigned long long)ftHundredUnitForValue:(unsigned long long)arg1;
+ (BOOL)ftConvertValue:(double)arg1 toKMBValue:(double *)arg2 KMBUnit:(unsigned long long *)arg3 KMBUnitSuffix:(id *)arg4;
- (id)ftOneFractionTenThousandString;
- (id)ftTwoFractionSignedMoneyStringRoundDown;
- (id)ftTwoFractionStringRoundDown;
- (id)ftThreeFractionStringRoundDown;
- (id)ftFiveZeroSignedMoneyString;
- (id)ftFiveZeroOneFractionString;
- (id)ftFiveZeroKMBString;
- (id)ftFiveZeroMoneyString;
- (id)ftFiveZeroMinimalFractionString;
- (id)ftFiveZeroMiniTwoFractionString;
- (id)ftUSPriceString;
- (id)ftTwoZeroAutoFractionString;
- (id)ftFiveZeroAutoFractionString;
- (id)ftFiveZeroThreeFractionString;
- (id)ftFiveZeroFiveFractionString;
- (id)ftFitPriceStepString;
- (id)ftPriceDisplayStringWithFractionCount:(int)arg1;
- (id)ftPriceDisplayString;
- (id)ftChineseStringWithoutFraction;
- (id)ftChineseStringWithFraction:(int)arg1;
- (id)ftChineseStringWithFiveMaxSignificantDigits;
- (id)ftChineseString;
- (id)ftKMBStringWithTwoFractionStringAndRoundDown;
- (id)ftKMBStringWithThreeMaxSignificantDigits;
- (id)ftKMBString;
- (id)ftKMBStringWithNumberFormatter:(id)arg1;
- (id)ftSignedString;
- (id)ftString;
@end

