//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (Base64)
+ (id)stringWithBase64EncodedString:(id)arg1;
- (id)base64DecodedData;
- (id)base64DecodedString;
- (id)base64EncodedString;
- (id)base64EncodedStringWithWrapWidth:(unsigned long long)arg1;
@end

