//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (ByteDecode)
+ (id)decodeStringUINT32:(struct util_byteios_net *)arg1;
+ (id)decodeString:(struct util_byteios_net *)arg1;
@end

