//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@interface NSUserDefaults (FLAdditions)
- (void)registerDefaultsBoolValue:(BOOL)arg1 forUserStrKey:(id)arg2;
- (void)removeObjectForUserStrKey:(id)arg1;
- (void)setObject:(id)arg1 forUserStrKey:(id)arg2;
- (id)objectForUserStrKey:(id)arg1;
- (void)removeObjectForUserKey:(unsigned short)arg1;
- (void)setObject:(id)arg1 forUserKey:(unsigned short)arg2;
- (id)objectForUserKey:(unsigned short)arg1;
- (void)setBool:(BOOL)arg1 forUserStrKey:(id)arg2;
- (BOOL)boolForUserStrKey:(id)arg1;
- (void)setInteger:(long long)arg1 forUserKey:(unsigned short)arg2;
- (long long)integerForUserKey:(unsigned short)arg1;
- (void)setBool:(BOOL)arg1 forUserKey:(unsigned short)arg2;
- (BOOL)boolForUserKey:(unsigned short)arg1;
@end

