//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RsaHelper : NSObject
{
}

- (id)rsaDecryptWithData:(id)arg1 key:(struct OpaqueSecKeyRef *)arg2;
- (id)decrypt:(id)arg1 privateTag:(id)arg2;
- (id)encryptWithModulus:(id)arg1 exponent:(id)arg2 publicKeyTag:(id)arg3 content:(id)arg4;
- (void)writePublicKeyModAndExpWithTag:(id)arg1;
- (id)getExponentWithTag:(id)arg1;
- (id)getModulusWithTag:(id)arg1;
- (void)createKeyPairWithTag:(id)arg1 privateTag:(id)arg2;
- (void)test;

@end

