//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2017 15:19:17).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TBXML : NSObject
{
    struct _TBXMLElement *rootXMLElement;
    struct _TBXMLElementBuffer *currentElementBuffer;
    struct _TBXMLAttributeBuffer *currentAttributeBuffer;
    long long currentElement;
    long long currentAttribute;
    char *bytes;
    long long bytesLength;
}

+ (id)tbxmlWithXMLFile:(id)arg1 fileExtension:(id)arg2 error:(id *)arg3;
+ (id)tbxmlWithXMLFile:(id)arg1 fileExtension:(id)arg2;
+ (id)tbxmlWithXMLFile:(id)arg1 error:(id *)arg2;
+ (id)tbxmlWithXMLFile:(id)arg1;
+ (id)tbxmlWithXMLData:(id)arg1 error:(id *)arg2;
+ (id)tbxmlWithXMLData:(id)arg1;
+ (id)tbxmlWithXMLString:(id)arg1 error:(id *)arg2;
+ (id)tbxmlWithXMLString:(id)arg1;
+ (void)iterateAttributesOfElement:(struct _TBXMLElement *)arg1 withBlock:(CDUnknownBlockType)arg2;
+ (void)iterateElementsForQuery:(id)arg1 fromElement:(struct _TBXMLElement *)arg2 withBlock:(CDUnknownBlockType)arg3;
+ (struct _TBXMLElement *)nextSiblingNamed:(id)arg1 searchFromElement:(struct _TBXMLElement *)arg2 error:(id *)arg3;
+ (struct _TBXMLElement *)nextSiblingNamed:(id)arg1 searchFromElement:(struct _TBXMLElement *)arg2;
+ (struct _TBXMLElement *)childElementNamed:(id)arg1 parentElement:(struct _TBXMLElement *)arg2 error:(id *)arg3;
+ (struct _TBXMLElement *)childElementNamed:(id)arg1 parentElement:(struct _TBXMLElement *)arg2;
+ (id)valueOfAttributeNamed:(id)arg1 forElement:(struct _TBXMLElement *)arg2 error:(id *)arg3;
+ (id)valueOfAttributeNamed:(id)arg1 forElement:(struct _TBXMLElement *)arg2;
+ (id)textForElement:(struct _TBXMLElement *)arg1 error:(id *)arg2;
+ (id)textForElement:(struct _TBXMLElement *)arg1;
+ (id)attributeValue:(struct _TBXMLAttribute *)arg1 error:(id *)arg2;
+ (id)attributeValue:(struct _TBXMLAttribute *)arg1;
+ (id)attributeName:(struct _TBXMLAttribute *)arg1 error:(id *)arg2;
+ (id)attributeName:(struct _TBXMLAttribute *)arg1;
+ (id)elementName:(struct _TBXMLElement *)arg1 error:(id *)arg2;
+ (id)elementName:(struct _TBXMLElement *)arg1;
+ (id)errorWithCode:(int)arg1 userInfo:(id)arg2;
+ (id)errorWithCode:(int)arg1;
+ (id)errorTextForCode:(int)arg1;
+ (id)tbxmlWithURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) struct _TBXMLElement *rootXMLElement; // @synthesize rootXMLElement;
- (void)decodeData:(id)arg1 withError:(id *)arg2;
- (void)decodeData:(id)arg1;
- (id)initWithXMLFile:(id)arg1 fileExtension:(id)arg2 error:(id *)arg3;
- (id)initWithXMLFile:(id)arg1 fileExtension:(id)arg2;
- (id)initWithXMLFile:(id)arg1 error:(id *)arg2;
- (id)initWithXMLFile:(id)arg1;
- (id)initWithXMLData:(id)arg1 error:(id *)arg2;
- (id)initWithXMLData:(id)arg1;
- (id)initWithXMLString:(id)arg1 error:(id *)arg2;
- (id)initWithXMLString:(id)arg1;
- (id)init;
- (struct _TBXMLAttribute *)nextAvailableAttribute;
- (struct _TBXMLElement *)nextAvailableElement;
- (void)dealloc;
- (void)decodeBytes;
- (void)allocateBytesOfLength:(long long)arg1 error:(id *)arg2;
- (id)initWithURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;

@end

