# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'com.erwanb.MachInjectSample.Injector' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for com.erwanb.MachInjectSample.Injector

end

target 'com.erwanb.MachInjectSample.Installer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for com.erwanb.MachInjectSample.Installer

end

target 'MachInjectSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MachInjectSample

end

target 'Payload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Payload

end


