// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trader.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TraderRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TraderRoot : GPBRootObject
@end

#pragma mark - PTMessage

typedef GPB_ENUM(PTMessage_FieldNumber) {
  PTMessage_FieldNumber_Version = 1,
  PTMessage_FieldNumber_Seq = 2,
  PTMessage_FieldNumber_Servant = 3,
  PTMessage_FieldNumber_Method = 4,
  PTMessage_FieldNumber_Data_p = 5,
  PTMessage_FieldNumber_Oneway_p = 6,
  PTMessage_FieldNumber_Code = 7,
  PTMessage_FieldNumber_Message = 8,
};

@interface PTMessage : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int64_t seq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *servant;

@property(nonatomic, readwrite, copy, null_resettable) NSString *method;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

/** 是否只是上下行 */
@property(nonatomic, readwrite) BOOL oneway_p;

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - PMNull

@interface PMNull : GPBMessage

@end

#pragma mark - PMHeartBeatRequest

typedef GPB_ENUM(PMHeartBeatRequest_FieldNumber) {
  PMHeartBeatRequest_FieldNumber_UserId = 1,
};

@interface PMHeartBeatRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
