module: trader
author: QCloudTerminalLab
author_url: http://qcloud.com
objc: true
clean: true
framework_root: .
umbrella_header: Pod/Classes/trader.h
sdk: iphoneos
hide_documentation_coverage: true
docset_path: com.tencent.qcloud.trader.docset
